import type { AppLocale } from "@/contexts/language-context";

export type SettingsTabKey =
  | "top"
  | "account"
  | "company"
  | "document-defaults"
  | "display"
  | "payment"
  | "evidence"
  | "team"
  | "other";

const labels = {
  ja: {
    pageTitle: "設定",
    tabs: [
      "設定トップ",
      "アカウント情報",
      "自社情報",
      "文書初期設定",
      "表示設定",
      "決済連携",
      "証憑管理・会計連携",
      "チーム設定",
      "その他設定",
    ] as const,
    tabKeys: [
      "top",
      "account",
      "company",
      "document-defaults",
      "display",
      "payment",
      "evidence",
      "team",
      "other",
    ] as const satisfies readonly SettingsTabKey[],
    cards: [
      {
        key: "account",
        title: "アカウント情報",
        description: "現在ご契約中のサービスプランやアカウント情報の概要を確認できます。",
      },
      {
        key: "company",
        title: "自社情報",
        description:
          "ここに登録した情報は、見積書・納品書・請求書・領収書を新しく作成する際に自動で入力されます。",
      },
      {
        key: "document-defaults",
        title: "文書初期設定",
        description:
          "見積書・納品書・請求書・領収書を新しく作成する際に利用する文書設定を確認・変更できます。",
      },
      {
        key: "display",
        title: "表示設定",
        description: "一覧に表示する件数や、ログイン後に最初に表示するページを変更できます。",
      },
      {
        key: "payment",
        title: "決済連携",
        description: "請求書のクレジットカード決済に関する設定を行います。",
      },
      {
        key: "evidence",
        title: "証憑管理・会計連携",
        description: "会計ソフトとの連携設定を確認・変更できます。",
      },
      {
        key: "team",
        title: "チーム設定",
        description: "チームメンバーの確認・追加・削除ができます。",
      },
      {
        key: "other",
        title: "その他設定",
        description: "オプション機能など、その他の設定を行います。",
      },
    ],
    account: {
      title: "アカウント情報",
      contractSection: "ご契約情報",
      contractEntity: "ご契約事業者",
      contractEntityValue: "Raon",
      contractPlan: "ご契約プラン",
      contractPlanValue: "無料体験プラン",
      planUpgrade: "プランアップグレード",
      yayoiSoftware: "弥生会計・申告ソフト",
      yayoiSoftwareValue: "未連携",
      integrationSettings: "連携設定",
      serviceContractId: "サービス契約ID",
      serviceContractIdValue: "4995171",
      yayoiIdSection: "弥生ID登録情報",
      yayoiIdDesc:
        "メールアドレスやパスワードなどのご登録内容、決済方法の確認・変更ができます。",
      yayoiIdButton: "弥生ID登録情報の確認・変更",
      contractInfoButton: "契約情報の確認・変更",
      systemSection: "システム情報",
      userId: "ユーザーID",
      userIdValue: "1291383",
    },
    company: {
      title: "自社情報",
      intro:
        "ここに登録した情報は、見積書・納品書・請求書・領収書を新しく作成する際に自動で入力されます。既に作成済みの文書には反映されません。",
      basicSection: "基本情報",
      postalCode: "郵便番号",
      postalCodeHint: "000-0000形式(半角)で入力してください",
      postalCodeLookup: "郵便番号から検索",
      address: "住所",
      addressRequired: "1行目必須",
      addressPlaceholder1: "(例) 東京都千代田区日比谷公園1",
      addressPlaceholder2: "(例) パークビル1F",
      companyName: "自社名",
      companyRequired: "1行目必須",
      tel: "TEL",
      fax: "FAX",
      email: "メールアドレス",
      invoiceNumber: "登録番号",
      invoiceNumberHint: "適格請求書(インボイス)に記載が必要な番号です。",
      invoiceNumberLink: "適格請求書について詳しく",
      invoiceNumberPlaceholder: "T1234567890123",
      logo: "ロゴ",
      logoHint: "1MB までの png/jpeg/gif形式に対応",
      seal: "印影",
      sealHint: "1MB までの png/jpeg/gif形式に対応",
      required: "必須",
      orderFormAlert:
        "受注フォーム機能を利用するには、自社情報の必須項目を設定してください。",
    },
    documentDefaults: {
      title: "文書初期設定",
      intro:
        "見積書・納品書・請求書・領収書を新しく作成する際に利用する文書設定を確認・変更できます。",
      commonSection: "文書共通",
      numberingTitle: "文書番号ルールの設定",
      numberingDesc: "文書番号の採番ルールを設定できます。",
      numberingPreview: "プレビュー",
      lineItemsTitle: "明細項目の表示名",
      lineItemHints: {
        name: "30文字以内で入力してください。",
        qty: "10文字以内で入力してください。",
        price: "10文字以内で入力してください。",
        amount: "10文字以内で入力してください。",
      },
      lineItemPlaceholders: {
        name: "品番・品名",
        qty: "数量",
        price: "単価",
        amount: "金額",
      },
      template: "テンプレート",
      templateStandard: "スタンダード",
      changeTemplate: "テンプレートを変更",
      customizeTitle: "カスタマイズオプション",
      customizeDesc: "テンプレートの内容を変更できます。",
      customizeLink: "→ 設定画面へ",
      heading: "表題",
      message: "メッセージ",
      remarks: "備考",
      categoryFormat: "区分記載の形式",
      categoryFormatCheck: "常に区分記載の形式で印字する",
      categoryFormatNote: "税区分が1種類でも区分記載の形式で印字します。",
      sections: {
        estimate: "見積書",
        deliveryNote: "納品書",
        invoice: "請求書",
        receipt: "領収書",
      },
      estimateTitle: "見積書",
      estimateTitleAlt: "御見積書",
      estimateMessage: "下記のとおりお見積申し上げます。",
      estimateRemarks: "見積書の備考",
      estimateRemarksPlaceholder: "(例) いつも有り難うございます。",
      deliveryMessage: "下記のとおり納品いたしました。",
      deliveryRemarks: "納品書の備考",
      deliveryRemarksPlaceholder: "(例) いつも有り難うございます。",
      invoiceTitle: "請求書",
      invoiceMessage: "下記のとおりご請求申し上げます。",
      invoiceRemarks: "請求書の備考",
      invoiceRemarksPlaceholder: "(例) いつも有り難うございます。",
      receiptMessage: "下記のとおり領収いたしました。",
      receiptRemarks: "領収書の備考",
      receiptRemarksPlaceholder: "(例) いつも有り難うございます。",
    },
    display: {
      title: "表示設定",
      listSection: "一覧画面（見積書・納品書・請求書・領収書）",
      listPerPageLabel: "1ページあたりの表示件数",
      listPerPageDesc: "一覧画面に表示する文書の件数を変更します。",
      help: "ヘルプ",
      itemsUnit: "件",
      homeSection: "最初に開くページ",
      homeDesc: "ログイン直後に開くページを設定できます。",
      homeOptionHome: "ホーム",
      pageSizeOptions: ["30", "50", "100"] as const,
    },
    payment: {
      title: "決済連携",
      intro: "SalesFlowで発行する請求書に決済機能を追加します。",
      accountSection: "決済アカウント連携",
      cardPayment: {
        title: "カード決済+ by 弥生株式会社",
        desc: "クレジットカード決済を希望する取引先へのニーズに応えるサービスです。これまでの請求書にクレジットカード決済機能が付けられます。",
        link: "カード決済+ご利用方法",
        button: "連携する",
      },
      deferredPayment: {
        title: "掛け払い+ by 弥生株式会社",
        desc: "面倒な督促・未回収リスクを弥生にお任せできるサービスです。翌月5営業日の早期入金でキャッシュフローも改善できます。",
        link: "掛け払い+について",
        note: "掛け払い+は法人のお客さまのみご利用いただけます。",
        helpPrefix: "掛け払い+のご利用について詳しくは、",
        helpLink: "こちらのヘルプ",
        helpSuffix: "をご覧ください。",
        button: "連携する",
      },
    },
    evidence: {
      title: "証憑管理・会計連携",
      intro: "会計サービスとの連携設定を行います。",
      emailAlert: {
        title: "証憑管理・会計連携機能を使うためにはメールアドレスの確認が必要です。",
        body: "下のボタンをクリックすると、ご登録のメールアドレス（bluebourne907@gmail.com）に確認メールを送信します。メール内のリンクをクリックして、メールアドレスの確認を完了してください。",
        button: "確認メールを送信",
      },
      evidenceSection: "証憑管理連携",
      smartEvidence: {
        title: "スマート証憑管理・デジタルインボイス送信",
        desc: "発行した見積書・納品書・請求書をスマート証憑管理に送信できます。デジタルインボイスの送信も可能です。",
        link: "詳しい説明はこちら",
        button: "連携する",
      },
      accountingSection: "会計アカウント連携",
      yayoi: {
        title: "弥生会計・申告ソフト",
        desc: "請求書のデータを弥生会計・申告ソフトに仕訳（売上）として直接送信できます。",
        products: [
          "弥生会計",
          "弥生会計 オンライン",
          "弥生会計 Next",
          "弥生会計 26",
          "弥生会計 25",
          "弥生会計 24",
          "弥生会計 23",
          "弥生会計 22",
          "弥生会計 21",
          "弥生会計 20",
          "弥生会計 19",
          "弥生青色申告 オンライン",
          "弥生青色申告 26",
          "弥生青色申告 25",
          "弥生白色申告 26",
          "弥生白色申告 25",
        ],
        button: "連携する",
      },
      freee: {
        title: "freee",
        desc: "請求書の内容をfreeeに未決済取引として送信できます。",
        button: "連携する",
      },
    },
    team: {
      title: "チーム設定",
      emailAlert: {
        title: "チーム設定機能を使うためにはメールアドレスの確認が必要です。",
        body: "下のボタンをクリックすると、ご登録のメールアドレス（bluebourne907@gmail.com）に確認メールを送信します。メール内のリンクをクリックして、メールアドレスの確認を完了してください。",
        button: "確認メールを送信",
      },
      inviteSection: "メンバーの招待",
      emailLabel: "メールアドレス",
      inviteButton: "招待メールを送信",
      membersSection: "チームメンバー",
      membersUsage: "利用中: 0 上限: 1",
      membersEmpty: "メンバーはいません",
      pendingSection: "招待中のメンバー",
      pendingEmpty: "招待中のメンバーはいません",
    },
    other: {
      title: "その他設定",
      intro: "SalesFlowの追加機能を設定します。",
      featuresSection: "機能設定",
      integrationsSection: "連携設定",
      enabled: "有効",
      enable: "有効にする",
      disable: "無効にする",
      features: [
        {
          title: "郵送ステータス通知（メール）",
          desc: "請求書の郵送ステータスを、郵送指示受付時と郵送完了時の2回、メールでお知らせします。",
          enabled: true,
        },
        {
          title: "SalesFlowロゴの非表示",
          desc: "請求書・見積書などの文書からSalesFlowロゴを非表示にします。",
        },
        {
          title: "注文書PDF生成",
          desc: "見積書の受取人が注文書PDFをダウンロードできるようにします。",
        },
        {
          title: "品目管理機能",
          desc: "よく使う品目を登録して、正確な入力を支援します。",
          link: "詳しくはこちら",
          enabled: true,
        },
        {
          title: "送信した見積書での発注ボタンの表示",
          desc: "リンク・メールで送信した見積書に「発注」ボタンを表示します。クリック時に通知され、受注情報が作成されます。",
          link: "詳しくはこちら",
          enabled: true,
        },
        {
          title: "請求書の品番・品名ごとの納品日表示",
          desc: "請求書の明細行ごとに納品日を設定・表示できます。",
          link: "詳しくはこちら",
        },
        {
          title: "請求書カード払いの非表示",
          desc: "取引先の請求書画面から「カード払い」ボタンを非表示にします。",
        },
      ],
      calendar: {
        title: "カレンダー連携",
        desc: "請求書の支払期限をカレンダーと同期できます。",
        link: "ご利用方法",
        button: "連携する",
      },
    },
    save: "保存する",
    externalLink: "外部リンク",
    help: "ヘルプ",
    integrate: "連携する",
  },
  ko: {
    pageTitle: "설정",
    tabs: [
      "설정 홈",
      "계정 정보",
      "자사 정보",
      "문서 초기 설정",
      "표시 설정",
      "결제 연동",
      "증빙·회계 연동",
      "팀 설정",
      "기타 설정",
    ] as const,
    tabKeys: [
      "top",
      "account",
      "company",
      "document-defaults",
      "display",
      "payment",
      "evidence",
      "team",
      "other",
    ] as const satisfies readonly SettingsTabKey[],
    cards: [
      {
        key: "account",
        title: "계정 정보",
        description: "현재 이용 중인 서비스 플랜과 계정 정보 개요를 확인할 수 있습니다.",
      },
      {
        key: "company",
        title: "자사 정보",
        description:
          "여기에 등록한 정보는 견적서·납품서·청구서·영수증을 새로 만들 때 자동으로 입력됩니다.",
      },
      {
        key: "document-defaults",
        title: "문서 초기 설정",
        description: "견적서·납품서·청구서·영수증 작성 시 사용하는 문서 설정을 확인·변경할 수 있습니다.",
      },
      {
        key: "display",
        title: "표시 설정",
        description: "목록 표시 건수와 로그인 후 처음 표시할 페이지를 변경할 수 있습니다.",
      },
      {
        key: "payment",
        title: "결제 연동",
        description: "청구서 신용카드 결제 관련 설정을 합니다.",
      },
      {
        key: "evidence",
        title: "증빙·회계 연동",
        description: "회계 소프트웨어 연동 설정을 확인·변경할 수 있습니다.",
      },
      {
        key: "team",
        title: "팀 설정",
        description: "팀 멤버 확인·추가·삭제가 가능합니다.",
      },
      {
        key: "other",
        title: "기타 설정",
        description: "옵션 기능 등 기타 설정을 합니다.",
      },
    ],
    account: {
      title: "계정 정보",
      contractSection: "계약 정보",
      contractEntity: "계약 사업자",
      contractEntityValue: "Raon",
      contractPlan: "계약 플랜",
      contractPlanValue: "무료 체험 플랜",
      planUpgrade: "플랜 업그레이드",
      yayoiSoftware: "弥生会計·신고 소프트",
      yayoiSoftwareValue: "미연동",
      integrationSettings: "연동 설정",
      serviceContractId: "서비스 계약 ID",
      serviceContractIdValue: "4995171",
      yayoiIdSection: "弥生ID 등록 정보",
      yayoiIdDesc: "이메일·비밀번호 등 등록 내용과 결제 방법을 확인·변경할 수 있습니다.",
      yayoiIdButton: "弥生ID 등록 정보 확인·변경",
      contractInfoButton: "계약 정보 확인·변경",
      systemSection: "시스템 정보",
      userId: "사용자 ID",
      userIdValue: "1291383",
    },
    company: {
      title: "자사 정보",
      intro:
        "여기에 등록한 정보는 견적서·납품서·청구서·영수증을 새로 만들 때 자동으로 입력됩니다. 이미 작성된 문서에는 반영되지 않습니다.",
      basicSection: "기본 정보",
      postalCode: "우편번호",
      postalCodeHint: "000-0000 형식(반각)으로 입력해 주세요",
      postalCodeLookup: "우편번호로 검색",
      address: "주소",
      addressRequired: "1행 필수",
      addressPlaceholder1: "(예) 도쿄도 치요다구 ...",
      addressPlaceholder2: "(예) 파크빌 1F",
      companyName: "자사명",
      companyRequired: "1행 필수",
      tel: "TEL",
      fax: "FAX",
      email: "이메일",
      invoiceNumber: "등록번호",
      invoiceNumberHint: "적격청구서(인보イス)에 기재가 필요한 번호입니다.",
      invoiceNumberLink: "적격청구서 자세히",
      invoiceNumberPlaceholder: "T1234567890123",
      logo: "로고",
      logoHint: "1MB 이하 png/jpeg/gif 지원",
      seal: "인영",
      sealHint: "1MB 이하 png/jpeg/gif 지원",
      required: "필수",
      orderFormAlert:
        "수주 폼 기능을 이용하려면 자사 정보의 필수 항목을 설정해 주세요.",
    },
    documentDefaults: {
      title: "문서 초기 설정",
      intro: "견적서·납품서·청구서·영수증 작성 시 사용하는 문서 설정을 확인·변경할 수 있습니다.",
      commonSection: "문서 공통",
      numberingTitle: "문서번호 규칙 설정",
      numberingDesc: "문서번호 채번 규칙을 설정할 수 있습니다.",
      numberingPreview: "미리보기",
      lineItemsTitle: "명세 항목 표시명",
      lineItemHints: {
        name: "30자 이내로 입력해 주세요.",
        qty: "10자 이내로 입력해 주세요.",
        price: "10자 이내로 입력해 주세요.",
        amount: "10자 이내로 입력해 주세요.",
      },
      lineItemPlaceholders: {
        name: "품번·품명",
        qty: "수량",
        price: "단가",
        amount: "금액",
      },
      template: "템플릿",
      templateStandard: "스탠다드",
      changeTemplate: "템플릿 변경",
      customizeTitle: "커스터마이즈 옵션",
      customizeDesc: "템플릿 내용을 변경할 수 있습니다.",
      customizeLink: "→ 설정 화면으로",
      heading: "표제",
      message: "메시지",
      remarks: "비고",
      categoryFormat: "구분 기재 형식",
      categoryFormatCheck: "항상 구분 기재 형식으로 인쇄",
      categoryFormatNote: "세금 구분이 1종류여도 구분 기재 형식으로 인쇄합니다.",
      sections: {
        estimate: "견적서",
        deliveryNote: "납품서",
        invoice: "청구서",
        receipt: "영수증",
      },
      estimateTitle: "견적서",
      estimateTitleAlt: "견적서(敬)",
      estimateMessage: "아래와 같이 견적드립니다.",
      estimateRemarks: "견적서 비고",
      estimateRemarksPlaceholder: "(예) 항상 감사합니다.",
      deliveryMessage: "아래와 같이 납품하였습니다.",
      deliveryRemarks: "납품서 비고",
      deliveryRemarksPlaceholder: "(예) 항상 감사합니다.",
      invoiceTitle: "청구서",
      invoiceMessage: "아래와 같이 청구드립니다.",
      invoiceRemarks: "청구서 비고",
      invoiceRemarksPlaceholder: "(예) 항상 감사합니다.",
      receiptMessage: "아래와 같이 영수하였습니다.",
      receiptRemarks: "영수증 비고",
      receiptRemarksPlaceholder: "(예) 항상 감사합니다.",
    },
    display: {
      title: "표시 설정",
      listSection: "목록 화면 (견적서·납품서·청구서·영수증)",
      listPerPageLabel: "페이지당 표시 건수",
      listPerPageDesc: "목록 화면에 표시할 문서 건수를 변경합니다.",
      help: "도움말",
      itemsUnit: "건",
      homeSection: "처음 열 페이지",
      homeDesc: "로그인 직후 열리는 페이지를 설정할 수 있습니다.",
      homeOptionHome: "홈",
      pageSizeOptions: ["30", "50", "100"] as const,
    },
    payment: {
      title: "결제 연동",
      intro: "SalesFlow에서 발행하는 청구서에 결제 기능을 추가합니다.",
      accountSection: "결제 계정 연동",
      cardPayment: {
        title: "카드 결제+ by 弥生株式会社",
        desc: "신용카드 결제를 원하는 거래처의 니즈에 대응하는 서비스입니다. 기존 청구서에 신용카드 결제 기능을 추가할 수 있습니다.",
        link: "카드 결제+ 이용 방법",
        button: "연동하기",
      },
      deferredPayment: {
        title: "외상 결제+ by 弥生株式会社",
        desc: "번거로운 독촉·미수금 리스크를 弥生에 맡길 수 있는 서비스입니다. 익월 5영업일 조기 입금으로 캐시플로우도 개선할 수 있습니다.",
        link: "외상 결제+ 소개",
        note: "외상 결제+는 법인 고객만 이용할 수 있습니다.",
        helpPrefix: "외상 결제+ 이용에 대한 자세한 내용은 ",
        helpLink: "여기 도움말",
        helpSuffix: "을 참고해 주세요.",
        button: "연동하기",
      },
    },
    evidence: {
      title: "증빙·회계 연동",
      intro: "회계 서비스와의 연동 설정을 합니다.",
      emailAlert: {
        title: "증빙·회계 연동 기능을 사용하려면 이메일 주소 확인이 필요합니다.",
        body: "아래 버튼을 클릭하면 등록된 이메일 주소(bluebourne907@gmail.com)로 확인 메일을 보냅니다. 메일 내 링크를 클릭하여 이메일 확인을 완료해 주세요.",
        button: "확인 메일 보내기",
      },
      evidenceSection: "증빙 관리 연동",
      smartEvidence: {
        title: "스마트 증빙 관리·디지털 인보イス 전송",
        desc: "발행한 견적서·납품서·청구서를 스마트 증빙 관리로 전송할 수 있습니다. 디지털 인보イス 전송도 가능합니다.",
        link: "자세한 설명은 여기",
        button: "연동하기",
      },
      accountingSection: "회계 계정 연동",
      yayoi: {
        title: "弥生会計·신고 소프트",
        desc: "청구서 데이터를 弥生会計·신고 소프트에 분개(매출)로 직접 전송할 수 있습니다.",
        products: [
          "弥生会計",
          "弥生会計 オンライン",
          "弥生会計 Next",
          "弥生会計 26",
          "弥生会計 25",
          "弥生会計 24",
          "弥生会計 23",
          "弥生会計 22",
          "弥生会計 21",
          "弥生会計 20",
          "弥生会計 19",
          "弥生青色申告 オンライン",
          "弥生青色申告 26",
          "弥生青色申告 25",
          "弥生白色申告 26",
          "弥生白色申告 25",
        ],
        button: "연동하기",
      },
      freee: {
        title: "freee",
        desc: "청구서 내용을 freee에 미결제 거래로 전송할 수 있습니다.",
        button: "연동하기",
      },
    },
    team: {
      title: "팀 설정",
      emailAlert: {
        title: "팀 설정 기능을 사용하려면 이메일 주소 확인이 필요합니다.",
        body: "아래 버튼을 클릭하면 등록된 이메일 주소(bluebourne907@gmail.com)로 확인 메일을 보냅니다. 메일 내 링크를 클릭하여 이메일 확인을 완료해 주세요.",
        button: "확인 메일 보내기",
      },
      inviteSection: "멤버 초대",
      emailLabel: "이메일 주소",
      inviteButton: "초대 메일 보내기",
      membersSection: "팀 멤버",
      membersUsage: "이용 중: 0 상한: 1",
      membersEmpty: "멤버가 없습니다",
      pendingSection: "초대 중인 멤버",
      pendingEmpty: "초대 중인 멤버가 없습니다",
    },
    other: {
      title: "기타 설정",
      intro: "SalesFlow 추가 기능을 설정합니다.",
      featuresSection: "기능 설정",
      integrationsSection: "연동 설정",
      enabled: "유효",
      enable: "유효하게 하기",
      disable: "무효하게 하기",
      features: [
        {
          title: "우편 상태 알림 (메일)",
          desc: "청구서 우편 상태를 우편 지시 접수 시와 우편 완료 시 2회 메일로 알려드립니다.",
          enabled: true,
        },
        {
          title: "SalesFlow 로고 숨기기",
          desc: "청구서·견적서 등 문서에서 SalesFlow 로고를 숨깁니다.",
        },
        {
          title: "주문서 PDF 생성",
          desc: "견적서 수신인이 주문서 PDF를 다운로드할 수 있게 합니다.",
        },
        {
          title: "품목 관리 기능",
          desc: "자주 쓰는 품목을 등록하여 정확한 입력을 지원합니다.",
          link: "자세히는 여기",
          enabled: true,
        },
        {
          title: "보낸 견적서의 발주 버튼 표시",
          desc: "링크·메일로 보낸 견적서에 「발주」 버튼을 표시합니다. 클릭 시 알림되고 수주 정보가 생성됩니다.",
          link: "자세히는 여기",
          enabled: true,
        },
        {
          title: "청구서 품번·품명별 납품일 표시",
          desc: "청구서 명세 행별로 납품일을 설정·표시할 수 있습니다.",
          link: "자세히는 여기",
        },
        {
          title: "청구서 카드 결제 숨기기",
          desc: "거래처 청구서 화면에서 「카드 결제」 버튼을 숨깁니다.",
        },
      ],
      calendar: {
        title: "캘린더 연동",
        desc: "청구서 결제 기한을 캘린더와 동기화할 수 있습니다.",
        link: "이용 방법",
        button: "연동하기",
      },
    },
    save: "저장하기",
    externalLink: "외부 링크",
    help: "도움말",
    integrate: "연동하기",
  },
  en: {
    pageTitle: "Settings",
    tabs: [
      "Settings Top",
      "Account",
      "Company",
      "Document Defaults",
      "Display",
      "Payment",
      "Evidence / Accounting",
      "Team",
      "Other",
    ] as const,
    tabKeys: [
      "top",
      "account",
      "company",
      "document-defaults",
      "display",
      "payment",
      "evidence",
      "team",
      "other",
    ] as const satisfies readonly SettingsTabKey[],
    cards: [
      {
        key: "account",
        title: "Account Information",
        description: "View your current service plan and account overview.",
      },
      {
        key: "company",
        title: "Company Information",
        description:
          "Information registered here is auto-filled when creating new estimates, delivery notes, invoices, and receipts.",
      },
      {
        key: "document-defaults",
        title: "Document Defaults",
        description: "Review and change document settings used when creating new documents.",
      },
      {
        key: "display",
        title: "Display Settings",
        description: "Change list page size and the first page shown after login.",
      },
      {
        key: "payment",
        title: "Payment Integration",
        description: "Configure credit card payment settings for invoices.",
      },
      {
        key: "evidence",
        title: "Evidence / Accounting",
        description: "Review and change accounting software integration settings.",
      },
      {
        key: "team",
        title: "Team Settings",
        description: "View, add, or remove team members.",
      },
      {
        key: "other",
        title: "Other Settings",
        description: "Configure optional features and other settings.",
      },
    ],
    account: {
      title: "Account Information",
      contractSection: "Contract Information",
      contractEntity: "Contract Entity",
      contractEntityValue: "Raon",
      contractPlan: "Plan",
      contractPlanValue: "Free Trial",
      planUpgrade: "Upgrade Plan",
      yayoiSoftware: "Yayoi Accounting / Tax",
      yayoiSoftwareValue: "Not linked",
      integrationSettings: "Integration Settings",
      serviceContractId: "Service Contract ID",
      serviceContractIdValue: "4995171",
      yayoiIdSection: "Yayoi ID Registration",
      yayoiIdDesc: "Review or change your email, password, and payment methods.",
      yayoiIdButton: "Review / Change Yayoi ID",
      contractInfoButton: "Review / Change Contract",
      systemSection: "System Information",
      userId: "User ID",
      userIdValue: "1291383",
    },
    company: {
      title: "Company Information",
      intro:
        "Information registered here is auto-filled when creating new documents. Existing documents are not updated.",
      basicSection: "Basic Information",
      postalCode: "Postal Code",
      postalCodeHint: "Enter in 000-0000 format (half-width)",
      postalCodeLookup: "Search by postal code",
      address: "Address",
      addressRequired: "Line 1 required",
      addressPlaceholder1: "(e.g.) 1 Hibiya Park, Chiyoda-ku, Tokyo",
      addressPlaceholder2: "(e.g.) Park Building 1F",
      companyName: "Company Name",
      companyRequired: "Line 1 required",
      tel: "TEL",
      fax: "FAX",
      email: "Email",
      invoiceNumber: "Registration Number",
      invoiceNumberHint: "Required number for qualified invoices.",
      invoiceNumberLink: "About qualified invoices",
      invoiceNumberPlaceholder: "T1234567890123",
      logo: "Logo",
      logoHint: "Supports png/jpeg/gif up to 1MB",
      seal: "Seal",
      sealHint: "Supports png/jpeg/gif up to 1MB",
      required: "Required",
      orderFormAlert:
        "To use the order form feature, please set the required company information fields.",
    },
    documentDefaults: {
      title: "Document Defaults",
      intro: "Review and change document settings used when creating new documents.",
      commonSection: "Common",
      numberingTitle: "Document Number Rule",
      numberingDesc: "Configure how document numbers are assigned.",
      numberingPreview: "Preview",
      lineItemsTitle: "Line Item Labels",
      lineItemHints: {
        name: "Enter within 30 characters.",
        qty: "Enter within 10 characters.",
        price: "Enter within 10 characters.",
        amount: "Enter within 10 characters.",
      },
      lineItemPlaceholders: {
        name: "Item / Name",
        qty: "Qty",
        price: "Unit Price",
        amount: "Amount",
      },
      template: "Template",
      templateStandard: "Standard",
      changeTemplate: "Change Template",
      customizeTitle: "Customization Options",
      customizeDesc: "You can change template contents.",
      customizeLink: "→ Go to settings",
      heading: "Heading",
      message: "Message",
      remarks: "Remarks",
      categoryFormat: "Tax Category Format",
      categoryFormatCheck: "Always print in category format",
      categoryFormatNote: "Prints in category format even with a single tax rate.",
      sections: {
        estimate: "Estimates",
        deliveryNote: "Delivery Notes",
        invoice: "Invoices",
        receipt: "Receipts",
      },
      estimateTitle: "Estimate",
      estimateTitleAlt: "Formal Estimate",
      estimateMessage: "We are pleased to submit the following estimate.",
      estimateRemarks: "Estimate remarks",
      estimateRemarksPlaceholder: "(e.g.) Thank you as always.",
      deliveryMessage: "Delivered as follows.",
      deliveryRemarks: "Delivery note remarks",
      deliveryRemarksPlaceholder: "(e.g.) Thank you as always.",
      invoiceTitle: "Invoice",
      invoiceMessage: "We hereby request payment as follows.",
      invoiceRemarks: "Invoice remarks",
      invoiceRemarksPlaceholder: "(e.g.) Thank you as always.",
      receiptMessage: "Received payment as follows.",
      receiptRemarks: "Receipt remarks",
      receiptRemarksPlaceholder: "(e.g.) Thank you as always.",
    },
    display: {
      title: "Display Settings",
      listSection: "List Screens (Estimates, Delivery Notes, Invoices, Receipts)",
      listPerPageLabel: "Items per page",
      listPerPageDesc: "Change how many documents appear on list screens.",
      help: "Help",
      itemsUnit: "items",
      homeSection: "First page after login",
      homeDesc: "Choose which page opens immediately after you log in.",
      homeOptionHome: "Home",
      pageSizeOptions: ["30", "50", "100"] as const,
    },
    payment: {
      title: "Payment Integration",
      intro: "Add payment features to invoices issued with SalesFlow.",
      accountSection: "Payment Account Integration",
      cardPayment: {
        title: "Card Payment+ by Yayoi Co., Ltd.",
        desc: "Meet client needs for credit card payments. Add credit card payment to your existing invoices.",
        link: "How to use Card Payment+",
        button: "Integrate",
      },
      deferredPayment: {
        title: "Deferred Payment+ by Yayoi Co., Ltd.",
        desc: "Leave collection risk to Yayoi. Improve cash flow with early payment on the 5th business day of the following month.",
        link: "About Deferred Payment+",
        note: "Deferred Payment+ is available for corporate customers only.",
        helpPrefix: "For more details on Deferred Payment+, see ",
        helpLink: "this help page",
        helpSuffix: ".",
        button: "Integrate",
      },
    },
    evidence: {
      title: "Evidence / Accounting Integration",
      intro: "Configure integration with accounting services.",
      emailAlert: {
        title: "Email verification is required to use evidence and accounting integration.",
        body: "Click the button below to send a verification email to your registered address (bluebourne907@gmail.com). Click the link in the email to complete verification.",
        button: "Send verification email",
      },
      evidenceSection: "Evidence Management Integration",
      smartEvidence: {
        title: "Smart Evidence Management / Digital Invoice Transmission",
        desc: "Send issued estimates, delivery notes, and invoices to Smart Evidence Management. Digital invoice transmission is also supported.",
        link: "Detailed explanation here",
        button: "Integrate",
      },
      accountingSection: "Accounting Account Integration",
      yayoi: {
        title: "Yayoi Accounting / Tax Software",
        desc: "Send invoice data directly as journal entries (sales) to Yayoi accounting software.",
        products: [
          "Yayoi Accounting",
          "Yayoi Accounting Online",
          "Yayoi Accounting Next",
          "Yayoi Accounting 26",
          "Yayoi Accounting 25",
          "Yayoi Accounting 24",
          "Yayoi Accounting 23",
          "Yayoi Accounting 22",
          "Yayoi Accounting 21",
          "Yayoi Accounting 20",
          "Yayoi Accounting 19",
          "Yayoi Blue Return Online",
          "Yayoi Blue Return 26",
          "Yayoi Blue Return 25",
          "Yayoi White Return 26",
          "Yayoi White Return 25",
        ],
        button: "Integrate",
      },
      freee: {
        title: "freee",
        desc: "Send invoice contents to freee as unpaid transactions.",
        button: "Integrate",
      },
    },
    team: {
      title: "Team Settings",
      emailAlert: {
        title: "Email verification is required to use team settings.",
        body: "Click the button below to send a verification email to your registered address (bluebourne907@gmail.com). Click the link in the email to complete verification.",
        button: "Send verification email",
      },
      inviteSection: "Invite Members",
      emailLabel: "Email Address",
      inviteButton: "Send invitation email",
      membersSection: "Team Members",
      membersUsage: "In use: 0 / Limit: 1",
      membersEmpty: "No members",
      pendingSection: "Pending Invitations",
      pendingEmpty: "No pending invitations",
    },
    other: {
      title: "Other Settings",
      intro: "Configure additional SalesFlow features.",
      featuresSection: "Feature Settings",
      integrationsSection: "Integration Settings",
      enabled: "Enabled",
      enable: "Enable",
      disable: "Disable",
      features: [
        {
          title: "Mailing Status Notification (Email)",
          desc: "Notifies invoice mailing status via email when instructions are received and when mailing is complete.",
          enabled: true,
        },
        {
          title: "Hide SalesFlow Logo",
          desc: "Hide the SalesFlow logo from documents such as invoices and estimates.",
        },
        {
          title: "Purchase Order PDF Generation",
          desc: "Allow quote recipients to download a purchase order PDF.",
        },
        {
          title: "Item Management",
          desc: "Register frequently used items for accurate input.",
          link: "Learn more",
          enabled: true,
        },
        {
          title: "Order Button on Sent Estimates",
          desc: "Show an Order button on estimates sent via link or email. You are notified and order info is created when clicked.",
          link: "Learn more",
          enabled: true,
        },
        {
          title: "Delivery Date per Line Item on Invoices",
          desc: "Set and display delivery dates for individual line items on invoices.",
          link: "Learn more",
        },
        {
          title: "Hide Invoice Card Payment",
          desc: "Hide the Card Payment button from the client's invoice view.",
        },
      ],
      calendar: {
        title: "Calendar Integration",
        desc: "Sync invoice payment deadlines with your calendar.",
        link: "How to use",
        button: "Integrate",
      },
    },
    save: "Save",
    externalLink: "External link",
    help: "Help",
    integrate: "Integrate",
  },
} as const;

export function getSettingsContent(lang: AppLocale) {
  return labels[lang];
}

export function getSettingsTabHref(lang: AppLocale, tab: SettingsTabKey) {
  const base = `/${lang}/settings`;
  if (tab === "top") {
    return base;
  }
  return `${base}/${tab}`;
}
