import type { AppLocale } from "@/contexts/language-context";

export type InvoiceLocale = "ja" | "ko" | "en";

const labels = {
  ja: {
    // 목록 페이지
    listTitle: "請求書",
    createInvoice: "請求書を新しく作る",
    searchPlaceholder: "取引先名, 請求書番号, 件名, 社内メモ",
    searchDetail: "詳細検索",
    searchButton: "検索",
    tabs: ["未処理", "処理済", "ごみ箱"],
    tabTitles: ["請求書", "処理済みの請求書", "ごみ箱の請求書"],
    tabEmpty: ["請求書はありません", "処理済みの請求書はありません", "ごみ箱の請求書はありません"],
    trashNote: "ごみ箱の請求書は30日後に自動的に削除されます。",
    empty: "請求書はありません",
    displayCount: "表示件数",
    displayCountUnit: "件",
    csvDownload: "CSVダウンロード",
    // 서브 내비
    subNav: ["請求書", "自動作成予約", "一括作成/郵送"],
    // 미입금 상황 배너
    unpaidTitle: "未入金状況",
    unpaidPeriod: "過去1年間",
    unpaidClose: "閉じる",
    overdueLabel: "期限超過",
    unpaidTotalLabel: "未入金合計",
    unpaidZero: "0円/0件",
    unpaidGraphLink: "未入金グラフを表示",
    // 표 컬럼
    tableHeaders: ["ステータス", "文書", "請求日", "お支払い期限", "金額"],
    pagination: "件中",
    // 신규 작성 폼
    newTitle: "請求書の新規作成",
    guideLink: "請求書の作り方がわからない方はこちらをクリック",
    newTabs: ["基本情報", "送付先", "決済設定", "課税設定", "テンプレート"],
    invoiceInfo: "請求情報",
    senderInfo: "請求元情報",
    detailLink: "詳細（住所, 連絡先など）",
    required: "必須",
    requiredLine: "1行目必須",
    client: "取引先",
    issueDate: "請求日",
    paymentDue: "お支払い期限",
    noDate: "指定なし",
    invoiceNumber: "請求書番号",
    invoiceHint: "請求書番号を事前にお好みの形式で設定できます。",
    subject: "件名",
    deliveryDateLink: "納品日を表示したい場合はこちら",
    itemHeaders: ["品番・品名", "数量", "単位", "単価", "税区分", "金額"],
    batchTax: "税区分を一括で",
    change: "変更する",
    addRow: "+ 行の追加",
    printNote: "印刷時には最低10行になります。行の追加は最大80行までです。",
    subtotal: "小計",
    tax: "消費税",
    total: "合計",
    remarks: "備考",
    save: "保存する",
    companyName: "自社名",
    companyHonorific: "様",
    unit: "単位",
    issueDateValue: "2026/05/22",
    invoiceNumberValue: "20260522-002",
    companyValue: "Raon",
    // 送付先 탭
    postalCode: "郵便番号",
    postalCodePlaceholder: "000-0000形式（半角）で入力してください",
    postalCodeLookup: "郵便番号から検索",
    recipientAddressNote: "送付先の住所になります。郵送する場合は必ず入力してください。",
    address: "住所",
    recipientName: "名前",
    recipientNameNote: "郵送する場合は1行目の名前が必須になります。\n宛名は請求書送付先の「名前」の設定の後に付与されます。",
    companyNamePlaceholder: "（例）会社または個人名",
    departmentPlaceholder: "（例）部署名",
    sectionPlaceholder: "（例）課名",
    contactPlaceholder: "（例）担当者名",
    envelopePreviewTitle: "封筒宛名 印字イメージ",
    billingMonthLink: "請求月を表示したい場合はこちら",
    // 決済設定 탭
    paymentSettingsTitle: "決済オプション",
    paymentSettingsNote: "口座振込以外のお支払い方法を選択できます。",
    paymentNone: "なし",
    paymentCard: "「カード決済+」を有効にする",
    paymentCardDesc: "請求書にクレジットカード決済機能を追加できます。",
    paymentPay: "「出し払い+」を有効にする",
    paymentPayDesc: "請求後の債権・入金回収を代行します。翌月5営業日の早期入金が可能です。法人のみご利用いただけます。",
    settingsLink: "設定画面へ",
    bankTransferTitle: "お振込先",
    bankTransferNote: "銀行口座等を入力します。3件まで登録できます。",
    addBankAccount: "+ 口座の追加",
    documentRemarks: "文書初期設定の備考を使う",
    documentSettings: "文書初期設定",
    // 課税設定 탭
    taxSettingsNote: "自社情報の「課税設定」で初期値を設定できます",
    taxSettingsLink: "設定画面へ",
    taxSettingsTitle: "消費税設定",
    taxSeparate: "税別表示",
    taxIncluded: "税込表示",
    taxExempt: "税込表示（免税）",
    taxRounding: "消費税端数処理",
    taxRoundingNote: "「小計」にかかる消費税の小数点以下の処理方法を選択できます。",
    roundDown: "切り捨て",
    roundUp: "切り上げ",
    roundHalf: "四捨五入",
    withholdingTitle: "源泉徴収税種別",
    withholdingLink: "源泉徴収税の計算方法について",
    withholdingNone: "なし",
    withholdingWith: "あり（復興税あり）",
    withholdingWithout: "あり（復興税なし）",
    // 自動作成予約 페이지
    periodicTitle: "自動作成予約",
    periodicDesc: "毎月、毎年など繰り返して先行する請求書の自動作成を予約する機能です。",
    periodicDescLink: "さらに詳しく",
    periodicCreate: "新しく自動作成予約をする",
    periodicSearch: "取引先, 件名",
    periodicTabs: ["一覧", "ごみ箱"],
    periodicEmpty: "自動作成予約はありません",
    periodicNewAbout: "自動作成予約について",
    periodicNewTabs: ["基本情報", "課税設定", "自動メール送信"],
    startDate: "開始日",
    cycle: "周期",
    cycleMonthly: "毎月",
    cycleYearly: "毎年",
    cycleWeekly: "毎週",
    daySuffix: "日",
    lastDay: "末日",
    endDate: "終了日",
    endDateNone: "なし",
    paymentDueMonthCurrent: "当月",
    paymentDueMonthNext: "翌月",
    separateDateLink: "請求書の作成日を請求日と別にしたい場合",
    periodicLineItemsNotice:
      "取引先名や備考、品番・品名などの各項目に「{month}」「{year}」といった可変の文字列を設定すると、請求日にあわせて自動で更新されます。",
    periodicEmailTitle: "自動メール送信",
    periodicEmailNote: "請求書の自動作成時に、取引先へメールを自動送信できます。",
    periodicEmailEnable: "自動メール送信を有効にする",
    periodicEmailSubject: "件名",
    periodicEmailBody: "本文",
    periodicEmailSubjectPlaceholder: "請求書を送付いたします",
    periodicEmailBodyPlaceholder: "いつもお世話になっております。\n請求書を送付いたしますのでご確認ください。",
    remarksCounter: "0/1000",
    // 一括作成/郵送 페이지
    csvUploadTitle: "請求書の一括作成（CSVアップロード）",
    csvUploadDesc: "CSVファイルをアップロードすることで、複数の請求書を一括で作成できます。",
    csvUploadTemplateLink: "記入用テンプレート",
    csvUploadTemplateDesc: "をダウンロードし、必要項目を入力の上、アップロードしてください。",
    csvUploadAreaTitle: "ファイルのアップロード",
    csvUploadChoose: "参照 選択",
    csvUploadNoFile: "選択されたファイルはありません",
    csvUploadMailCheck: "アップロード後に郵送手続きへ進む",
    csvUploadButton: "アップロードする",
    csvUploadTaxNote: "取引先管理コードを指定した場合の消費税設定について",
    csvUploadTaxDesc: "取引先管理コードを指定した場合、取引先の消費税設定が自社情報の消費税設定よりも優先されます。取引先の消費税設定を優先したくない場合は、取引先の消費税設定に「設定しない」を設定してください。",
    csvUploadTaxDescLink: "詳細はこちらのヘルプ",
    csvUploadNotesTitle: "ファイルアップロード時の注意点",
    csvUploadNotes: [
      "CSVファイルの行数は最大5MBです。そのリイズを超えるCSVファイルはアップロードできません",
      "一度にアップロードする件数は300件以下にしてください。それ以上の件数では、エラーが発生する場合があります",
    ],
    csvTemplateDownloadTitle: "記入用テンプレートのダウンロード",
    csvTemplateUtf8: "UTF-8版",
    csvTemplateShiftJis: "Shift-JIS版\n（Excelを使用される方はこちら）",
    csvTemplateUtf8Label: "UTF-8版 記入用テンプレート",
    csvTemplateShiftJisLabel: "Shift-JIS版 記入用テンプレート",
    csvTemplateUtf8Link: "旧テンプレート（UTF-8）",
    csvTemplateShiftJisLink: "旧テンプレート（Shift-JIS）",
    csvTemplateExcelNote: "※ Excelなどの表計算ソフトで作成できます。（CSV形式で保存してください。）",
    csvTemplateHeaderNote: "※ 1行目のヘッダ行は必須です。",
    csvFormatTitle: "記入用テンプレートの形式",
    csvFormatRows: [
      ["形式", "CSV形式"],
      ["文字エンコーディング", "UTF-8 または Shift-JIS"],
    ],
    csvFormatNote: "保存する際は、上記の形式で保存してください。",
    csvFieldsTitle: "記入用テンプレートの項目説明",
    csvFieldsNote: "記入用テンプレートの各項目は次のようになっています。\n請求元に関する項目は、【自社情報】に設定されているものが適用されます。",
    csvFieldHeaders: ["項目", "必須", "制限", "説明"],
    csvFields: [
      { name: "請求日", required: "○", limit: "日付", desc: "請求日付です。YYYY/MM/DD（西暦年/月/日）の形式で記入してください。\n例：2012/05/25" },
      { name: "請求番号", required: "", limit: "20文字", desc: "請求書に記載される請求番号です。未記入の場合は自動で番号が付与されます。" },
      { name: "件名", required: "", limit: "70文字", desc: "請求書の件名です。" },
      { name: "取引先管理コード", required: "○", limit: "取引先管理コード", desc: "関連付けたい取引先の管理コードを入力してください。" },
      { name: "消費税設定", required: "", limit: "右記", desc: "請求金額の計算を行う際の消費税設定を記入します。EXCLUDE（税別）、INCLUDE（税込）、EXEMPT（免税）のいずれかを記入してください。" },
      { name: "備考", required: "", limit: "1000文字", desc: "請求書に記載される備考です。※列を追加してください。" },
      { name: "GMO-PG会員ID", required: "", limit: "GMO-PGの会員ID", desc: "GMO-PG会員IDを入力してください。※列を追加してください。" },
      { name: "カード決済+有効フラグ", required: "", limit: "1または0", desc: "カード決済を有効にする場合は1を記入します。※列を追加してください。" },
      { name: "カード決済+QRコード印字フラグ", required: "", limit: "1または0", desc: "カード決済を有効にしている場合にQRコードを印字するには1を記入します。※列を追加してください。" },
    ],
    csvSetupWarning: "ご利用前に自社情報を設定してください",
    // テンプレートタブ
    templateTitle: "カスタマイズオプション",
    templateNote: "テンプレートの内容を変更できます。初期値は文書初期設定で変更可能です。",
    templateSettingsLink: "設定画面へ",
    templateChangeButton: "テンプレートを変更",
    templateChangeTitle: "テンプレートの変更",
    templateMessageLabel: "メッセージ",
    templateMessagePlaceholder: "下記のとおりご請求申し上げます。",
    templateFieldsTitle: "明細項目の表示名",
    templateFieldItemName: "品番・品名",
    templateFieldItemNameLimit: "30文字以内で入力してください",
    templateFieldQty: "数量",
    templateFieldQtyLimit: "10文字以内で入力してください",
    templateFieldUnitPrice: "単価",
    templateFieldUnitPriceLimit: "10文字以内で入力してください",
    templateFieldAmount: "金額",
    templateFieldAmountLimit: "10文字以内で入力してください",
    templateModalCancel: "キャンセル",
    templateModalSelect: "選択する",
    templateList: [
      { key: "standard", name: "スタンダード" },
      { key: "standard_overlay", name: "スタンダード-印刷が会社名に重なる" },
      { key: "standard_approval", name: "スタンダード-承認欄つき" },
      { key: "standard_noseals", name: "スタンダード-印刷を表示しない" },
      { key: "standard_noquantity", name: "スタンダード-数量・単価を表示しない" },
      { key: "delivery_invoice", name: "納品書業務請求書" },
      { key: "bank_transfer", name: "口座振替通知書" },
      { key: "envelope", name: "密付封筒対応" },
      { key: "simple_line", name: "シンプルライン" },
    ] as { key: string; name: string }[],
    // プレビューサンプルデータ
    sampleDate: "2013年06月09日",
    sampleDocNo: "請求書番号: 20130602-001",
    sampleClient: "サンプル株式会社 様",
    sampleSubject: "件名：サンプルプロジェクト",
    samplePaymentDue: "お支払い期限：2013年06月30日",
    sampleMessage: "下記のとおりご請求申し上げます。",
    sampleAmountLabel: "ご請求金額",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "ミソカインダイス株式会社",
    sampleAddress: "〒151-0064\n東京都渋谷区松涛 3-13\n鮫ビル1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "企画書作成", qty: "1企業", price: "50,000", amount: "50,000" },
      { name: "デザイン業務他", qty: "1案", price: "80,000", amount: "80,000" },
      { name: "交通費", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "いつもありがとうございます。",
  },
  ko: {
    listTitle: "청구서",
    createInvoice: "청구서를 새로 만들기",
    searchPlaceholder: "거래처명, 청구서 번호, 제목, 사내 메모",
    searchDetail: "상세 검색",
    searchButton: "검색",
    tabs: ["미처리", "처리 완료", "휴지통"],
    tabTitles: ["청구서", "처리 완료된 청구서", "휴지통의 청구서"],
    tabEmpty: ["청구서가 없습니다", "처리 완료된 청구서가 없습니다", "휴지통의 청구서가 없습니다"],
    trashNote: "휴지통의 청구서는 30일 후 자동으로 삭제됩니다.",
    empty: "청구서가 없습니다",
    displayCount: "표시 건수",
    displayCountUnit: "건",
    csvDownload: "CSV 다운로드",
    subNav: ["청구서", "자동 작성 예약", "일괄 작성/발송"],
    unpaidTitle: "미입금 현황",
    unpaidPeriod: "최근 1년간",
    unpaidClose: "닫기",
    overdueLabel: "기한 초과",
    unpaidTotalLabel: "미입금 합계",
    unpaidZero: "0원/0건",
    unpaidGraphLink: "미입금 그래프 표시",
    tableHeaders: ["상태", "문서", "청구일", "결제 기한", "금액"],
    pagination: "건 중",
    newTitle: "청구서 신규 작성",
    guideLink: "청구서 작성 방법을 모르시는 분은 클릭",
    newTabs: ["기본 정보", "수신처", "결제 설정", "과세 설정", "템플릿"],
    invoiceInfo: "청구 정보",
    senderInfo: "청구원 정보",
    detailLink: "상세(주소, 연락처 등)",
    required: "필수",
    requiredLine: "1행 필수",
    client: "거래처",
    issueDate: "청구일",
    paymentDue: "결제 기한",
    noDate: "지정 없음",
    invoiceNumber: "청구서 번호",
    invoiceHint: "청구서 번호 형식을 미리 원하는 방식으로 설정할 수 있습니다.",
    subject: "제목",
    deliveryDateLink: "납품일을 표시하려면 클릭",
    itemHeaders: ["품번·품명", "수량", "단위", "단가", "세금 구분", "금액"],
    batchTax: "세금 구분 일괄",
    change: "변경하기",
    addRow: "+ 행 추가",
    printNote: "인쇄 시 최소 10행이 됩니다. 행 추가는 최대 80행까지 가능합니다.",
    subtotal: "소계",
    tax: "소비세",
    total: "합계",
    remarks: "비고",
    save: "저장하기",
    companyName: "자사명",
    companyHonorific: "님",
    unit: "단위",
    issueDateValue: "2026/05/22",
    invoiceNumberValue: "20260522-002",
    companyValue: "Raon",
    postalCode: "우편번호",
    postalCodePlaceholder: "000-0000 형식(반각)으로 입력해 주세요",
    postalCodeLookup: "우편번호로 검색",
    recipientAddressNote: "수신처 주소입니다. 우편 발송 시 반드시 입력해 주세요.",
    address: "주소",
    recipientName: "이름",
    recipientNameNote: "우편 발송 시 1행 이름이 필수입니다.\n수신처는 청구서 수신처 '이름' 설정 뒤에 추가됩니다.",
    companyNamePlaceholder: "（예）법인명 또는 개인명",
    departmentPlaceholder: "（예）부서명",
    sectionPlaceholder: "（예）과명",
    contactPlaceholder: "（예）담당자명",
    envelopePreviewTitle: "봉투 수신인 인쇄 이미지",
    billingMonthLink: "청구월을 표시하려면 클릭",
    paymentSettingsTitle: "결제 옵션",
    paymentSettingsNote: "계좌 이체 외 결제 방법을 선택할 수 있습니다.",
    paymentNone: "없음",
    paymentCard: "「카드 결제+」 활성화",
    paymentCardDesc: "청구서에 신용카드 결제 기능을 추가할 수 있습니다.",
    paymentPay: "「나중결제+」 활성화",
    paymentPayDesc: "청구 후 채권·입금 수금을 대행합니다. 익월 5영업일 조기 입금이 가능합니다. 법인만 이용 가능합니다.",
    settingsLink: "설정 화면으로",
    bankTransferTitle: "입금 계좌",
    bankTransferNote: "은행 계좌 등을 입력합니다. 3건까지 등록할 수 있습니다.",
    addBankAccount: "+ 계좌 추가",
    documentRemarks: "문서 초기 설정의 비고 사용",
    documentSettings: "문서 초기 설정",
    taxSettingsNote: "자사 정보의 「과세 설정」에서 초기값을 설정할 수 있습니다",
    taxSettingsLink: "설정 화면으로",
    taxSettingsTitle: "소비세 설정",
    taxSeparate: "세별 표시",
    taxIncluded: "세포함 표시",
    taxExempt: "세포함 표시（면세）",
    taxRounding: "소비세 단수 처리",
    taxRoundingNote: "「소계」에 부과되는 소비세 소수점 이하 처리 방법을 선택할 수 있습니다.",
    roundDown: "버림",
    roundUp: "올림",
    roundHalf: "반올림",
    withholdingTitle: "원천징수세 종별",
    withholdingLink: "원천징수세 계산 방법에 대하여",
    withholdingNone: "없음",
    withholdingWith: "있음（부흥세 있음）",
    withholdingWithout: "있음（부흥세 없음）",
    periodicTitle: "자동 작성 예약",
    periodicDesc: "매월, 매년 반복해서 선행하는 청구서 자동 작성을 예약하는 기능입니다.",
    periodicDescLink: "자세히 보기",
    periodicCreate: "새 자동 작성 예약 만들기",
    periodicSearch: "거래처, 제목",
    periodicTabs: ["목록", "휴지통"],
    periodicEmpty: "자동 작성 예약이 없습니다",
    periodicNewAbout: "자동 작성 예약 안내",
    periodicNewTabs: ["기본 정보", "과세 설정", "자동 메일 발송"],
    startDate: "시작일",
    cycle: "주기",
    cycleMonthly: "매월",
    cycleYearly: "매년",
    cycleWeekly: "매주",
    daySuffix: "일",
    lastDay: "말일",
    endDate: "종료일",
    endDateNone: "없음",
    paymentDueMonthCurrent: "당월",
    paymentDueMonthNext: "익월",
    separateDateLink: "청구서 작성일과 청구일을 다르게 하려는 경우",
    periodicLineItemsNotice:
      "거래처명, 비고, 품번·품명 등 각 항목에 「{month}」「{year}」 같은 가변 문자열을 설정하면 청구일에 맞춰 자동으로 갱신됩니다.",
    periodicEmailTitle: "자동 메일 발송",
    periodicEmailNote: "청구서 자동 작성 시 거래처에 메일을 자동 발송할 수 있습니다.",
    periodicEmailEnable: "자동 메일 발송 사용",
    periodicEmailSubject: "제목",
    periodicEmailBody: "본문",
    periodicEmailSubjectPlaceholder: "청구서를 송부드립니다",
    periodicEmailBodyPlaceholder: "평소 감사합니다.\n청구서를 송부드리니 확인 부탁드립니다.",
    remarksCounter: "0/1000",
    csvUploadTitle: "청구서 일괄 작성（CSV 업로드）",
    csvUploadDesc: "CSV 파일을 업로드하여 여러 청구서를 일괄 작성할 수 있습니다.",
    csvUploadTemplateLink: "기입용 템플릿",
    csvUploadTemplateDesc: "을 다운로드하여 필요 항목을 입력한 후 업로드해 주세요.",
    csvUploadAreaTitle: "파일 업로드",
    csvUploadChoose: "찾아보기",
    csvUploadNoFile: "선택된 파일 없음",
    csvUploadMailCheck: "업로드 후 우편 발송 절차로 진행",
    csvUploadButton: "업로드하기",
    csvUploadTaxNote: "거래처 관리코드를 지정한 경우 소비세 설정에 대하여",
    csvUploadTaxDesc: "거래처 관리코드를 지정한 경우, 거래처의 소비세 설정이 자사 정보의 소비세 설정보다 우선됩니다.",
    csvUploadTaxDescLink: "자세한 내용은 도움말",
    csvUploadNotesTitle: "파일 업로드 시 주의 사항",
    csvUploadNotes: [
      "CSV 파일 크기는 최대 5MB입니다. 초과하는 파일은 업로드할 수 없습니다.",
      "한 번에 업로드하는 건수는 300건 이하로 해 주세요.",
    ],
    csvTemplateDownloadTitle: "기입용 템플릿 다운로드",
    csvTemplateUtf8: "UTF-8판",
    csvTemplateShiftJis: "Shift-JIS판\n（Excel 사용자）",
    csvTemplateUtf8Label: "UTF-8판 기입용 템플릿",
    csvTemplateShiftJisLabel: "Shift-JIS판 기입용 템플릿",
    csvTemplateUtf8Link: "구 템플릿（UTF-8）",
    csvTemplateShiftJisLink: "구 템플릿（Shift-JIS）",
    csvTemplateExcelNote: "※ Excel 등 스프레드시트 소프트웨어로 작성할 수 있습니다.",
    csvTemplateHeaderNote: "※ 1행 헤더 행은 필수입니다.",
    csvFormatTitle: "기입용 템플릿 형식",
    csvFormatRows: [
      ["형식", "CSV 형식"],
      ["문자 인코딩", "UTF-8 또는 Shift-JIS"],
    ],
    csvFormatNote: "저장 시 위의 형식으로 저장해 주세요.",
    csvFieldsTitle: "기입용 템플릿 항목 설명",
    csvFieldsNote: "기입용 템플릿의 각 항목은 다음과 같습니다.\n청구원에 관한 항목은 【자사 정보】에 설정된 내용이 적용됩니다.",
    csvFieldHeaders: ["항목", "필수", "제한", "설명"],
    csvFields: [
      { name: "청구일", required: "○", limit: "날짜", desc: "청구 날짜입니다. YYYY/MM/DD 형식으로 입력해 주세요." },
      { name: "청구 번호", required: "", limit: "20자", desc: "청구서에 기재되는 청구 번호입니다. 미입력 시 자동으로 번호가 부여됩니다." },
      { name: "제목", required: "", limit: "70자", desc: "청구서의 제목입니다." },
      { name: "거래처 관리코드", required: "○", limit: "거래처 관리코드", desc: "연결할 거래처의 관리코드를 입력해 주세요." },
      { name: "소비세 설정", required: "", limit: "우기", desc: "EXCLUDE（세별）, INCLUDE（세포함）, EXEMPT（면세）중 하나를 입력해 주세요." },
      { name: "비고", required: "", limit: "1000자", desc: "청구서에 기재되는 비고입니다." },
      { name: "카드 결제+ 유효 플래그", required: "", limit: "1 또는 0", desc: "카드 결제를 활성화하는 경우 1을 입력합니다." },
    ],
    csvSetupWarning: "이용 전에 자사 정보를 설정해 주세요",
    templateTitle: "커스터마이즈 옵션",
    templateNote: "템플릿 내용을 변경할 수 있습니다. 초기값은 문서 초기 설정에서 변경 가능합니다.",
    templateSettingsLink: "설정 화면으로",
    templateChangeButton: "템플릿 변경",
    templateChangeTitle: "템플릿 변경",
    templateMessageLabel: "메시지",
    templateMessagePlaceholder: "아래와 같이 청구드립니다.",
    templateFieldsTitle: "명세 항목의 표시명",
    templateFieldItemName: "품번·품명",
    templateFieldItemNameLimit: "30자 이내로 입력해 주세요",
    templateFieldQty: "수량",
    templateFieldQtyLimit: "10자 이내로 입력해 주세요",
    templateFieldUnitPrice: "단가",
    templateFieldUnitPriceLimit: "10자 이내로 입력해 주세요",
    templateFieldAmount: "금액",
    templateFieldAmountLimit: "10자 이내로 입력해 주세요",
    templateModalCancel: "취소",
    templateModalSelect: "선택하기",
    templateList: [
      { key: "standard", name: "스탠다드" },
      { key: "standard_overlay", name: "스탠다드-회사명 겹침" },
      { key: "standard_approval", name: "스탠다드-승인란 있음" },
      { key: "standard_noseals", name: "스탠다드-인장 표시 없음" },
      { key: "standard_noquantity", name: "스탠다드-수량·단가 표시 없음" },
      { key: "delivery_invoice", name: "납품서 겸용 청구서" },
      { key: "bank_transfer", name: "구좌 대체 통지서" },
      { key: "envelope", name: "봉투 대응" },
      { key: "simple_line", name: "심플 라인" },
    ] as { key: string; name: string }[],
    sampleDate: "2013년 06월 09일",
    sampleDocNo: "청구서 번호: 20130602-001",
    sampleClient: "샘플 주식회사 귀중",
    sampleSubject: "건명：샘플 프로젝트",
    samplePaymentDue: "결제 기한：2013년 06월 30일",
    sampleMessage: "아래와 같이 청구드립니다.",
    sampleAmountLabel: "청구 금액",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "미소카인다이스 주식회사",
    sampleAddress: "〒151-0064\n도쿄도 시부야구 마쓰자와 3-13\n사메 빌딩 1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "기획서 작성", qty: "1건", price: "50,000", amount: "50,000" },
      { name: "디자인 업무 외", qty: "1건", price: "80,000", amount: "80,000" },
      { name: "교통비", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "항상 감사합니다.",
  },
  en: {
    listTitle: "Invoices",
    createInvoice: "Create a new invoice",
    searchPlaceholder: "Client, invoice number, subject, internal memo",
    searchDetail: "Advanced search",
    searchButton: "Search",
    tabs: ["Open", "Processed", "Trash"],
    tabTitles: ["Invoices", "Processed invoices", "Trash"],
    tabEmpty: ["No invoices found", "No processed invoices found", "No invoices in trash"],
    trashNote: "Invoices in the trash will be automatically deleted after 30 days.",
    empty: "No invoices found",
    displayCount: "Show",
    displayCountUnit: "items",
    csvDownload: "Download CSV",
    subNav: ["Invoices", "Auto-create schedule", "Bulk create/send"],
    unpaidTitle: "Unpaid status",
    unpaidPeriod: "Past 1 year",
    unpaidClose: "Close",
    overdueLabel: "Overdue",
    unpaidTotalLabel: "Total unpaid",
    unpaidZero: "¥0 / 0",
    unpaidGraphLink: "Show unpaid graph",
    tableHeaders: ["Status", "Document", "Invoice date", "Payment due", "Amount"],
    pagination: "of",
    newTitle: "Create invoice",
    guideLink: "Click here if you need help creating an invoice",
    newTabs: ["Basic info", "Recipient", "Payment settings", "Tax settings", "Template"],
    invoiceInfo: "Invoice information",
    senderInfo: "Issuer information",
    detailLink: "Details (address, contact, etc.)",
    required: "Required",
    requiredLine: "Line 1 required",
    client: "Client",
    issueDate: "Invoice date",
    paymentDue: "Payment due",
    noDate: "Not specified",
    invoiceNumber: "Invoice number",
    invoiceHint: "You can preset your preferred invoice number format.",
    subject: "Subject",
    deliveryDateLink: "Click here to show delivery date",
    itemHeaders: ["Item code / name", "Qty", "Unit", "Unit price", "Tax", "Amount"],
    batchTax: "Apply tax rate",
    change: "Change",
    addRow: "+ Add row",
    printNote: "At least 10 rows are printed. You can add up to 80 rows.",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    remarks: "Notes",
    save: "Save",
    companyName: "Company name",
    companyHonorific: "",
    unit: "Unit",
    issueDateValue: "2026/05/22",
    invoiceNumberValue: "20260522-002",
    companyValue: "Raon",
    postalCode: "Postal code",
    postalCodePlaceholder: "Enter in 000-0000 format",
    postalCodeLookup: "Look up by postal code",
    recipientAddressNote: "This is the recipient's address. Required for postal delivery.",
    address: "Address",
    recipientName: "Name",
    recipientNameNote: "Line 1 name is required for postal delivery.\nThe recipient name is appended after the invoice recipient's 'Name' setting.",
    companyNamePlaceholder: "(e.g.) Company or individual name",
    departmentPlaceholder: "(e.g.) Department",
    sectionPlaceholder: "(e.g.) Section",
    contactPlaceholder: "(e.g.) Contact person",
    envelopePreviewTitle: "Envelope address print preview",
    billingMonthLink: "Click here to show billing month",
    paymentSettingsTitle: "Payment options",
    paymentSettingsNote: "You can select payment methods other than bank transfer.",
    paymentNone: "None",
    paymentCard: "Enable \"Card payment+\"",
    paymentCardDesc: "Add credit card payment functionality to invoices.",
    paymentPay: "Enable \"Deferred payment+\"",
    paymentPayDesc: "We collect receivables and payments on your behalf. Early payment available within 5 business days of the following month. For corporations only.",
    settingsLink: "Go to settings",
    bankTransferTitle: "Bank account",
    bankTransferNote: "Enter bank account details. Up to 3 accounts can be registered.",
    addBankAccount: "+ Add account",
    documentRemarks: "Use default document remarks",
    documentSettings: "Document default settings",
    taxSettingsNote: "You can set the default value in your company's \"Tax settings\"",
    taxSettingsLink: "Go to settings",
    taxSettingsTitle: "Tax settings",
    taxSeparate: "Tax separate",
    taxIncluded: "Tax included",
    taxExempt: "Tax included (exempt)",
    taxRounding: "Tax rounding",
    taxRoundingNote: "Select how to handle fractions below 1 unit in consumption tax on the subtotal.",
    roundDown: "Round down",
    roundUp: "Round up",
    roundHalf: "Round half",
    withholdingTitle: "Withholding tax type",
    withholdingLink: "About withholding tax calculation",
    withholdingNone: "None",
    withholdingWith: "Yes (with recovery tax)",
    withholdingWithout: "Yes (without recovery tax)",
    periodicTitle: "Auto-create schedule",
    periodicDesc: "Schedule automatic invoice creation that repeats monthly, yearly, etc.",
    periodicDescLink: "Learn more",
    periodicCreate: "Create new auto-create schedule",
    periodicSearch: "Client, subject",
    periodicTabs: ["List", "Trash"],
    periodicEmpty: "No auto-create schedules",
    periodicNewAbout: "About auto-create schedules",
    periodicNewTabs: ["Basic info", "Tax settings", "Auto email"],
    startDate: "Start date",
    cycle: "Cycle",
    cycleMonthly: "Monthly",
    cycleYearly: "Yearly",
    cycleWeekly: "Weekly",
    daySuffix: " day",
    lastDay: "Last day",
    endDate: "End date",
    endDateNone: "None",
    paymentDueMonthCurrent: "Current month",
    paymentDueMonthNext: "Next month",
    separateDateLink: "If you want the creation date to differ from the invoice date",
    periodicLineItemsNotice:
      "If you set variables such as \"{month}\" or \"{year}\" in client name, remarks, or item fields, they will update automatically based on the invoice date.",
    periodicEmailTitle: "Automatic email",
    periodicEmailNote: "You can automatically send an email to the client when an invoice is created.",
    periodicEmailEnable: "Enable automatic email",
    periodicEmailSubject: "Subject",
    periodicEmailBody: "Body",
    periodicEmailSubjectPlaceholder: "Sending your invoice",
    periodicEmailBodyPlaceholder: "Thank you for your business.\nPlease find the attached invoice.",
    remarksCounter: "0/1000",
    csvUploadTitle: "Bulk invoice creation (CSV upload)",
    csvUploadDesc: "Upload a CSV file to create multiple invoices at once.",
    csvUploadTemplateLink: "entry template",
    csvUploadTemplateDesc: "Download, fill in the required fields, then upload.",
    csvUploadAreaTitle: "Upload file",
    csvUploadChoose: "Browse",
    csvUploadNoFile: "No file selected",
    csvUploadMailCheck: "Proceed to postal sending after upload",
    csvUploadButton: "Upload",
    csvUploadTaxNote: "About tax settings when specifying client management codes",
    csvUploadTaxDesc: "When a client management code is specified, the client's tax settings take priority over company-wide settings.",
    csvUploadTaxDescLink: "See help for details",
    csvUploadNotesTitle: "Notes on file upload",
    csvUploadNotes: [
      "CSV file size must be 5MB or less. Files exceeding this size cannot be uploaded.",
      "Upload no more than 300 records at a time. Errors may occur with larger batches.",
    ],
    csvTemplateDownloadTitle: "Download entry template",
    csvTemplateUtf8: "UTF-8 version",
    csvTemplateShiftJis: "Shift-JIS version\n(For Excel users)",
    csvTemplateUtf8Label: "UTF-8 entry template",
    csvTemplateShiftJisLabel: "Shift-JIS entry template",
    csvTemplateUtf8Link: "Legacy template (UTF-8)",
    csvTemplateShiftJisLink: "Legacy template (Shift-JIS)",
    csvTemplateExcelNote: "※ Can be created with Excel or other spreadsheet software. (Save as CSV format.)",
    csvTemplateHeaderNote: "※ The header row on line 1 is required.",
    csvFormatTitle: "Entry template format",
    csvFormatRows: [
      ["Format", "CSV"],
      ["Character encoding", "UTF-8 or Shift-JIS"],
    ],
    csvFormatNote: "Save in the format specified above.",
    csvFieldsTitle: "Entry template field descriptions",
    csvFieldsNote: "Each field in the entry template is as follows.\nFields related to the issuer use values set in [Company info].",
    csvFieldHeaders: ["Field", "Required", "Limit", "Description"],
    csvFields: [
      { name: "Invoice date", required: "○", limit: "Date", desc: "The invoice date. Enter in YYYY/MM/DD format.\nExample: 2012/05/25" },
      { name: "Invoice number", required: "", limit: "20 chars", desc: "The invoice number shown on the invoice. Auto-assigned if left blank." },
      { name: "Subject", required: "", limit: "70 chars", desc: "The subject of the invoice." },
      { name: "Client code", required: "○", limit: "Client code", desc: "Enter the management code of the client to link." },
      { name: "Tax setting", required: "", limit: "See right", desc: "Enter EXCLUDE (tax separate), INCLUDE (tax included), or EXEMPT." },
      { name: "Notes", required: "", limit: "1000 chars", desc: "Notes to display on the invoice." },
      { name: "Card payment+ flag", required: "", limit: "1 or 0", desc: "Enter 1 to enable card payment." },
    ],
    csvSetupWarning: "Please configure your company information before use",
    templateTitle: "Customize options",
    templateNote: "You can change the template content. The default can be changed in Document defaults.",
    templateSettingsLink: "Go to settings",
    templateChangeButton: "Change template",
    templateChangeTitle: "Change template",
    templateMessageLabel: "Message",
    templateMessagePlaceholder: "We hereby submit the following invoice.",
    templateFieldsTitle: "Line item display names",
    templateFieldItemName: "Item code / name",
    templateFieldItemNameLimit: "Up to 30 characters",
    templateFieldQty: "Qty",
    templateFieldQtyLimit: "Up to 10 characters",
    templateFieldUnitPrice: "Unit price",
    templateFieldUnitPriceLimit: "Up to 10 characters",
    templateFieldAmount: "Amount",
    templateFieldAmountLimit: "Up to 10 characters",
    templateModalCancel: "Cancel",
    templateModalSelect: "Select",
    templateList: [
      { key: "standard", name: "Standard" },
      { key: "standard_overlay", name: "Standard - overlapping company name" },
      { key: "standard_approval", name: "Standard - with approval box" },
      { key: "standard_noseals", name: "Standard - no seals" },
      { key: "standard_noquantity", name: "Standard - no quantity/price" },
      { key: "delivery_invoice", name: "Delivery + invoice" },
      { key: "bank_transfer", name: "Bank transfer notice" },
      { key: "envelope", name: "Envelope-compatible" },
      { key: "simple_line", name: "Simple line" },
    ] as { key: string; name: string }[],
    sampleDate: "June 09, 2013",
    sampleDocNo: "Invoice No: 20130602-001",
    sampleClient: "Sample Corporation",
    sampleSubject: "Subject: Sample Project",
    samplePaymentDue: "Payment due: June 30, 2013",
    sampleMessage: "We hereby submit the following invoice.",
    sampleAmountLabel: "Invoice amount",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "SalesFlow Inc.",
    sampleAddress: "〒151-0064\n3-13 Matsuzawa, Shibuya-ku, Tokyo\nSame Bldg. 1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "Document preparation", qty: "1", price: "50,000", amount: "50,000" },
      { name: "Design work, etc.", qty: "1", price: "80,000", amount: "80,000" },
      { name: "Travel expenses", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "Thank you for your continued business.",
  },
} as const;

export function getInvoiceContent(locale: string) {
  if (locale === "ko" || locale === "en") {
    return labels[locale];
  }

  return labels.ja;
}

export function getInvoiceHref(
  _lang: AppLocale,
  page: "invoices" | "periodic" | "csv_upload" = "invoices",
) {
  const base = "/invoices";
  if (page === "periodic") return `${base}/periodic`;
  if (page === "csv_upload") return `${base}/csv_upload`;
  return base;
}
