"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { sourceCopy, sourceKindLabel, type AiSourceDocumentKind } from "@/components/ai-estimates/source-fields";
import { BookOpen, ChevronDown, ChevronUp, ExternalLink, Sparkles, WandSparkles } from "lucide-react";
import { aiTaxCategoryLabel } from "@/components/ai-estimates/presentation";
import { aiEstimateErrorMessage } from "@/components/ai-estimates/error-message";
import { useLanguage } from "@/contexts/language-context";
import type { AiEstimateDraft, AiMarketResearchResult } from "@/lib/ai/estimates/schemas";
import type { AiDraftApplyOptions } from "@/lib/ai/estimates/apply-draft";
import { generateAiEstimateDraft, getAiEstimateCapabilities, getAiEstimateReferenceOptions, getAiEstimateRecommendations, validateAiEstimateSuggestion, markAiEstimateSuggestionApplied } from "@/lib/actions/ai-estimates";

type ReferenceOption = { id: string; title: string; documentKind: AiSourceDocumentKind; projectName: string; revision: string; validFrom: string | null; validUntil: string | null; status: string };
type Capabilities = { providerOptions: Array<{ provider: "gemini" | "anthropic"; model: string }>; enabled: boolean; canWrite: boolean; approvedSourceCount: number; modelGenerationConfigured: boolean; modelGenerationModel: string | null; externalProcessingAllowed: boolean; webMarketResearchAllowed: boolean; webMarketResearchConfigured: boolean; minimumPriceSamples: number };
type Recommendation = { unit?: string | null; taxCategory?: string; name: string; sampleCount: number; medianPrice: number; p25Price: number; p75Price: number };
type Suggestion = { id: string; context: string; draft: AiEstimateDraft; marketResearch: AiMarketResearchResult | null; mode: "model" | "local"; provider: string; model: string };

const copy = {
  ja: { invalidTax: "原本の税率が未確認です。資料の税率を確認・承認してから利用してください。", retry: "再試行", taxIncluded: "税込", taxExcluded: "税抜", title: "AI見積アシスト", desc: "承認済み資料を検索し、根拠を確認して必要な項目だけ反映します。", model: "生成AI", local: "承認済み資料の検索", localNotice: "外部生成AIを使わず、承認済み資料を検索して下書きを組み立てます。", aiNotice: "外部AIの利用が許可されています。作業説明・要件・前提・対象外と承認済みの品目・単価・文面・作業資料が送信されます。機密情報は入力しないでください。", work: "今回の作業内容", placeholder: "例：採用サイトを5ページ制作。デザインと実装を含む", create: "根拠を検索して下書きを作成", loading: "処理中…", instant: "承認資料の単価", samples: "件", result: "下書きの確認", apply: "選択した内容を反映", applied: "フォームに反映しました。内容を確認して見積を保存してください。", recordFailed: "フォームには反映しましたが、適用履歴を記録できませんでした。", evidence: "参照資料", empty: "現在の取引先・税区分で、十分な件数の単価実績がありません。", library: "資料を管理", hide: "閉じる", show: "開く", web: "公開Webの市場価格も調べる", webQuery: "公開検索語", webNotice: "検索語・市場・通貨を外部へ送信します。顧客名や社内情報は入力しないでください。", webDisabled: "管理者の許可とAPI設定が必要です。", market: "公開Webの参考価格（見積の単価とは別）", country: "市場", currency: "通貨", append: "既存の明細に追加", replace: "既存の明細を置き換える", replaceConfirm: "選択した項目で既存の明細をすべて置き換えます。選択した件名・定型文・備考も上書きします。続けますか？", textConfirm: "選択した件名・定型文・備考を提案内容で上書きします。続けますか？", subject: "件名", message: "定型文", remarks: "備考", fields: "置き換える文面（任意）", insufficient: "単価の根拠不足：金額を確認してください", historical: "過去見積の単価", statistical: "承認資料の価格統計", range: "参考範囲", all: "すべて選択", stale: "条件が変わりました。もう一度検索してください。", error: "処理に失敗しました。接続を確認して再試行してください。", disabled: "AI見積アシストは設定で無効になっています。", readOnly: "閲覧権限では下書きを作成・反映できません。", limit: "明細は合計80行までです。選択を減らすか、置き換えを選んでください。", select: "反映する項目か文面を選択してください。", count: "既存明細", unit: "単価", selectItem: "反映する品目", settings: "設定", noEvidence: "条件の一致する価格の根拠がありません。金額を確認して入力してください。" },
  ko: { invalidTax: "원본의 세율이 미확인 상태입니다. 자료의 세율을 검수·승인한 뒤 사용해 주세요.", retry: "다시 시도", taxIncluded: "세금 포함", taxExcluded: "세금 별도", title: "AI 견적 도우미", desc: "승인된 자료를 검색하고 근거를 확인한 뒤 필요한 항목만 적용합니다.", model: "생성형 AI", local: "승인 자료 검색", localNotice: "외부 생성형 AI 없이 승인된 자료를 검색해 초안을 구성합니다.", aiNotice: "외부 AI 사용이 허용되어 작업 설명·요구사항·전제·제외 조건과 승인된 품목·단가·문구·작업 자료가 전송됩니다. 기밀정보는 입력하지 마세요.", work: "이번 작업 설명", placeholder: "예: 채용 사이트 5페이지 제작, 디자인과 구현 포함", create: "근거 검색 후 초안 만들기", loading: "처리 중…", instant: "승인 자료 단가", samples: "건", result: "초안 검토", apply: "선택한 내용 적용", applied: "폼에 적용했습니다. 내용을 확인한 뒤 견적을 저장해 주세요.", recordFailed: "폼에는 적용했지만 적용 이력을 기록하지 못했습니다.", evidence: "참고 자료", empty: "현재 거래처·세금 기준에서 표본이 충분한 단가가 없습니다.", library: "자료 관리", hide: "닫기", show: "열기", web: "공개 웹 시중가도 조사", webQuery: "공개 검색어", webNotice: "검색어·시장·통화를 외부로 전송합니다. 고객명이나 내부 정보를 입력하지 마세요.", webDisabled: "관리자 허용과 API 설정이 필요합니다.", market: "공개 웹 참고 가격 (견적 단가와 별도)", country: "시장", currency: "통화", append: "기존 명세에 추가", replace: "기존 명세 교체", replaceConfirm: "선택한 항목으로 기존 명세 전체를 교체합니다. 선택한 제목·안내 문구·비고도 덮어씁니다. 계속할까요?", textConfirm: "선택한 제목·안내 문구·비고를 제안된 내용으로 덮어씁니다. 계속할까요?", subject: "제목", message: "안내 문구", remarks: "비고", fields: "교체할 문구 (선택)", insufficient: "단가 근거 부족: 금액을 확인해 주세요", historical: "과거 견적 단가", statistical: "승인 자료 가격 통계", range: "참고 범위", all: "전체 선택", stale: "조건이 변경되었습니다. 다시 검색해 주세요.", error: "처리에 실패했습니다. 연결 상태를 확인하고 다시 시도해 주세요.", disabled: "설정에서 AI 견적 도우미가 비활성화되어 있습니다.", readOnly: "조회 권한으로는 초안 생성·적용을 할 수 없습니다.", limit: "명세는 총 80행까지입니다. 선택을 줄이거나 교체를 선택해 주세요.", select: "적용할 항목이나 문구를 선택해 주세요.", count: "기존 명세", unit: "단가", selectItem: "적용할 품목", settings: "설정", noEvidence: "일치하는 가격 근거가 없습니다. 금액을 직접 확인해 주세요." },
  en: { invalidTax: "The source tax rate is not verified. Review and approve an explicit tax rate before applying this item.", retry: "Retry", taxIncluded: "Tax included", taxExcluded: "Tax excluded", title: "AI estimate assistant", desc: "Search approved sources, inspect the evidence, and apply only what you need.", model: "Generative AI", local: "Approved-source search", localNotice: "Drafts are assembled from approved sources without an external generative model.", aiNotice: "External AI processing is enabled. Work descriptions, requirements, assumptions, exclusions and approved items, prices, wording and work references are sent externally. Do not enter confidential information.", work: "Describe this job", placeholder: "Example: Five-page recruiting site, including design and implementation", create: "Search evidence and create draft", loading: "Working…", instant: "Approved source prices", samples: "samples", result: "Review draft", apply: "Apply selected content", applied: "Applied to the form. Review the result and save your estimate.", recordFailed: "Applied to the form, but the application history could not be recorded.", evidence: "Source evidence", empty: "There are not enough comparable prices for the current client and tax settings.", library: "Manage sources", hide: "Close", show: "Open", web: "Also research public-web market prices", webQuery: "Public search query", webNotice: "The query, market, and currency are sent externally. Do not include client or internal information.", webDisabled: "Admin permission and API configuration are required.", market: "Public-web reference prices (separate from estimate prices)", country: "Market", currency: "Currency", append: "Append to existing lines", replace: "Replace existing lines", replaceConfirm: "Replace all existing lines with the selected items? Selected subject, message, and remarks will also be overwritten.", textConfirm: "Overwrite the selected subject, message, and remarks with the suggested text?", subject: "Subject", message: "Message", remarks: "Remarks", fields: "Text to replace (optional)", insufficient: "Insufficient price evidence: verify the amount", historical: "Historical estimate price", statistical: "Approved-source price statistics", range: "Reference range", all: "Select all", stale: "The request changed. Search again to get a current draft.", error: "The request failed. Check your connection and try again.", disabled: "The estimate assistant is disabled in settings.", readOnly: "Viewers cannot generate or apply drafts.", limit: "An estimate supports 80 lines. Select fewer items or replace the existing lines.", select: "Select at least one item or text field.", count: "Existing lines", unit: "Unit price", selectItem: "Select item", settings: "Settings", noEvidence: "No matching price evidence is available. Verify and enter the amount." },
} as const;

const referenceCopy = {
  ja: { suggestionLimit: "1つの見積には20件までのAI下書きを紐づけられます。明細を置き換えるか、新しい見積で続けてください。", title: "今回使う資料", search: "資料名・案件を検索", auto: "未選択：承認済み資料から自動検索", selected: "選択した資料だけを使います。単価は選択した単価表・過去見積の範囲に限定します。", missing: "この資料は利用できません。取引先・承認状態・適用期間を確認するか、選択から外してください。", empty: "利用できる承認資料がありません。", requirements: "今回の要件・数量・仕様", assumptions: "今回の前提・含む作業", exclusions: "今回の対象外", provider: "下書きの作成方法", automatic: "自動選択", clear: "選択を解除", maximum: "最大10資料", priceList: "承認済み単価表", sourcePrices: "選択資料の単価は、生成後の単価根拠で確認できます。", noneContext: "設計・作業の参考資料なし" },
  ko: { suggestionLimit: "견적 하나에는 AI 초안 20개까지 연결할 수 있습니다. 명세를 교체하거나 새 견적에서 계속해 주세요.", title: "이번에 사용할 자료", search: "자료명·프로젝트 검색", auto: "선택 없음: 승인 자료에서 자동 검색", selected: "선택한 자료만 사용합니다. 단가는 선택한 단가표·과거 견적 범위로 제한됩니다.", missing: "사용할 수 없는 자료입니다. 거래처·승인 상태·적용 기간을 확인하거나 선택에서 제외해 주세요.", empty: "사용할 수 있는 승인 자료가 없습니다.", requirements: "이번 요구사항·수량·사양", assumptions: "이번 전제 조건·포함 작업", exclusions: "이번 제외 작업", provider: "초안 작성 방식", automatic: "자동 선택", clear: "선택 해제", maximum: "최대 10개 자료", priceList: "승인된 단가표", sourcePrices: "선택 자료의 단가는 생성 결과의 단가 근거에서 확인할 수 있습니다.", noneContext: "설계·작업 참고 자료 없음" },
  en: { suggestionLimit: "An estimate can link up to 20 AI drafts. Replace its lines or continue in a new estimate.", title: "Sources for this estimate", search: "Search source or project", auto: "None selected: search approved sources automatically", selected: "Use only selected sources. Prices are limited to the selected price lists and past estimates.", missing: "This source is unavailable. Check its client, approval and validity dates, or remove it from the selection.", empty: "No eligible approved sources.", requirements: "Requirements, quantities and specifications", assumptions: "Assumptions and included work", exclusions: "Excluded work", provider: "Drafting method", automatic: "Automatic", clear: "Clear selection", maximum: "Up to 10 sources", priceList: "Approved price list", sourcePrices: "Prices from your selected sources appear in the generated price evidence.", noneContext: "No design or work references" },
} as const;

export function AiEstimatePanel({ clientId, clientName, subject, taxMode, existingLineCount, onApply }: { clientId: string | null; clientName: string; subject: string; taxMode: "included" | "excluded"; existingLineCount: number; onApply: (draft: AiEstimateDraft, options: AiDraftApplyOptions, suggestionId: string) => { ok: true } | { ok: false; error: string } }) {
  const { lang } = useLanguage();
  const ui = copy[lang];
  const sourceUi = sourceCopy[lang];
  const refUi = referenceCopy[lang];
  const searchParams = useSearchParams();
  const [open, setOpen] = useState(Boolean(searchParams.get("aiSource")));
  const [sourceIds, setSourceIds] = useState<string[]>(() => { const id = searchParams.get("aiSource"); return id ? [id] : []; });
  const [referenceOptions, setReferenceOptions] = useState<{ clientId: string | null; items: ReferenceOption[] } | null>(null);
  const [referenceError, setReferenceError] = useState(false);
  const [referenceQuery, setReferenceQuery] = useState("");
  const [requirements, setRequirements] = useState("");
  const [assumptions, setAssumptions] = useState("");
  const [exclusions, setExclusions] = useState("");
  const [provider, setProvider] = useState<"auto" | "gemini" | "anthropic">("auto");
  const [refreshKey, setRefreshKey] = useState(0);
  const [description, setDescription] = useState("");
  const [recommendations, setRecommendations] = useState<{ key: string; items: Recommendation[]; error?: string } | null>(null);
  const [capabilities, setCapabilities] = useState<Capabilities | null>(null);
  const [capabilityError, setCapabilityError] = useState(false);
  const [suggestion, setSuggestion] = useState<Suggestion | null>(null);
  const [options, setOptions] = useState<AiDraftApplyOptions>({ lineIndexes: [], mode: "append", subject: false, templateMessage: false, remarks: false });
  const [appliedId, setAppliedId] = useState<string | null>(null);
  const applying = useRef(false);
  const applyDraft = useRef(onApply);
  useEffect(() => { applyDraft.current = onApply; }, [onApply]);
  const [applyMessage, setApplyMessage] = useState<string | null>(null);
  const [useWebMarketResearch, setUseWebMarketResearch] = useState(false);
  const [publicSearchQuery, setPublicSearchQuery] = useState("");
  const [marketCountryCode, setMarketCountryCode] = useState<"JP" | "KR" | "US" | "GLOBAL">("JP");
  const [marketCurrency, setMarketCurrency] = useState<"JPY" | "KRW" | "USD">("JPY");
  const [error, setError] = useState<{ context: string; message: string } | null>(null);
  const [pending, startTransition] = useTransition();
  const context = JSON.stringify([clientId, clientName, subject, taxMode, description, useWebMarketResearch, publicSearchQuery, marketCountryCode, marketCurrency, lang, sourceIds, requirements, assumptions, exclusions, provider]);
  const activeContext = useRef(context);
  useEffect(() => { activeContext.current = context; }, [context]);
  const recommendationKey = JSON.stringify([clientId, taxMode]);
  const visibleSuggestion = suggestion?.context === context && suggestion.id !== appliedId ? suggestion : null;
  const webAvailable = capabilities?.webMarketResearchAllowed && capabilities.webMarketResearchConfigured;
  const usesModel = capabilities?.modelGenerationConfigured && capabilities.externalProcessingAllowed;
  const currentReferences = referenceOptions?.clientId === clientId ? referenceOptions.items : null;
  const missingSourceIds = currentReferences ? sourceIds.filter(id => !currentReferences.some(item => item.id === id)) : [];
  const providerUnavailable = provider !== "auto" && (!capabilities?.externalProcessingAllowed || !capabilities.providerOptions.some(option => option.provider === provider));
  const canGenerate = capabilities?.enabled && capabilities.canWrite && !providerUnavailable && !missingSourceIds.length;

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    void getAiEstimateCapabilities().then((result) => { if (!cancelled) { if (result.ok) setCapabilities(result.data); else setCapabilityError(true); } }).catch(() => { if (!cancelled) setCapabilityError(true); });
    return () => { cancelled = true; };
  }, [open, refreshKey]);
  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    void getAiEstimateRecommendations(clientId, taxMode).then((result) => { if (!cancelled) setRecommendations({ key: recommendationKey, items: result.ok ? result.data : [], error: result.ok ? undefined : aiEstimateErrorMessage(result.error, lang, ui.error) }); }).catch(() => { if (!cancelled) setRecommendations({ key: recommendationKey, items: [], error: ui.error }); });
    return () => { cancelled = true; };
  }, [clientId, taxMode, recommendationKey, ui.error, lang, open, refreshKey]);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    void getAiEstimateReferenceOptions(clientId).then(result => { if (!cancelled) { if (result.ok) { setReferenceOptions({ clientId, items: result.data }); setReferenceError(false); } else setReferenceError(true); } }).catch(() => { if (!cancelled) setReferenceError(true); });
    return () => { cancelled = true; };
  }, [open, refreshKey, clientId]);

  function generate() {
    if (!canGenerate || pending) return;
    setError(null); setApplyMessage(null);
    startTransition(async () => {
      try {
        const result = await generateAiEstimateDraft({ clientId, clientName, subject, taxMode, locale: lang, requestId: crypto.randomUUID(), workDescription: description, sourceIds, requirements, assumptions, exclusions, provider, useWebMarketResearch: Boolean(webAvailable && useWebMarketResearch), publicSearchQuery, marketCountryCode, marketCurrency });
        if (!result.ok) { setError({ context, message: aiEstimateErrorMessage(result.error, lang, ui.error) }); return; }
        setSuggestion({ id: result.data.suggestionId, context, draft: result.data.draft, marketResearch: result.data.marketResearch, mode: result.data.generationMode, provider: result.data.provider, model: result.data.model });
        setOptions({ lineIndexes: result.data.draft.lines.flatMap((line, i) => line.priceEvidence === "insufficient" || line.taxCategory === "follow_company" ? [] : [i]), mode: "append", subject: false, templateMessage: false, remarks: false });
      } catch { setError({ context, message: ui.error }); }
    });
  }
  function apply() {
    if (!visibleSuggestion || applying.current || pending || !canGenerate) return;
    if ((options.lineIndexes.length && options.mode === "replace" && existingLineCount > 0) ? !window.confirm(ui.replaceConfirm) : (options.subject || options.templateMessage || options.remarks) && !window.confirm(ui.textConfirm)) return;
    applying.current = true;
    setError(null);
    startTransition(async () => {
      try {
        const recorded = await validateAiEstimateSuggestion(visibleSuggestion.id);
        if (!recorded.ok) { setError({ context, message: aiEstimateErrorMessage(recorded.error, lang, ui.error) }); return; }
        if (activeContext.current !== context) { setError({ context: activeContext.current, message: ui.stale }); return; }
        const result = applyDraft.current(visibleSuggestion.draft, options, visibleSuggestion.id);
        if (!result.ok) { setError({ context, message: result.error === "row_limit" ? ui.limit : result.error === "invalid_tax" ? ui.invalidTax : result.error === "suggestion_limit" ? refUi.suggestionLimit : result.error === "form_busy" ? ui.loading : ui.select }); return; }
        setAppliedId(visibleSuggestion.id); setApplyMessage(ui.applied);
        try {
          const marked = await markAiEstimateSuggestionApplied(visibleSuggestion.id);
          if (!marked.ok) setApplyMessage(`${ui.applied} ${ui.recordFailed}`);
        } catch { setApplyMessage(`${ui.applied} ${ui.recordFailed}`); }
      } catch { setError({ context, message: ui.error }); }
      finally { applying.current = false; }
    });
  }
  const currentRecommendations = recommendations?.key === recommendationKey ? recommendations : null;
  const selectableIndexes = visibleSuggestion?.draft.lines.flatMap((line, index) => line.taxCategory === "follow_company" ? [] : [index]) ?? [];
  const selectedCount = options.lineIndexes.length;
  const rowLimit = selectedCount > 0 && selectedCount + (options.mode === "append" ? existingLineCount : 0) > 80;
  const hasSelection = selectedCount > 0 || options.subject || options.templateMessage || options.remarks;

  return <section className="mt-8 min-w-0 max-w-full overflow-hidden rounded-2xl [overflow-wrap:anywhere] border border-violet-200 bg-violet-50/50">
    <div className="flex items-center justify-between gap-3 px-4 py-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><WandSparkles className="h-6 w-6 shrink-0 text-violet-600" /><div className="min-w-0"><h2 className="font-bold text-slate-900">{ui.title}</h2><p className="mt-1 text-sm text-slate-600">{ui.desc}</p></div></div><button type="button" onClick={() => setOpen(!open)} className="shrink-0 rounded-lg p-3 text-slate-600 hover:bg-white" aria-expanded={open} aria-label={`${ui.title}: ${open ? ui.hide : ui.show}`}>{open ? <ChevronUp className="h-5 w-5" /> : <ChevronDown className="h-5 w-5" />}</button></div>
    {open && <div className="border-t border-violet-100 p-4 sm:p-6">
      <div className="mb-4 flex min-w-0 flex-wrap items-center justify-between gap-3"><span className="min-w-0 max-w-full rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-700">{capabilities ? usesModel ? `${ui.model} · ${capabilities.modelGenerationModel ?? ""}` : ui.local : ui.loading}</span><div className="flex flex-wrap gap-4"><Link href={`/${lang}/estimates/ai-library`} className="inline-flex items-center gap-1 text-sm font-semibold text-violet-700"><BookOpen className="h-4 w-4 shrink-0" />{ui.library}</Link><Link href={`/${lang}/settings/ai-estimates`} className="text-sm text-violet-700">{ui.settings}</Link></div></div>
      {capabilityError && <p role="alert" className="mb-4 text-sm text-red-700">{ui.error}<button type="button" onClick={() => { setCapabilityError(false); setRefreshKey((value) => value + 1); }} className="ml-3 underline">{ui.retry}</button></p>}
      {capabilities && (!capabilities.enabled || !capabilities.canWrite) && <p role="status" className="mb-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{!capabilities.enabled ? ui.disabled : ui.readOnly}</p>}
      <section className="mb-6 min-w-0 rounded-xl border border-violet-200 bg-white p-4">
        <div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-sm font-bold">{refUi.title} ({sourceIds.length}/10)</h3>{sourceIds.length > 0 && <button type="button" disabled={pending} onClick={() => setSourceIds([])} className="min-h-11 text-sm text-violet-700 underline">{refUi.clear}</button>}</div>
        <p className="mt-2 text-xs leading-5 text-slate-600">{sourceIds.length ? refUi.selected : refUi.auto}</p>
        <label className="mt-3 block"><span className="sr-only">{refUi.search}</span><input type="search" className="field" value={referenceQuery} onChange={event => setReferenceQuery(event.target.value)} placeholder={refUi.search} /></label>
        {referenceError ? <p role="alert" className="mt-3 text-sm text-red-700">{ui.error}<button type="button" onClick={() => setRefreshKey(key => key + 1)} className="ml-3 underline">{ui.retry}</button></p> : !currentReferences ? <p className="mt-3 text-sm text-slate-500">{ui.loading}</p> : !currentReferences.length ? <p className="mt-3 text-sm text-slate-500">{refUi.empty}</p> : <div className="mt-3 grid max-h-72 gap-2 overflow-y-auto overscroll-contain sm:grid-cols-2">{currentReferences.filter(item => `${item.title} ${item.projectName} ${item.revision}`.toLowerCase().includes(referenceQuery.toLowerCase())).map(item => <label key={item.id} className={`flex min-w-0 items-start gap-3 rounded-lg border p-3 text-sm ${sourceIds.includes(item.id) ? "border-violet-400 bg-violet-50" : "border-slate-200"}`}><input type="checkbox" className="mt-1 shrink-0" checked={sourceIds.includes(item.id)} disabled={pending || (!sourceIds.includes(item.id) && sourceIds.length >= 10)} onChange={event => setSourceIds(ids => event.target.checked ? [...ids, item.id] : ids.filter(id => id !== item.id))} /><span className="min-w-0"><span className="block font-semibold">{item.title}</span><span className="mt-1 block text-xs text-slate-600">{[sourceKindLabel(item.documentKind, lang), item.projectName, item.revision].filter(Boolean).join(" · ")}</span>{(item.validFrom || item.validUntil) && <span className="mt-1 block text-xs text-slate-500">{item.validFrom ?? "…"} – {item.validUntil ?? "…"}</span>}</span></label>)}</div>}
        {missingSourceIds.map(id => <p key={id} role="alert" className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{refUi.missing}<button type="button" disabled={pending} onClick={() => setSourceIds(ids => ids.filter(value => value !== id))} className="ml-3 underline">{refUi.clear}</button></p>)}
      </section>
      <div className="grid min-w-0 gap-6 xl:grid-cols-2"><div className="min-w-0"><label className="block"><span className="mb-2 block text-sm font-semibold">{ui.work}</span><textarea maxLength={2000} disabled={!canGenerate || pending} className="field min-h-28 bg-white" value={description} onChange={(e) => setDescription(e.target.value)} placeholder={ui.placeholder} /><span className="mt-2 block text-xs leading-5 text-slate-600">{usesModel ? ui.aiNotice : ui.localNotice}</span></label>
        <div className="mt-4 space-y-4">{([ ["requirements", refUi.requirements, requirements, setRequirements, 8000], ["assumptions", refUi.assumptions, assumptions, setAssumptions, 4000], ["exclusions", refUi.exclusions, exclusions, setExclusions, 4000] ] as const).map(([key, label, value, setValue, limit]) => <label key={key} className="block min-w-0"><span className="mb-1 block text-sm font-semibold">{label}</span><textarea className="field min-h-24 bg-white" maxLength={limit} disabled={pending || !capabilities?.canWrite} value={value} onChange={event => setValue(event.target.value)} /></label>)}
          <label className="block"><span className="mb-1 block text-sm font-semibold">{refUi.provider}</span><select className="field bg-white" disabled={pending || !capabilities?.canWrite} value={provider} onChange={event => setProvider(event.target.value as typeof provider)}><option value="auto">{refUi.automatic}{!usesModel ? ` · ${ui.local}` : ""}</option>{(["gemini", "anthropic"] as const).map(name => { const option = capabilities?.providerOptions.find(item => item.provider === name); return <option key={name} value={name} disabled={!capabilities?.externalProcessingAllowed || !option}>{name === "gemini" ? "Gemini" : "Claude"}{option ? ` · ${option.model}` : ""}</option>; })}</select>{!capabilities?.externalProcessingAllowed && <span className="mt-2 block text-xs text-slate-600">{ui.localNotice}</span>}</label>
        </div>
        <div className="mt-4 rounded-xl border border-sky-200 bg-sky-50 p-3"><label className="flex items-start gap-2 text-sm font-semibold"><input type="checkbox" className="mt-1 shrink-0" checked={useWebMarketResearch} disabled={!webAvailable || !canGenerate || pending} onChange={(e) => setUseWebMarketResearch(e.target.checked)} />{ui.web}</label>{!webAvailable && <p className="mt-1 text-xs text-slate-600">{ui.webDisabled}</p>}{useWebMarketResearch && <div className="mt-3 space-y-3"><label className="block text-xs font-semibold">{ui.webQuery}<input maxLength={300} disabled={pending} className="field mt-1 bg-white" value={publicSearchQuery} onChange={(e) => setPublicSearchQuery(e.target.value)} /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">{ui.country}<select disabled={pending} className="field mt-1 bg-white" value={marketCountryCode} onChange={(e) => setMarketCountryCode(e.target.value as typeof marketCountryCode)}><option value="JP">JP</option><option value="KR">KR</option><option value="US">US</option><option value="GLOBAL">Global</option></select></label><label className="text-xs">{ui.currency}<select disabled={pending} className="field mt-1 bg-white" value={marketCurrency} onChange={(e) => setMarketCurrency(e.target.value as typeof marketCurrency)}><option>JPY</option><option>KRW</option><option>USD</option></select></label></div><p className="text-xs leading-5 text-sky-900">{ui.webNotice}</p></div>}</div>
        <button type="button" disabled={!canGenerate || pending || (!description.trim() && !requirements.trim() && !sourceIds.length && !subject.trim() && !(useWebMarketResearch && publicSearchQuery.trim().length >= 3)) || (useWebMarketResearch && publicSearchQuery.trim().length < 3)} onClick={generate} className="mt-4 inline-flex w-full max-w-full items-center justify-center gap-2 rounded-lg bg-violet-600 sm:w-auto px-4 py-3 text-sm font-semibold text-white disabled:opacity-40"><Sparkles className="h-4 w-4 shrink-0" />{pending ? ui.loading : ui.create}</button>
      </div><div className="min-w-0"><h3 className="text-sm font-bold">{ui.instant}</h3>{sourceIds.length ? <p className="mt-3 text-sm text-slate-600">{refUi.sourcePrices}</p> : !currentRecommendations ? <p className="mt-3 text-sm text-slate-500">{ui.loading}</p> : currentRecommendations.error ? <p role="alert" className="mt-3 text-sm text-red-700">{currentRecommendations.error}<button type="button" onClick={() => { setRecommendations(null); setRefreshKey((value)=>value+1); }} className="ml-3 underline">{ui.retry}</button></p> : currentRecommendations.items.length ? <div className="mt-3 space-y-2">{currentRecommendations.items.slice(0,4).map((item) => <div key={`${item.name}:${item.unit ?? ""}:${item.taxCategory ?? ""}`} className="rounded-lg bg-white p-3"><p className="break-words font-semibold text-slate-800">{item.name}</p><p className="mt-1 text-sm font-bold text-violet-700">¥{item.medianPrice.toLocaleString(lang)}{item.unit ? ` / ${item.unit}` : ""}<span className="ml-2 text-xs font-normal text-slate-600">{taxMode === "included" ? ui.taxIncluded : ui.taxExcluded} · {aiTaxCategoryLabel(item.taxCategory, lang)}</span></p><p className="mt-1 text-xs text-slate-600">¥{item.p25Price.toLocaleString(lang)}–¥{item.p75Price.toLocaleString(lang)} · {item.sampleCount} {ui.samples}</p>{item.sampleCount < (capabilities?.minimumPriceSamples ?? 3) && <p className="mt-1 text-xs text-amber-800">{ui.insufficient}</p>}</div>)}</div> : <p className="mt-3 text-sm leading-6 text-slate-600">{ui.empty}</p>}</div></div>
      {error?.context === context && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error.message}</p>}
      {applyMessage && <p role="status" className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{applyMessage}</p>}
      {suggestion && !visibleSuggestion && suggestion.id !== appliedId && <p role="status" className="mt-4 text-sm text-amber-800">{ui.stale}</p>}
      {visibleSuggestion && <div className="mt-6 rounded-xl border border-violet-200 bg-white p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="break-words font-bold text-slate-900">{ui.result}: {visibleSuggestion.draft.subject}</h3><span className="text-xs text-slate-600">{visibleSuggestion.mode === "model" ? `${visibleSuggestion.provider === "gemini" ? "Gemini" : visibleSuggestion.provider === "anthropic" ? "Claude" : ui.model} · ${visibleSuggestion.model}` : ui.local}</span></div>
        <label className="mt-4 flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={selectableIndexes.length > 0 && selectedCount === selectableIndexes.length} disabled={pending} onChange={(e) => setOptions({ ...options, lineIndexes: e.target.checked ? selectableIndexes : [] })} />{ui.all}</label>
        <div className="mt-3 space-y-3">{visibleSuggestion.draft.lines.map((line,index) => <div key={index} className="rounded-lg border border-slate-200 p-3"><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 shrink-0" aria-label={`${ui.selectItem}: ${line.name}`} disabled={pending || line.taxCategory === "follow_company"} checked={options.lineIndexes.includes(index)} onChange={(e) => setOptions({ ...options, lineIndexes: e.target.checked ? [...options.lineIndexes,index] : options.lineIndexes.filter((i)=>i!==index) })} /><span className="min-w-0 flex-1"><span className="block break-words font-semibold">{line.name}</span><span className="mt-1 flex flex-wrap gap-x-1 gap-y-0.5 text-sm text-slate-700"><span className="min-w-0 max-w-full break-words">{line.qty} {line.unit}</span><span className="inline-flex max-w-full flex-wrap gap-x-1"><span className="whitespace-nowrap">· {ui.unit}</span><span className="whitespace-nowrap">¥{line.unitPrice.toLocaleString(lang)}</span></span><span className="whitespace-nowrap">· {taxMode === "included" ? ui.taxIncluded : ui.taxExcluded}</span><span className="whitespace-nowrap">· {aiTaxCategoryLabel(line.taxCategory, lang)}</span></span></span></label><div className="mt-2 text-xs leading-5 sm:pl-7">{line.taxCategory === "follow_company" && <p className="font-semibold text-amber-800">{ui.invalidTax}</p>}<p className={line.priceEvidence === "insufficient" ? "font-semibold text-amber-800" : "text-slate-600"}>{line.priceEvidence === "insufficient" ? ui.insufficient : line.priceEvidence === "price_list" ? refUi.priceList : line.priceEvidence === "statistical" ? ui.statistical : ui.historical}</p>{line.priceRange && <p className="text-slate-600">{ui.range}: ¥{line.priceRange.low.toLocaleString(lang)}–¥{line.priceRange.high.toLocaleString(lang)} / {line.priceRange.unit} · {line.priceRange.sampleCount} {ui.samples}</p>}<p className="break-words text-slate-500">{line.reason}</p>{line.quantityReason && <p className="mt-1 break-words text-slate-600"><span className="font-semibold">{sourceUi.quantityReason}: </span>{line.quantityReason}</p>}</div></div>)}</div>
        {!!visibleSuggestion.draft.warnings.length && <div className="mt-3 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-900">{visibleSuggestion.draft.warnings.map((warning,i)=><p key={i}>• {warning}</p>)}</div>}
        <section className="mt-4"><h4 className="text-sm font-semibold">{sourceUi.priceEvidence}</h4>{visibleSuggestion.draft.evidence.length ? visibleSuggestion.draft.evidence.map((item)=><p key={item.exampleId} className="mt-2 text-sm">{item.sourceId ? <Link href={`/${lang}/estimates/ai-library/${item.sourceId}`} target="_blank" className="inline-flex max-w-full items-start gap-1 text-violet-700 underline"><span className="min-w-0">{item.label}{item.documentKind ? ` · ${sourceKindLabel(item.documentKind, lang)}` : ""}</span><ExternalLink className="mt-1 h-3 w-3 shrink-0" /></Link> : item.label}</p>) : <p className="mt-2 text-xs text-amber-800">{ui.noEvidence}</p>}</section>
        <section className="mt-4"><h4 className="text-sm font-semibold">{sourceUi.contextEvidence}</h4>{visibleSuggestion.draft.contextEvidence?.length ? visibleSuggestion.draft.contextEvidence.map(item => <p key={item.exampleId} className="mt-2 text-sm"><span className="min-w-0">{item.sourceId ? <Link href={`/${lang}/estimates/ai-library/${item.sourceId}`} target="_blank" className="inline-flex max-w-full items-start gap-1 text-violet-700 underline"><span className="min-w-0">{item.label} · {sourceKindLabel(item.documentKind, lang)}</span><ExternalLink className="mt-1 h-3 w-3 shrink-0" /></Link> : item.label}</span></p>) : <p className="mt-2 text-xs text-slate-500">{refUi.noneContext}</p>}</section>
        {visibleSuggestion.marketResearch && <section className="mt-4 rounded-lg bg-sky-50 p-3 text-sm"><h4 className="font-semibold text-sky-950">{ui.market}</h4><p className="mt-2 text-sky-900">{visibleSuggestion.marketResearch.summary}</p>{visibleSuggestion.marketResearch.items.map((item,i)=><p key={i} className="mt-2 text-xs">{item.name} · {item.lowPrice.toLocaleString(lang)}–{item.highPrice.toLocaleString(lang)} {visibleSuggestion.marketResearch?.currency} / {item.unit}<span className="block text-slate-600">{item.basis}</span></p>)}{visibleSuggestion.marketResearch.sources.map((source)=><a key={source.url} href={source.url} target="_blank" rel="noopener noreferrer" className="mt-2 block break-words text-xs text-sky-800 underline">{source.title}</a>)}{visibleSuggestion.marketResearch.caveats.map((caveat,i)=><p key={i} className="mt-2 text-xs text-sky-900">• {caveat}</p>)}</section>}
        <fieldset className="mt-5 space-y-2 rounded-lg bg-slate-50 p-3" disabled={pending}><legend className="px-1 text-sm font-semibold">{ui.count}: {existingLineCount} / 80</legend><label className="flex items-center gap-2 text-sm"><input type="radio" name="ai-apply-mode" checked={options.mode === "append"} onChange={()=>setOptions({...options,mode:"append"})} />{ui.append}</label><label className="flex items-center gap-2 text-sm"><input type="radio" name="ai-apply-mode" checked={options.mode === "replace"} onChange={()=>setOptions({...options,mode:"replace"})} />{ui.replace}</label></fieldset>
        <fieldset className="mt-4 space-y-3" disabled={pending}><legend className="mb-2 text-sm font-semibold">{ui.fields}</legend>{([ ["subject",ui.subject], ["templateMessage",ui.message], ["remarks",ui.remarks] ] as const).map(([field,label])=><label key={field} className="block rounded-lg border border-slate-200 p-3"><span className="flex items-center gap-2 text-sm"><input type="checkbox" checked={options[field]} disabled={!visibleSuggestion.draft[field]} onChange={(e)=>setOptions({...options,[field]:e.target.checked})} />{label}</span><span className="mt-2 block whitespace-pre-wrap break-words text-xs text-slate-600">{visibleSuggestion.draft[field] || "—"}</span></label>)}</fieldset>
        {rowLimit && <p role="alert" className="mt-3 text-sm text-red-700">{ui.limit}</p>}<button type="button" onClick={apply} disabled={pending || !canGenerate || rowLimit || !hasSelection} className="mt-5 w-full rounded-lg bg-[#0A4D34] px-5 py-3 text-sm font-semibold text-white disabled:opacity-40 sm:w-auto">{ui.apply} ({selectedCount})</button>
      </div>}
    </div>}
  </section>;
}
