import type { AppLocale } from "@/contexts/language-context";

const labels = {
  ja: {
    tabs: ["品目管理", "一括登録"],
    title: "品目管理",
    intro:
      "よく使う品目を登録しておくことで、品番・品名を正確・簡単に入力できる機能です。",
    learnMore: "さらに詳しく",
    createItem: "品目の新規登録",
    searchPlaceholder: "品番・品名",
    search: "検索",
    csvDownload: "CSVダウンロード",
    empty: "品目はありません",
    newItem: {
      title: "品目の新規登録",
      backToList: "品目管理へ戻る",
      itemName: "品番・品名",
      itemNameHint: "255文字以内で入力してください。",
      unit: "単位",
      unitHint: "255文字以内で入力してください。",
      unitPrice: "単価",
      unitPriceHint: "15桁以内の数値で入力してください。",
      yen: "円",
      taxRateSetting: "消費税率設定",
      taxFollowCompany: "自社情報の設定に従う",
      taxFollowCompanyHelp: "自社情報で設定した消費税率を使用します。",
      tax10: "10%",
      taxReduced8: "軽減8%",
      tax8: "8%",
      taxExempt: "対象外",
      tax5: "5%",
      withholdingTax: "源泉税",
      withholdingExempt: "対象外",
      save: "保存する",
      required: "必須",
    },
    bulk: {
      title: "品目の一括登録(CSVアップロード)",
      intro: "CSVファイルをアップロードすることで、複数の品目を一括で登録できます。",
      uploadSection: "CSVファイルのアップロード",
      chooseFile: "ファイルを選択",
      noFile: "選択されたファイルはありません",
      upload: "アップロードする",
      uploadNotes: [
        "Excelで作成したCSV形式、またはCSV形式で保存したファイルをアップロードしてください。",
        "1行目はヘッダー行としてください。",
        "1回のアップロードで登録できる品目数は100件までです。",
      ],
      templateSection: "記入用テンプレートのダウンロード",
      templateUtf8: "UTF-8版",
      templateUtf8Button: "UTF-8版 記入用テンプレート",
      templateShiftJis: "Shift-JIS版\n(Excelを使用される方はこちら)",
      templateShiftJisButton: "Shift-JIS版 記入用テンプレート",
      formatSection: "記入用テンプレートの形式",
      formatRows: [
        ["形式", "CSV形式"],
        ["文字エンコーディング", "UTF-8 または Shift-JIS"],
      ] as const,
      formatNote: "保存する際は、上記の形式で保存してください。",
      fieldsSection: "記入用テンプレートの項目説明",
      fieldsIntro: "記入用テンプレートの各項目は次のようになっています。",
      fieldHeaders: ["項目", "必須", "制限", "説明"],
      fields: [
        {
          name: "品番・品名",
          required: "○",
          limit: "255文字",
          desc: "品目の番号・名前です。",
        },
        {
          name: "単位",
          required: "",
          limit: "255文字",
          desc: "品目の単位です。",
        },
        {
          name: "単価",
          required: "",
          limit: "数値",
          desc: "品目の単価です。¥などの通貨記号は記入しないでください。",
        },
        {
          name: "消費税率",
          required: "",
          limit: "5, 8, 10, R8",
          desc: "品目の消費税率です。",
        },
        {
          name: "非課税フラグ",
          required: "",
          limit: "1 または 0",
          desc: "非課税の場合は 1、課税の場合は 0 を入力してください。",
        },
        {
          name: "源泉徴収税対象外フラグ",
          required: "",
          limit: "1 または 0",
          desc: "源泉徴収税の対象外の場合は 1、対象の場合は 0 を入力してください。",
        },
      ],
    },
  },
  ko: {
    tabs: ["품목 관리", "일괄 등록"],
    title: "품목 관리",
    intro: "자주 쓰는 품목을 등록해 두면 품번·품명을 정확하고 쉽게 입력할 수 있습니다.",
    learnMore: "자세히 보기",
    createItem: "품목 신규 등록",
    searchPlaceholder: "품번·품명",
    search: "검색",
    csvDownload: "CSV 다운로드",
    empty: "품목이 없습니다",
    newItem: {
      title: "품목 신규 등록",
      backToList: "품목 관리로 돌아가기",
      itemName: "품번·품명",
      itemNameHint: "255자 이내로 입력해 주세요.",
      unit: "단위",
      unitHint: "255자 이내로 입력해 주세요.",
      unitPrice: "단가",
      unitPriceHint: "15자리 이내의 숫자로 입력해 주세요.",
      yen: "엔",
      taxRateSetting: "소비세율 설정",
      taxFollowCompany: "자사 정보 설정 따름",
      taxFollowCompanyHelp: "자사 정보에 설정한 소비세율을 사용합니다.",
      tax10: "10%",
      taxReduced8: "경감 8%",
      tax8: "8%",
      taxExempt: "대상 외",
      tax5: "5%",
      withholdingTax: "원천세",
      withholdingExempt: "대상 외",
      save: "저장",
      required: "필수",
    },
    bulk: {
      title: "품목 일괄 등록(CSV 업로드)",
      intro: "CSV 파일을 업로드하여 여러 품목을 한 번에 등록할 수 있습니다.",
      uploadSection: "CSV 파일 업로드",
      chooseFile: "파일 선택",
      noFile: "선택된 파일 없음",
      upload: "업로드",
      uploadNotes: [
        "Excel로 작성한 CSV 형식 또는 CSV 형식으로 저장한 파일을 업로드해 주세요.",
        "첫 번째 행은 헤더 행이어야 합니다.",
        "한 번에 등록할 수 있는 품목 수는 최대 100건입니다.",
      ],
      templateSection: "입력용 템플릿 다운로드",
      templateUtf8: "UTF-8版",
      templateUtf8Button: "UTF-8版 입력용 템플릿",
      templateShiftJis: "Shift-JIS版\n(Excel 사용자는 여기)",
      templateShiftJisButton: "Shift-JIS版 입력용 템플릿",
      formatSection: "입력용 템플릿 형식",
      formatRows: [
        ["형식", "CSV 형식"],
        ["문자 인코딩", "UTF-8 또는 Shift-JIS"],
      ] as const,
      formatNote: "저장 시 위 형식으로 저장해 주세요.",
      fieldsSection: "입력용 템플릿 항목 설명",
      fieldsIntro: "입력용 템플릿의 각 항목은 다음과 같습니다.",
      fieldHeaders: ["항목", "필수", "제한", "설명"],
      fields: [
        {
          name: "품번·품명",
          required: "○",
          limit: "255자",
          desc: "품목의 번호·이름입니다.",
        },
        {
          name: "단위",
          required: "",
          limit: "255자",
          desc: "품목의 단위입니다.",
        },
        {
          name: "단가",
          required: "",
          limit: "숫자",
          desc: "품목의 단가입니다. ¥ 등의 통화 기호는 입력하지 마세요.",
        },
        {
          name: "소비세율",
          required: "",
          limit: "5, 8, 10, R8",
          desc: "품목의 소비세율입니다.",
        },
        {
          name: "비과세 플래그",
          required: "",
          limit: "1 또는 0",
          desc: "비과세인 경우 1, 과세인 경우 0을 입력하세요.",
        },
        {
          name: "원천징수세 대상 외 플래그",
          required: "",
          limit: "1 또는 0",
          desc: "원천징수세 대상 외인 경우 1, 대상인 경우 0을 입력하세요.",
        },
      ],
    },
  },
  en: {
    tabs: ["Item Management", "Bulk Registration"],
    title: "Item Management",
    intro: "Register frequently used items to enter item numbers and names accurately and easily.",
    learnMore: "Learn more",
    createItem: "Register New Item",
    searchPlaceholder: "Item No. / Name",
    search: "Search",
    csvDownload: "CSV Download",
    empty: "No items",
    newItem: {
      title: "Register New Item",
      backToList: "Back to Item Management",
      itemName: "Item No. / Name",
      itemNameHint: "Enter up to 255 characters.",
      unit: "Unit",
      unitHint: "Enter up to 255 characters.",
      unitPrice: "Unit Price",
      unitPriceHint: "Enter a numeric value up to 15 digits.",
      yen: "JPY",
      taxRateSetting: "Consumption Tax Rate",
      taxFollowCompany: "Follow company settings",
      taxFollowCompanyHelp: "Uses the tax rate configured in company settings.",
      tax10: "10%",
      taxReduced8: "Reduced 8%",
      tax8: "8%",
      taxExempt: "Not applicable",
      tax5: "5%",
      withholdingTax: "Withholding Tax",
      withholdingExempt: "Not applicable",
      save: "Save",
      required: "Required",
    },
    bulk: {
      title: "Bulk Item Registration (CSV Upload)",
      intro: "Upload a CSV file to register multiple items at once.",
      uploadSection: "CSV File Upload",
      chooseFile: "Choose File",
      noFile: "No file selected",
      upload: "Upload",
      uploadNotes: [
        "Upload a file saved in CSV format, including files exported from Excel.",
        "The first row must be a header row.",
        "You can register up to 100 items per upload.",
      ],
      templateSection: "Download Entry Template",
      templateUtf8: "UTF-8",
      templateUtf8Button: "UTF-8 Entry Template",
      templateShiftJis: "Shift-JIS\n(For Excel users)",
      templateShiftJisButton: "Shift-JIS Entry Template",
      formatSection: "Entry Template Format",
      formatRows: [
        ["Format", "CSV"],
        ["Character encoding", "UTF-8 or Shift-JIS"],
      ] as const,
      formatNote: "Please save files in the format above.",
      fieldsSection: "Entry Template Field Descriptions",
      fieldsIntro: "The entry template fields are as follows.",
      fieldHeaders: ["Field", "Required", "Limit", "Description"],
      fields: [
        {
          name: "Item No. / Name",
          required: "○",
          limit: "255 chars",
          desc: "The item number and name.",
        },
        {
          name: "Unit",
          required: "",
          limit: "255 chars",
          desc: "The unit of the item.",
        },
        {
          name: "Unit Price",
          required: "",
          limit: "Numeric",
          desc: "The unit price. Do not include currency symbols such as ¥.",
        },
        {
          name: "Tax Rate",
          required: "",
          limit: "5, 8, 10, R8",
          desc: "The consumption tax rate for the item.",
        },
        {
          name: "Tax-exempt Flag",
          required: "",
          limit: "1 or 0",
          desc: "Enter 1 if tax-exempt, 0 if taxable.",
        },
        {
          name: "Withholding Tax Exemption Flag",
          required: "",
          limit: "1 or 0",
          desc: "Enter 1 if exempt from withholding tax, 0 if subject to withholding tax.",
        },
      ],
    },
  },
} as const;

export function getItemsContent(lang: AppLocale) {
  return labels[lang];
}

export function getItemsHref(_lang: AppLocale, page: "list" | "new" | "bulk" = "list") {
  const base = "/items";
  if (page === "new") return `${base}/new`;
  if (page === "bulk") return `${base}/bulk`;
  return base;
}
