export type EstimateLocale = "ja" | "ko" | "en";

const labels = {
  ja: {
    listTitle: "見積書",
    createEstimate: "見積書を新しく作る",
    searchPlaceholder: "取引先名, 見積書番号, 件名, 社内メモ",
    searchDetail: "詳細検索",
    searchButton: "検索",
    tabs: ["未処理", "処理済", "ごみ箱"],
    empty: "見積書はありません",
    newTitle: "見積書の新規作成",
    newTabs: ["基本情報", "送付先", "課税設定", "テンプレート"],
    estimateInfo: "見積情報",
    recipientInfo: "見積元情報",
    detailLink: "詳細（住所, 連絡先など）",
    required: "必須",
    requiredLine: "1行目必須",
    client: "取引先",
    issueDate: "発行日",
    expiryDate: "有効期限",
    noDate: "指定なし",
    estimateNumber: "見積書番号",
    estimateHint: "見積書番号を事前にお好みの形式で設定できます。",
    subject: "件名",
    itemHeaders: ["品番・品名", "数量", "単位", "単価", "税区分", "金額"],
    batchTax: "税区分を一括で",
    change: "変更する",
    addRow: "+ 行の追加",
    printNote: "印刷時には最低10行になります。行の追加は最大80行までです。",
    subtotal: "小計",
    tax: "消費税",
    total: "合計",
    remarks: "備考",
    save: "保存する",
    detailTitle: "見積書の詳細",
    successClient: "取引先一覧に 11111 様 を新規追加しました",
    successEstimate: "見積書を作成しました。",
    previewTab: "プレビュー",
    historyTab: "履歴",
    issueAction: "発行",
    editAction: "編集",
    moreAction: "その他",
    internalMemo: "社内メモ",
    memoPlaceholder: "（見積書には記載されません。）",
    saveMini: "保存",
    estimateAmount: "見積金額",
    status: "ステータス",
    statusDraft: "未発行",
    statusPending: "未受注",
    companyName: "自社名",
    companyHonorific: "様",
    previewLead: "下記のとおりお見積申し上げます。",
    unit: "単位",
    issueDateValue: "2026/05/22",
    issueDateJapanese: "2026年05月22日",
    estimateNumberValue: "20260522-001",
    companyValue: "Raon",
    clientValue: "11111",
    phone: "TEL: 070-9116-9716",
    email: "bluebourne907@gmail.com",
    backToList: "見積書へ戻る",
    issueMenu: {
      email: "メール送信手続",
      emailRecommended: "オススメ",
      fax: "FAX送信",
      download: "PDFダウンロード",
      print: "印刷",
      share: "共有リンク（チャット/SNS）"
    },
    emailModal: {
      title: "取引先情報の更新",
      description: "メール送信をするにはメールアドレスの登録をしてください。",
      fieldLabel: "メールアドレス",
      submit: "登録して送信へ進む",
      success: "メールアドレスを登録しました。送信準備ができました。"
    },
    shareModal: {
      title: "共有リンク（チャット/SNS）",
      description: "見積書を共有・閲覧できるリンクを取得します。",
      caution: "※「リンクを取得」をクリックすると文書は確定し、以後の編集はできなくなります。",
      submit: "リンクを取得",
      copied: "共有リンクをコピーしました。"
    },
    actions: {
      copied: "コピーしました。",
      downloaded: "PDFをダウンロードしました。",
      printing: "印刷ダイアログを開きました。"
    },
    faxPage: {
      title: "FAX送信手続き",
      faxNumber: "送信先FAX番号",
      tableHeaders: ["見積書", "送信先", "FAX送信料金（税抜）"],
      publishLabel: "発行日",
      expiryLabel: "有効期限",
      amountLabel: "金額",
      noExpiry: "-",
      amount: "0円",
      fee: "¥60",
      notesTitle: "FAX送信手続きのご注意",
      notes: [
        "FAX送信手続完了後はキャンセル（差し止め・返金）はできません。",
        "番号誤りなどによって不達になった場合も、送信費用は課金されます。",
        "FAXの送信先は日本国内に限られます。",
        "050で始まる番号（IP電話）への送信はできません。"
      ],
      warning: "プラン制限により有償のFAX送信機能をご利用いただけません。ご契約のプラン内容をご確認ください。"
    },
    // テンプレートタブ
    templateTitle: "カスタマイズオプション",
    templateNote: "テンプレートの内容を変更できます。初期値は文書初期設定で変更可能です。",
    templateSettingsLink: "設定画面へ",
    templateChangeButton: "テンプレートを変更",
    templateChangeTitle: "テンプレートの変更",
    templateMessageLabel: "メッセージ",
    templateMessagePlaceholder: "下記のとおりお見積申し上げます。",
    templateFieldsTitle: "明細項目の表示名",
    templateFieldItemName: "品番・品名",
    templateFieldItemNameLimit: "30文字以内で入力してください",
    templateFieldQty: "数量",
    templateFieldQtyLimit: "10文字以内で入力してください",
    templateFieldUnitPrice: "単価",
    templateFieldUnitPriceLimit: "10文字以内で入力してください",
    templateFieldAmount: "金額",
    templateFieldAmountLimit: "10文字以内で入力してください",
    templateStandard: "スタンダード",
    templateEnvelope: "忘付封筒対応",
    templateModalCancel: "キャンセル",
    templateModalSelect: "選択する",
    // 課税設定タブ
    taxSettings: "消費税設定",
    taxSeparate: "税別表示",
    taxSeparateOnInvoice: "税別表示（請求時に計算）",
    taxIncluded: "税込表示",
    taxExempt: "税込表示（免税）",
    taxRounding: "消費税端数処理",
    taxRoundingNote: "1円に満たない消費税の小数以下の処理方法を選択できます。",
    roundDown: "切り捨て",
    roundUp: "切り上げ",
    roundHalf: "四捨五入",
    documentRemarks: "文書初期設定の備考を使う",
    documentSettings: "文書初期設定",
    // 送付先タブ
    postalCode: "郵便番号",
    postalCodePlaceholder: "000-0000形式（半角）で入力してください",
    postalCodeLookup: "郵便番号から検索",
    address: "住所",
    recipientName: "名前",
    companyNamePlaceholder: "（例）合社名または個人名",
    departmentPlaceholder: "（例）部署名",
    namePlaceholder: "（例）氏名",
    contactPlaceholder: "（例）担当者名",
    // プレビューサンプルデータ
    sampleDate: "2013年06月09日",
    sampleDocNo: "見積書番号: 20130602-001",
    sampleClient: "サンプル株式会社 様",
    sampleSubject: "件名：サンプルプロジェクト",
    sampleExpiryDate: "有効期限：2013年06月30日",
    sampleMessage: "下記のとおりお見積申し上げます。",
    sampleAmountLabel: "お見積金額",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "ミソカインダイス株式会社",
    sampleAddress: "〒151-0064\n東京都渋谷区松涛 3-13\n鮫ビル1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "企画書作成", qty: "1企業", price: "50,000", amount: "50,000" },
      { name: "デザイン業務他", qty: "1案", price: "80,000", amount: "80,000" },
      { name: "交通費", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "いつもありがとうございます。",
  },
  ko: {
    listTitle: "견적서",
    createEstimate: "새 견적서 만들기",
    searchPlaceholder: "거래처명, 견적서 번호, 제목, 사내 메모",
    searchDetail: "상세 검색",
    searchButton: "검색",
    tabs: ["미처리", "처리 완료", "휴지통"],
    empty: "견적서가 없습니다",
    newTitle: "견적서 신규 작성",
    newTabs: ["기본 정보", "수신처", "과세 설정", "템플릿"],
    estimateInfo: "견적 정보",
    recipientInfo: "발신 정보",
    detailLink: "상세(주소, 연락처 등)",
    required: "필수",
    requiredLine: "1행 필수",
    client: "거래처",
    issueDate: "발행일",
    expiryDate: "유효기한",
    noDate: "지정 없음",
    estimateNumber: "견적서 번호",
    estimateHint: "견적서 번호 형식을 미리 원하는 방식으로 설정할 수 있습니다.",
    subject: "제목",
    itemHeaders: ["품번·품명", "수량", "단위", "단가", "세금 구분", "금액"],
    batchTax: "세금 구분 일괄",
    change: "변경하기",
    addRow: "+ 행 추가",
    printNote: "인쇄 시 최소 10행이 됩니다. 행 추가는 최대 80행까지 가능합니다.",
    subtotal: "소계",
    tax: "소비세",
    total: "합계",
    remarks: "비고",
    save: "저장하기",
    detailTitle: "견적서 상세",
    successClient: "거래처 목록에 11111 님을 새로 추가했습니다",
    successEstimate: "견적서를 작성했습니다.",
    previewTab: "미리보기",
    historyTab: "이력",
    issueAction: "발행",
    editAction: "편집",
    moreAction: "기타",
    internalMemo: "사내 메모",
    memoPlaceholder: "（견적서에는 표시되지 않습니다.）",
    saveMini: "저장",
    estimateAmount: "견적 금액",
    status: "상태",
    statusDraft: "미발행",
    statusPending: "미수주",
    companyName: "자사명",
    companyHonorific: "님",
    previewLead: "아래와 같이 견적드립니다.",
    unit: "단위",
    issueDateValue: "2026/05/22",
    issueDateJapanese: "2026년 05월 22일",
    estimateNumberValue: "20260522-001",
    companyValue: "Raon",
    clientValue: "11111",
    phone: "TEL: 070-9116-9716",
    email: "bluebourne907@gmail.com",
    backToList: "견적서로 돌아가기",
    issueMenu: {
      email: "메일 발송 절차",
      emailRecommended: "추천",
      fax: "FAX 발송",
      download: "PDF 다운로드",
      print: "인쇄",
      share: "공유 링크(채팅/SNS)"
    },
    emailModal: {
      title: "거래처 정보 업데이트",
      description: "메일을 보내려면 이메일 주소를 등록해 주세요.",
      fieldLabel: "이메일 주소",
      submit: "등록 후 발송으로 진행",
      success: "이메일 주소를 등록했습니다. 발송 준비가 완료되었습니다."
    },
    shareModal: {
      title: "공유 링크(채팅/SNS)",
      description: "견적서를 공유하고 열람할 수 있는 링크를 발급합니다.",
      caution: "※ 링크를 발급하면 문서가 확정되어 이후에는 편집할 수 없습니다.",
      submit: "링크 발급",
      copied: "공유 링크를 복사했습니다."
    },
    actions: {
      copied: "복사했습니다.",
      downloaded: "PDF를 다운로드했습니다.",
      printing: "인쇄 창을 열었습니다."
    },
    faxPage: {
      title: "FAX 발송 절차",
      faxNumber: "수신처 FAX 번호",
      tableHeaders: ["견적서", "수신처", "FAX 발송 요금(세전)"],
      publishLabel: "발행일",
      expiryLabel: "유효기한",
      amountLabel: "금액",
      noExpiry: "-",
      amount: "0원",
      fee: "¥60",
      notesTitle: "FAX 발송 절차 안내",
      notes: [
        "FAX 발송 완료 후에는 취소(중지·환불)할 수 없습니다.",
        "번호 오류 등으로 미도착한 경우에도 발송 비용이 과금됩니다.",
        "FAX 발송처는 일본 국내에 한합니다.",
        "050으로 시작하는 번호(IP 전화)로는 발송할 수 없습니다."
      ],
      warning: "플랜 제한으로 인해 유료 FAX 발송 기능을 이용할 수 없습니다. 계약 중인 플랜 내용을 확인해 주세요."
    },
    templateTitle: "커스터마이즈 옵션",
    templateNote: "템플릿 내용을 변경할 수 있습니다. 초기값은 문서 초기 설정에서 변경 가능합니다.",
    templateSettingsLink: "설정 화면으로",
    templateChangeButton: "템플릿 변경",
    templateChangeTitle: "템플릿 변경",
    templateMessageLabel: "메시지",
    templateMessagePlaceholder: "아래와 같이 견적드립니다.",
    templateFieldsTitle: "명세 항목의 표시명",
    templateFieldItemName: "품번·품명",
    templateFieldItemNameLimit: "30자 이내로 입력해 주세요",
    templateFieldQty: "수량",
    templateFieldQtyLimit: "10자 이내로 입력해 주세요",
    templateFieldUnitPrice: "단가",
    templateFieldUnitPriceLimit: "10자 이내로 입력해 주세요",
    templateFieldAmount: "금액",
    templateFieldAmountLimit: "10자 이내로 입력해 주세요",
    templateStandard: "스탠다드",
    templateEnvelope: "봉투 대응",
    templateModalCancel: "취소",
    templateModalSelect: "선택하기",
    taxSettings: "소비세 설정",
    taxSeparate: "세별 표시",
    taxSeparateOnInvoice: "세별 표시（청구 시 계산）",
    taxIncluded: "세포함 표시",
    taxExempt: "세포함 표시（면세）",
    taxRounding: "소비세 단수 처리",
    taxRoundingNote: "1원 미만의 소비세 소수점 이하 처리 방법을 선택할 수 있습니다.",
    roundDown: "버림",
    roundUp: "올림",
    roundHalf: "반올림",
    documentRemarks: "문서 초기 설정의 비고 사용",
    documentSettings: "문서 초기 설정",
    postalCode: "우편번호",
    postalCodePlaceholder: "000-0000 형식(반각)으로 입력해 주세요",
    postalCodeLookup: "우편번호로 검색",
    address: "주소",
    recipientName: "이름",
    companyNamePlaceholder: "（예）법인명 또는 개인명",
    departmentPlaceholder: "（예）부서명",
    namePlaceholder: "（예）성명",
    contactPlaceholder: "（예）담당자명",
    sampleDate: "2013년 06월 09일",
    sampleDocNo: "견적서 번호: 20130602-001",
    sampleClient: "샘플 주식회사 귀중",
    sampleSubject: "건명：샘플 프로젝트",
    sampleExpiryDate: "유효기한：2013년 06월 30일",
    sampleMessage: "아래와 같이 견적드립니다.",
    sampleAmountLabel: "견적 금액",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "미소카인다이스 주식회사",
    sampleAddress: "〒151-0064\n도쿄도 시부야구 마쓰자와 3-13\n사메 빌딩 1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "기획서 작성", qty: "1건", price: "50,000", amount: "50,000" },
      { name: "디자인 업무 외", qty: "1건", price: "80,000", amount: "80,000" },
      { name: "교통비", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "항상 감사합니다.",
  },
  en: {
    listTitle: "Estimates",
    createEstimate: "Create a new estimate",
    searchPlaceholder: "Client, estimate number, subject, internal memo",
    searchDetail: "Advanced search",
    searchButton: "Search",
    tabs: ["Open", "Processed", "Trash"],
    empty: "No estimates found",
    newTitle: "Create estimate",
    newTabs: ["Basic info", "Recipient", "Tax settings", "Template"],
    estimateInfo: "Estimate information",
    recipientInfo: "Issuer information",
    detailLink: "Details (address, contact, etc.)",
    required: "Required",
    requiredLine: "Line 1 required",
    client: "Client",
    issueDate: "Issue date",
    expiryDate: "Expiry date",
    noDate: "Not specified",
    estimateNumber: "Estimate number",
    estimateHint: "You can preset your preferred estimate number format.",
    subject: "Subject",
    itemHeaders: ["Item code / name", "Qty", "Unit", "Unit price", "Tax", "Amount"],
    batchTax: "Apply tax rate",
    change: "Change",
    addRow: "+ Add row",
    printNote: "At least 10 rows are printed. You can add up to 80 rows.",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    remarks: "Notes",
    save: "Save",
    detailTitle: "Estimate details",
    successClient: "Added 11111 to the client list",
    successEstimate: "Estimate created.",
    previewTab: "Preview",
    historyTab: "History",
    issueAction: "Issue",
    editAction: "Edit",
    moreAction: "More",
    internalMemo: "Internal memo",
    memoPlaceholder: "(This will not appear on the estimate.)",
    saveMini: "Save",
    estimateAmount: "Estimate amount",
    status: "Status",
    statusDraft: "Not issued",
    statusPending: "Not ordered",
    companyName: "Company name",
    companyHonorific: "",
    previewLead: "We are pleased to submit the following estimate.",
    unit: "Unit",
    issueDateValue: "2026/05/22",
    issueDateJapanese: "May 22, 2026",
    estimateNumberValue: "20260522-001",
    companyValue: "Raon",
    clientValue: "11111",
    phone: "TEL: 070-9116-9716",
    email: "bluebourne907@gmail.com",
    backToList: "Back to estimates",
    issueMenu: {
      email: "Email delivery",
      emailRecommended: "Recommended",
      fax: "FAX delivery",
      download: "Download PDF",
      print: "Print",
      share: "Share link (chat/SNS)"
    },
    emailModal: {
      title: "Update client information",
      description: "Please register an email address before sending by email.",
      fieldLabel: "Email address",
      submit: "Register and continue",
      success: "Email address saved. Ready to send."
    },
    shareModal: {
      title: "Share link (chat/SNS)",
      description: "Get a shareable link to view this estimate.",
      caution: "Once you get the link, this document is finalized and can no longer be edited.",
      submit: "Get link",
      copied: "Share link copied."
    },
    actions: {
      copied: "Copied.",
      downloaded: "PDF downloaded.",
      printing: "Opened the print dialog."
    },
    faxPage: {
      title: "FAX sending procedure",
      faxNumber: "Recipient FAX number",
      tableHeaders: ["Estimate", "Recipient", "FAX fee (tax excl.)"],
      publishLabel: "Issue date",
      expiryLabel: "Expiry date",
      amountLabel: "Amount",
      noExpiry: "-",
      amount: "¥0",
      fee: "¥60",
      notesTitle: "Important notes for FAX sending",
      notes: [
        "You cannot cancel or refund after completing the FAX sending procedure.",
        "Sending fees will still be charged if delivery fails due to an incorrect number.",
        "FAX can only be sent within Japan.",
        "Numbers beginning with 050 (IP phones) cannot be used."
      ],
      warning: "Your current plan does not include paid FAX sending. Please check your subscription plan."
    },
    templateTitle: "Customize options",
    templateNote: "You can change the template content. The default can be changed in Document defaults.",
    templateSettingsLink: "Go to settings",
    templateChangeButton: "Change template",
    templateChangeTitle: "Change template",
    templateMessageLabel: "Message",
    templateMessagePlaceholder: "We are pleased to submit the following estimate.",
    templateFieldsTitle: "Line item display names",
    templateFieldItemName: "Item code / name",
    templateFieldItemNameLimit: "Up to 30 characters",
    templateFieldQty: "Qty",
    templateFieldQtyLimit: "Up to 10 characters",
    templateFieldUnitPrice: "Unit price",
    templateFieldUnitPriceLimit: "Up to 10 characters",
    templateFieldAmount: "Amount",
    templateFieldAmountLimit: "Up to 10 characters",
    templateStandard: "Standard",
    templateEnvelope: "Envelope-compatible",
    templateModalCancel: "Cancel",
    templateModalSelect: "Select",
    taxSettings: "Tax settings",
    taxSeparate: "Tax separate",
    taxSeparateOnInvoice: "Tax separate (calculated on invoice)",
    taxIncluded: "Tax included",
    taxExempt: "Tax included (exempt)",
    taxRounding: "Tax rounding",
    taxRoundingNote: "Select how to handle fractions below 1 unit in consumption tax.",
    roundDown: "Round down",
    roundUp: "Round up",
    roundHalf: "Round half",
    documentRemarks: "Use default document remarks",
    documentSettings: "Document default settings",
    postalCode: "Postal code",
    postalCodePlaceholder: "Enter in 000-0000 format",
    postalCodeLookup: "Look up by postal code",
    address: "Address",
    recipientName: "Name",
    companyNamePlaceholder: "(e.g.) Company or individual name",
    departmentPlaceholder: "(e.g.) Department",
    namePlaceholder: "(e.g.) Full name",
    contactPlaceholder: "(e.g.) Contact person",
    sampleDate: "June 09, 2013",
    sampleDocNo: "Estimate No: 20130602-001",
    sampleClient: "Sample Corporation",
    sampleSubject: "Subject: Sample Project",
    sampleExpiryDate: "Expiry: June 30, 2013",
    sampleMessage: "We are pleased to submit the following estimate.",
    sampleAmountLabel: "Estimate amount",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "SalesFlow Inc.",
    sampleAddress: "〒151-0064\n3-13 Matsuzawa, Shibuya-ku, Tokyo\nSame Bldg. 1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "Document preparation", qty: "1", price: "50,000", amount: "50,000" },
      { name: "Design work, etc.", qty: "1", price: "80,000", amount: "80,000" },
      { name: "Travel expenses", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "Thank you for your continued business.",
  }
} as const;

export function getEstimateContent(locale: string) {
  if (locale === "ko" || locale === "en") {
    return labels[locale];
  }

  return labels.ja;
}
