export type DeliveryNoteLocale = "ja" | "ko" | "en";

const labels = {
  ja: {
    listTitle: "納品書",
    createDeliveryNote: "納品書を新しく作る",
    searchPlaceholder: "取引先名, 納品書番号, 件名, 社内メモ",
    searchDetail: "詳細検索",
    searchButton: "検索",
    tabs: ["未処理", "処理済", "ごみ箱"],
    tabTitles: ["納品書", "処理済みの納品書", "ごみ箱の納品書"],
    tabEmpty: ["納品書はありません", "処理済みの納品書はありません", "ごみ箱の納品書はありません"],
    trashNote: "ごみ箱の納品書は30日後に自動的に削除されます。",
    empty: "納品書はありません",
    newTitle: "納品書の新規作成",
    newTabs: ["基本情報", "送付先", "課税設定", "テンプレート"],
    deliveryInfo: "納品情報",
    senderInfo: "納品元情報",
    detailLink: "詳細（住所, 連絡先など）",
    required: "必須",
    requiredLine: "1行目必須",
    client: "取引先",
    issueDate: "発行日",
    deliveryDate: "納品日",
    noDate: "指定なし",
    deliveryNumber: "納品書番号",
    deliveryHint: "納品書番号を事前にお好みの形式で設定できます。",
    subject: "件名",
    itemHeaders: ["品番・品名", "数量", "単位", "単価", "税区分", "金額"],
    batchTax: "税区分を一括で",
    change: "変更する",
    addRow: "+ 行の追加",
    printNote: "印刷時には最低10行になります。行の追加は最大80行までです。",
    subtotal: "小計",
    tax: "消費税",
    total: "合計",
    remarks: "備考",
    save: "保存する",
    detailTitle: "納品書の詳細",
    companyName: "自社名",
    companyHonorific: "様",
    unit: "単位",
    issueDateValue: "2026/05/22",
    deliveryNumberValue: "20260522-001",
    companyValue: "Raon",
    backToList: "納品書へ戻る",
    // 送付先タブ
    postalCode: "郵便番号",
    postalCodePlaceholder: "000-0000形式（半角）で入力してください",
    postalCodeLookup: "郵便番号から検索",
    address: "住所",
    recipientName: "名前",
    companyNamePlaceholder: "（例）合社名または個人名",
    departmentPlaceholder: "（例）部署名",
    namePlaceholder: "（例）氏名",
    contactPlaceholder: "（例）担当者名",
    // 課税設定タブ
    taxSettings: "消費税設定",
    taxSeparate: "税別表示",
    taxSeparateOnInvoice: "税別表示（請求時に計算）",
    taxIncluded: "税込表示",
    taxExempt: "税込表示（免税）",
    taxRounding: "消費税端数処理",
    taxRoundingNote: "1円に満たない消費税の小数以下の処理方法を選択できます。",
    roundDown: "切り捨て",
    roundUp: "切り上げ",
    roundHalf: "四捨五入",
    documentRemarks: "文書初期設定の備考を使う",
    documentSettings: "文書初期設定",
    // テンプレートタブ
    templateTitle: "カスタマイズオプション",
    templateNote: "テンプレートの内容を変更できます。初期値は文書初期設定で変更可能です。",
    templateSettingsLink: "設定画面へ",
    templateChangeButton: "テンプレートを変更",
    templateChangeTitle: "テンプレートの変更",
    templateMessageLabel: "メッセージ",
    templateMessagePlaceholder: "下記のとおり納品いたします。",
    templateFieldsTitle: "明細項目の表示名",
    templateFieldItemName: "品番・品名",
    templateFieldItemNameLimit: "30文字以内で入力してください",
    templateFieldQty: "数量",
    templateFieldQtyLimit: "10文字以内で入力してください",
    templateFieldUnitPrice: "単価",
    templateFieldUnitPriceLimit: "10文字以内で入力してください",
    templateFieldAmount: "金額",
    templateFieldAmountLimit: "10文字以内で入力してください",
    templateStandard: "スタンダード",
    templateEnvelope: "忘付封筒対応",
    templateModalCancel: "キャンセル",
    templateModalSelect: "選択する",
    // プレビューサンプルデータ
    sampleDate: "2013年06月09日",
    sampleDocNo: "納品書番号: 20130602-001",
    sampleClient: "サンプル株式会社 様",
    sampleSubject: "件名：サンプルプロジェクト",
    sampleDeliveryDate: "納品日：2013年06月10日",
    sampleMessage: "下記のとおり納品いたします。",
    sampleAmountLabel: "合計金額",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "ミソカインダイス株式会社",
    sampleAddress: "〒151-0064\n東京都渋谷区松涛 3-13\n鮫ビル1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "企画書作成", qty: "1企業", price: "50,000", amount: "50,000" },
      { name: "デザイン業務他", qty: "1案", price: "80,000", amount: "80,000" },
      { name: "交通費", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "いつもありがとうございます。",
  },
  ko: {
    listTitle: "납품서",
    createDeliveryNote: "납품서를 새로 만들기",
    searchPlaceholder: "거래처명, 납품서 번호, 제목, 사내 메모",
    searchDetail: "상세 검색",
    searchButton: "검색",
    tabs: ["미처리", "처리 완료", "휴지통"],
    tabTitles: ["납품서", "처리 완료된 납품서", "휴지통의 납품서"],
    tabEmpty: ["납품서가 없습니다", "처리 완료된 납품서가 없습니다", "휴지통의 납품서가 없습니다"],
    trashNote: "휴지통의 납품서는 30일 후 자동으로 삭제됩니다.",
    empty: "납품서가 없습니다",
    newTitle: "납품서 신규 작성",
    newTabs: ["기본 정보", "수신처", "과세 설정", "템플릿"],
    deliveryInfo: "납품 정보",
    senderInfo: "납품원 정보",
    detailLink: "상세(주소, 연락처 등)",
    required: "필수",
    requiredLine: "1행 필수",
    client: "거래처",
    issueDate: "발행일",
    deliveryDate: "납품일",
    noDate: "지정 없음",
    deliveryNumber: "납품서 번호",
    deliveryHint: "납품서 번호 형식을 미리 원하는 방식으로 설정할 수 있습니다.",
    subject: "제목",
    itemHeaders: ["품번·품명", "수량", "단위", "단가", "세금 구분", "금액"],
    batchTax: "세금 구분 일괄",
    change: "변경하기",
    addRow: "+ 행 추가",
    printNote: "인쇄 시 최소 10행이 됩니다. 행 추가는 최대 80행까지 가능합니다.",
    subtotal: "소계",
    tax: "소비세",
    total: "합계",
    remarks: "비고",
    save: "저장하기",
    detailTitle: "납품서 상세",
    companyName: "자사명",
    companyHonorific: "님",
    unit: "단위",
    issueDateValue: "2026/05/22",
    deliveryNumberValue: "20260522-001",
    companyValue: "Raon",
    backToList: "납품서로 돌아가기",
    postalCode: "우편번호",
    postalCodePlaceholder: "000-0000 형식(반각)으로 입력해 주세요",
    postalCodeLookup: "우편번호로 검색",
    address: "주소",
    recipientName: "이름",
    companyNamePlaceholder: "（예）법인명 또는 개인명",
    departmentPlaceholder: "（예）부서명",
    namePlaceholder: "（예）성명",
    contactPlaceholder: "（예）담당자명",
    taxSettings: "소비세 설정",
    taxSeparate: "세별 표시",
    taxSeparateOnInvoice: "세별 표시（청구 시 계산）",
    taxIncluded: "세포함 표시",
    taxExempt: "세포함 표시（면세）",
    taxRounding: "소비세 단수 처리",
    taxRoundingNote: "1원 미만의 소비세 소수점 이하 처리 방법을 선택할 수 있습니다.",
    roundDown: "버림",
    roundUp: "올림",
    roundHalf: "반올림",
    documentRemarks: "문서 초기 설정의 비고 사용",
    documentSettings: "문서 초기 설정",
    templateTitle: "커스터마이즈 옵션",
    templateNote: "템플릿 내용을 변경할 수 있습니다. 초기값은 문서 초기 설정에서 변경 가능합니다.",
    templateSettingsLink: "설정 화면으로",
    templateChangeButton: "템플릿 변경",
    templateChangeTitle: "템플릿 변경",
    templateMessageLabel: "메시지",
    templateMessagePlaceholder: "아래와 같이 납품합니다.",
    templateFieldsTitle: "명세 항목의 표시명",
    templateFieldItemName: "품번·품명",
    templateFieldItemNameLimit: "30자 이내로 입력해 주세요",
    templateFieldQty: "수량",
    templateFieldQtyLimit: "10자 이내로 입력해 주세요",
    templateFieldUnitPrice: "단가",
    templateFieldUnitPriceLimit: "10자 이내로 입력해 주세요",
    templateFieldAmount: "금액",
    templateFieldAmountLimit: "10자 이내로 입력해 주세요",
    templateStandard: "스탠다드",
    templateEnvelope: "봉투 대응",
    templateModalCancel: "취소",
    templateModalSelect: "선택하기",
    sampleDate: "2013년 06월 09일",
    sampleDocNo: "납품서 번호: 20130602-001",
    sampleClient: "샘플 주식회사 귀중",
    sampleSubject: "건명：샘플 프로젝트",
    sampleDeliveryDate: "납품일：2013년 06월 10일",
    sampleMessage: "아래와 같이 납품합니다.",
    sampleAmountLabel: "합계 금액",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "미소카인다이스 주식회사",
    sampleAddress: "〒151-0064\n도쿄도 시부야구 마쓰자와 3-13\n사메 빌딩 1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "기획서 작성", qty: "1건", price: "50,000", amount: "50,000" },
      { name: "디자인 업무 외", qty: "1건", price: "80,000", amount: "80,000" },
      { name: "교통비", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "항상 감사합니다.",
  },
  en: {
    listTitle: "Delivery Notes",
    createDeliveryNote: "Create a new delivery note",
    searchPlaceholder: "Client, delivery note number, subject, internal memo",
    searchDetail: "Advanced search",
    searchButton: "Search",
    tabs: ["Open", "Processed", "Trash"],
    tabTitles: ["Delivery notes", "Processed delivery notes", "Trash"],
    tabEmpty: ["No delivery notes found", "No processed delivery notes found", "No delivery notes in trash"],
    trashNote: "Delivery notes in the trash will be automatically deleted after 30 days.",
    empty: "No delivery notes found",
    newTitle: "Create delivery note",
    newTabs: ["Basic info", "Recipient", "Tax settings", "Template"],
    deliveryInfo: "Delivery information",
    senderInfo: "Sender information",
    detailLink: "Details (address, contact, etc.)",
    required: "Required",
    requiredLine: "Line 1 required",
    client: "Client",
    issueDate: "Issue date",
    deliveryDate: "Delivery date",
    noDate: "Not specified",
    deliveryNumber: "Delivery note number",
    deliveryHint: "You can preset your preferred delivery note number format.",
    subject: "Subject",
    itemHeaders: ["Item code / name", "Qty", "Unit", "Unit price", "Tax", "Amount"],
    batchTax: "Apply tax rate",
    change: "Change",
    addRow: "+ Add row",
    printNote: "At least 10 rows are printed. You can add up to 80 rows.",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    remarks: "Notes",
    save: "Save",
    detailTitle: "Delivery note details",
    companyName: "Company name",
    companyHonorific: "",
    unit: "Unit",
    issueDateValue: "2026/05/22",
    deliveryNumberValue: "20260522-001",
    companyValue: "Raon",
    backToList: "Back to delivery notes",
    postalCode: "Postal code",
    postalCodePlaceholder: "Enter in 000-0000 format",
    postalCodeLookup: "Look up by postal code",
    address: "Address",
    recipientName: "Name",
    companyNamePlaceholder: "(e.g.) Company or individual name",
    departmentPlaceholder: "(e.g.) Department",
    namePlaceholder: "(e.g.) Full name",
    contactPlaceholder: "(e.g.) Contact person",
    taxSettings: "Tax settings",
    taxSeparate: "Tax separate",
    taxSeparateOnInvoice: "Tax separate (calculated on invoice)",
    taxIncluded: "Tax included",
    taxExempt: "Tax included (exempt)",
    taxRounding: "Tax rounding",
    taxRoundingNote: "Select how to handle fractions below 1 unit in consumption tax.",
    roundDown: "Round down",
    roundUp: "Round up",
    roundHalf: "Round half",
    documentRemarks: "Use default document remarks",
    documentSettings: "Document default settings",
    templateTitle: "Customize options",
    templateNote: "You can change the template content. The default can be changed in Document defaults.",
    templateSettingsLink: "Go to settings",
    templateChangeButton: "Change template",
    templateChangeTitle: "Change template",
    templateMessageLabel: "Message",
    templateMessagePlaceholder: "We hereby deliver the following items.",
    templateFieldsTitle: "Line item display names",
    templateFieldItemName: "Item code / name",
    templateFieldItemNameLimit: "Up to 30 characters",
    templateFieldQty: "Qty",
    templateFieldQtyLimit: "Up to 10 characters",
    templateFieldUnitPrice: "Unit price",
    templateFieldUnitPriceLimit: "Up to 10 characters",
    templateFieldAmount: "Amount",
    templateFieldAmountLimit: "Up to 10 characters",
    templateStandard: "Standard",
    templateEnvelope: "Envelope-compatible",
    templateModalCancel: "Cancel",
    templateModalSelect: "Select",
    sampleDate: "June 09, 2013",
    sampleDocNo: "Delivery No: 20130602-001",
    sampleClient: "Sample Corporation",
    sampleSubject: "Subject: Sample Project",
    sampleDeliveryDate: "Delivery date: June 10, 2013",
    sampleMessage: "We hereby deliver the following items.",
    sampleAmountLabel: "Total amount",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "SalesFlow Inc.",
    sampleAddress: "〒151-0064\n3-13 Matsuzawa, Shibuya-ku, Tokyo\nSame Bldg. 1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "Document preparation", qty: "1", price: "50,000", amount: "50,000" },
      { name: "Design work, etc.", qty: "1", price: "80,000", amount: "80,000" },
      { name: "Travel expenses", qty: "1", price: "1,800", amount: "1,800" },
    ] as { name: string; qty: string; price: string; amount: string }[],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "Thank you for your continued business.",
  },
} as const;

export function getDeliveryNoteContent(locale: string) {
  if (locale === "ko" || locale === "en") {
    return labels[locale];
  }

  return labels.ja;
}
