export type ReceiptLocale = "ja" | "ko" | "en";

const labels = {
  ja: {
    listTitle: "領収書",
    createReceipt: "領収書を新しく作る",
    searchPlaceholder: "取引先名, 領収書番号, 件名, 社内メモ",
    searchDetail: "詳細検索",
    searchButton: "検索",
    tabs: ["未処理", "処理済", "ごみ箱"],
    tabTitles: ["領収書", "処理済みの領収書", "ごみ箱の領収書"],
    tabEmpty: ["領収書はありません", "処理済みの領収書はありません", "ごみ箱の領収書はありません"],
    trashNote: "ごみ箱の領収書は30日後に自動的に削除されます。",
    empty: "領収書はありません",
    newTitle: "領収書の新規作成",
    newTabs: ["基本情報", "送付先", "課税設定", "テンプレート"],
    receiptInfo: "領収情報",
    senderInfo: "領収元情報",
    detailLink: "詳細（住所, 連絡先など）",
    required: "必須",
    requiredLine: "1行目必須",
    client: "取引先",
    issueDate: "発行日",
    transactionDate: "取引日",
    noDate: "指定なし",
    receiptNumber: "領収書番号",
    receiptHint: "領収書番号を事前にお好みの形式で設定できます。",
    subject: "件名",
    itemHeaders: ["品番・品名", "数量", "単位", "単価", "税区分", "金額"],
    batchTax: "税区分を一括で",
    change: "変更する",
    addRow: "+ 行の追加",
    printNote: "印刷時には最低10行になります。行の追加は最大80行までです。",
    subtotal: "小計",
    tax: "消費税",
    total: "合計",
    remarks: "備考",
    save: "保存する",
    companyName: "自社名",
    companyHonorific: "様",
    unit: "単位",
    issueDateValue: "2026/05/22",
    receiptNumberValue: "20260522-001",
    companyValue: "Raon",
    // 送付先 탭
    postalCode: "郵便番号",
    postalCodePlaceholder: "000-0000形式（半角）で入力してください",
    postalCodeLookup: "郵便番号から検索",
    address: "住所",
    recipientName: "名前",
    companyNamePlaceholder: "（例）会社または個人名",
    departmentPlaceholder: "（例）部署名",
    sectionPlaceholder: "（例）課名",
    contactPlaceholder: "（例）担当者名",
    // 課税設定 탭
    taxSettingsTitle: "消費税設定",
    taxSeparate: "税別表示",
    taxIncluded: "税込表示",
    taxExempt: "税込表示（免税）",
    taxRounding: "消費税端数処理",
    taxRoundingNote: "「小計」にかかる消費税の小数点以下の処理方法を選択できます。",
    roundDown: "切り捨て",
    roundUp: "切り上げ",
    roundHalf: "四捨五入",
    withholdingTitle: "源泉徴収税種別",
    withholdingLink: "源泉徴収税の計算方法について",
    withholdingNone: "なし",
    withholdingWith: "あり（復興税あり）",
    withholdingWithout: "あり（復興税なし）",
    // テンプレート 탭
    templateTitle: "カスタマイズオプション",
    templateNote: "テンプレートの内容を変更できます。初期値は文書初期設定で変更可能です。",
    templateSettingsLink: "設定画面へ",
    templateChangeButton: "テンプレートを変更",
    templateMessageLabel: "メッセージ",
    templateMessagePlaceholder: "下記のとおり領収いたしました。",
    templateFieldsTitle: "明細項目の表示名",
    templateFieldItemName: "品番・品名",
    templateFieldItemNameLimit: "30文字以内で入力してください",
    templateFieldQty: "数量",
    templateFieldQtyLimit: "10文字以内で入力してください",
    templateFieldUnitPrice: "単値",
    templateFieldUnitPriceLimit: "10文字以内で入力してください",
    templateFieldAmount: "金額",
    templateFieldAmountLimit: "10文字以内で入力してください",
    templateStandard: "スタンダード",
    templateEnvelope: "忘付封筒対応",
    templateModalCancel: "キャンセル",
    templateModalSelect: "選択する",
    // 샘플 데이터 (모달 프리뷰용)
    sampleDate: "2014年06月01日",
    sampleReceiptNo: "領収書番号: 20140601-001",
    sampleClient: "サンプル株式会社 様",
    sampleSubject: "件名：サンプルプロジェクト",
    sampleTransDate: "取引日：2024年05月24日",
    sampleMessage: "下記のとおり領収いたしました。",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "ミソカインダイス株式会社",
    sampleAddress: "〒151-0064\n東京都渋谷区松涛 3-13\n鮫ビル1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "行書類作成", qty: "1企業", price: "50,000", amount: "50,000" },
      { name: "デザイン業務他", qty: "1案", price: "80,000", amount: "80,000" },
      { name: "交通費", qty: "1", price: "1,800", amount: "1,800" },
    ],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "いつもありがとうございます。",
    documentRemarks: "文書初期設定の備考を使う",
    documentSettings: "文書初期設定",
  },
  ko: {
    listTitle: "영수증",
    createReceipt: "영수증을 새로 만들기",
    searchPlaceholder: "거래처명, 영수증 번호, 제목, 사내 메모",
    searchDetail: "상세 검색",
    searchButton: "검색",
    tabs: ["미처리", "처리 완료", "휴지통"],
    tabTitles: ["영수증", "처리 완료된 영수증", "휴지통의 영수증"],
    tabEmpty: ["영수증이 없습니다", "처리 완료된 영수증이 없습니다", "휴지통의 영수증이 없습니다"],
    trashNote: "휴지통의 영수증은 30일 후 자동으로 삭제됩니다.",
    empty: "영수증이 없습니다",
    newTitle: "영수증 신규 작성",
    newTabs: ["기본 정보", "수신처", "과세 설정", "템플릿"],
    receiptInfo: "영수 정보",
    senderInfo: "영수원 정보",
    detailLink: "상세(주소, 연락처 등)",
    required: "필수",
    requiredLine: "1행 필수",
    client: "거래처",
    issueDate: "발행일",
    transactionDate: "거래일",
    noDate: "지정 없음",
    receiptNumber: "영수증 번호",
    receiptHint: "영수증 번호 형식을 미리 원하는 방식으로 설정할 수 있습니다.",
    subject: "제목",
    itemHeaders: ["품번·품명", "수량", "단위", "단가", "세금 구분", "금액"],
    batchTax: "세금 구분 일괄",
    change: "변경하기",
    addRow: "+ 행 추가",
    printNote: "인쇄 시 최소 10행이 됩니다. 행 추가는 최대 80행까지 가능합니다.",
    subtotal: "소계",
    tax: "소비세",
    total: "합계",
    remarks: "비고",
    save: "저장하기",
    companyName: "자사명",
    companyHonorific: "님",
    unit: "단위",
    issueDateValue: "2026/05/22",
    receiptNumberValue: "20260522-001",
    companyValue: "Raon",
    postalCode: "우편번호",
    postalCodePlaceholder: "000-0000 형식(반각)으로 입력해 주세요",
    postalCodeLookup: "우편번호로 검색",
    address: "주소",
    recipientName: "이름",
    companyNamePlaceholder: "（예）법인명 또는 개인명",
    departmentPlaceholder: "（예）부서명",
    sectionPlaceholder: "（예）과명",
    contactPlaceholder: "（예）담당자명",
    taxSettingsTitle: "소비세 설정",
    taxSeparate: "세별 표시",
    taxIncluded: "세포함 표시",
    taxExempt: "세포함 표시（면세）",
    taxRounding: "소비세 단수 처리",
    taxRoundingNote: "「소계」에 부과되는 소비세 소수점 이하 처리 방법을 선택할 수 있습니다.",
    roundDown: "버림",
    roundUp: "올림",
    roundHalf: "반올림",
    withholdingTitle: "원천징수세 종별",
    withholdingLink: "원천징수세 계산 방법에 대하여",
    withholdingNone: "없음",
    withholdingWith: "있음（부흥세 있음）",
    withholdingWithout: "있음（부흥세 없음）",
    templateTitle: "커스터마이즈 옵션",
    templateNote: "템플릿 내용을 변경할 수 있습니다. 초기값은 문서 초기 설정에서 변경 가능합니다.",
    templateSettingsLink: "설정 화면으로",
    templateChangeButton: "템플릿 변경",
    templateMessageLabel: "메시지",
    templateMessagePlaceholder: "아래와 같이 영수하였습니다.",
    templateFieldsTitle: "명세 항목의 표시명",
    templateFieldItemName: "품번·품명",
    templateFieldItemNameLimit: "30자 이내로 입력해 주세요",
    templateFieldQty: "수량",
    templateFieldQtyLimit: "10자 이내로 입력해 주세요",
    templateFieldUnitPrice: "단가",
    templateFieldUnitPriceLimit: "10자 이내로 입력해 주세요",
    templateFieldAmount: "금액",
    templateFieldAmountLimit: "10자 이내로 입력해 주세요",
    templateStandard: "스탠다드",
    templateEnvelope: "봉투 대응",
    templateModalCancel: "취소",
    templateModalSelect: "선택하기",
    sampleDate: "2014년 06월 01일",
    sampleReceiptNo: "영수증 번호: 20140601-001",
    sampleClient: "샘플 주식회사 귀중",
    sampleSubject: "건명：샘플 프로젝트",
    sampleTransDate: "거래일：2024년 05월 24일",
    sampleMessage: "아래와 같이 영수하였습니다.",
    sampleAmount: "₩ 144,980 -",
    sampleCompany: "미소카인다이스 주식회사",
    sampleAddress: "〒151-0064\n도쿄도 시부야구 마쓰자와 3-13\n사메 빌딩 1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "서류 작성", qty: "1건", price: "50,000", amount: "50,000" },
      { name: "디자인 업무 외", qty: "1건", price: "80,000", amount: "80,000" },
      { name: "교통비", qty: "1", price: "1,800", amount: "1,800" },
    ],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "항상 감사합니다.",
    documentRemarks: "문서 초기 설정의 비고 사용",
    documentSettings: "문서 초기 설정",
  },
  en: {
    listTitle: "Receipts",
    createReceipt: "Create a new receipt",
    searchPlaceholder: "Client, receipt number, subject, internal memo",
    searchDetail: "Advanced search",
    searchButton: "Search",
    tabs: ["Open", "Processed", "Trash"],
    tabTitles: ["Receipts", "Processed receipts", "Trash"],
    tabEmpty: ["No receipts found", "No processed receipts found", "No receipts in trash"],
    trashNote: "Receipts in the trash will be automatically deleted after 30 days.",
    empty: "No receipts found",
    newTitle: "Create receipt",
    newTabs: ["Basic info", "Recipient", "Tax settings", "Template"],
    receiptInfo: "Receipt information",
    senderInfo: "Issuer information",
    detailLink: "Details (address, contact, etc.)",
    required: "Required",
    requiredLine: "Line 1 required",
    client: "Client",
    issueDate: "Issue date",
    transactionDate: "Transaction date",
    noDate: "Not specified",
    receiptNumber: "Receipt number",
    receiptHint: "You can preset your preferred receipt number format.",
    subject: "Subject",
    itemHeaders: ["Item code / name", "Qty", "Unit", "Unit price", "Tax", "Amount"],
    batchTax: "Apply tax rate",
    change: "Change",
    addRow: "+ Add row",
    printNote: "At least 10 rows are printed. You can add up to 80 rows.",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    remarks: "Notes",
    save: "Save",
    companyName: "Company name",
    companyHonorific: "",
    unit: "Unit",
    issueDateValue: "2026/05/22",
    receiptNumberValue: "20260522-001",
    companyValue: "Raon",
    postalCode: "Postal code",
    postalCodePlaceholder: "Enter in 000-0000 format",
    postalCodeLookup: "Look up by postal code",
    address: "Address",
    recipientName: "Name",
    companyNamePlaceholder: "(e.g.) Company or individual name",
    departmentPlaceholder: "(e.g.) Department",
    sectionPlaceholder: "(e.g.) Section",
    contactPlaceholder: "(e.g.) Contact person",
    taxSettingsTitle: "Tax settings",
    taxSeparate: "Tax separate",
    taxIncluded: "Tax included",
    taxExempt: "Tax included (exempt)",
    taxRounding: "Tax rounding",
    taxRoundingNote: "Select how to handle fractions below 1 unit in consumption tax on the subtotal.",
    roundDown: "Round down",
    roundUp: "Round up",
    roundHalf: "Round half",
    withholdingTitle: "Withholding tax type",
    withholdingLink: "About withholding tax calculation",
    withholdingNone: "None",
    withholdingWith: "Yes (with recovery tax)",
    withholdingWithout: "Yes (without recovery tax)",
    templateTitle: "Customize options",
    templateNote: "You can change the template content. The default can be changed in Document defaults.",
    templateSettingsLink: "Go to settings",
    templateChangeButton: "Change template",
    templateMessageLabel: "Message",
    templateMessagePlaceholder: "We hereby acknowledge receipt of the following.",
    templateFieldsTitle: "Line item display names",
    templateFieldItemName: "Item code / name",
    templateFieldItemNameLimit: "Up to 30 characters",
    templateFieldQty: "Qty",
    templateFieldQtyLimit: "Up to 10 characters",
    templateFieldUnitPrice: "Unit price",
    templateFieldUnitPriceLimit: "Up to 10 characters",
    templateFieldAmount: "Amount",
    templateFieldAmountLimit: "Up to 10 characters",
    templateStandard: "Standard",
    templateEnvelope: "Envelope-compatible",
    templateModalCancel: "Cancel",
    templateModalSelect: "Select",
    sampleDate: "June 01, 2014",
    sampleReceiptNo: "Receipt No: 20140601-001",
    sampleClient: "Sample Corporation",
    sampleSubject: "Subject: Sample Project",
    sampleTransDate: "Transaction date: May 24, 2024",
    sampleMessage: "We hereby acknowledge receipt of the following.",
    sampleAmount: "¥ 144,980 -",
    sampleCompany: "SalesFlow Inc.",
    sampleAddress: "〒151-0064\n3-13 Matsuzawa, Shibuya-ku, Tokyo\nSame Bldg. 1F",
    samplePhone: "TEL: 03-0000-0001\nFAX: 03-0000-0002\noffice@example.com",
    sampleItems: [
      { name: "Document preparation", qty: "1", price: "50,000", amount: "50,000" },
      { name: "Design work, etc.", qty: "1", price: "80,000", amount: "80,000" },
      { name: "Travel expenses", qty: "1", price: "1,800", amount: "1,800" },
    ],
    sampleSubtotal: "131,800",
    sampleTax: "13,180",
    sampleTotal: "144,980",
    sampleThanks: "Thank you for your continued business.",
    documentRemarks: "Use default document remarks",
    documentSettings: "Document default settings",
  },
} as const;

export function getReceiptContent(locale: string) {
  if (locale === "ko" || locale === "en") {
    return labels[locale];
  }

  return labels.ja;
}
