import type { AppLocale } from "@/contexts/language-context";

export type ClientRow = {
  id: string;
  name: string;
  managementCode: string;
  destination: string;
};

const sampleClients: ClientRow[] = [
  { id: "1", name: "11111", managementCode: "", destination: "" },
  { id: "2", name: "raon2", managementCode: "", destination: "" },
];

const labels = {
  ja: {
    tabs: ["取引先", "一括登録・更新"],
    title: "取引先",
    createClient: "取引先の新規登録",
    searchPlaceholder: "取引先名、管理コード、送り先",
    search: "検索",
    csvDownload: "CSVダウンロード",
    tableHeaders: ["取引先", "管理コード", "送り先", "操作"],
    edit: "編集",
    createDocument: "文書の作成",
    showDocument: "文書の表示",
    listToggle: "一覧 / 非表示",
    honorific: "様",
    modal: {
      title: "取引先/送り先を新規登録",
      clientName: "取引先名",
      required: "必須",
      nameSuffix: "様",
      charCount: "0/40",
      corpLookup: "国税庁 法人番号公表サイトから検索して自動入力する",
      furigana: "ふりがな",
      corpNumber: "法人番号",
      corpNumberHint: "法人番号公表サイトから入力すると自動で入力されます。",
      destinationTab: "送り先",
      addTab: "+ 追加",
      managementCode: "管理コード",
      managementCodeHint: "CSV一括で請求書を作成する際に利用する任意の文字列を設定できます。",
      department: "部署・担当者",
      departmentHint: "3行まで入力できます。",
      email: "メールアドレス",
      emailPlaceholder: "a@salesflow.com",
      emailCc: "メールアドレス (CC)",
      emailCcPlaceholder: "b@salesflow.com, c@salesflow.com, ...",
      emailCcHint: "メール送信時にCCで送るメールアドレスを追加します。複数ある場合はカンマで区切ってください。",
      postalCode: "郵便番号",
      postalCodeHint: "000-0000形式(半角)で入力してください",
      postalCodeLookup: "郵便番号から検索",
      address: "住所",
      addressLine1Placeholder: "都道府県・市区町村",
      addressLine2Placeholder: "番地・ビル名",
      mailingName: "郵送先の宛名",
      mailingNameHint: "郵送の場合、1行目は必須です。",
      mailingLine1Placeholder: "会社名または個人名",
      mailingLine2Placeholder: "部署名",
      mailingLine3Placeholder: "課名",
      mailingLine4NamePlaceholder: "名前",
      honorificLabel: "敬称",
      phone: "電話番号",
      phonePlaceholder: "03012345678",
      fax: "FAX番号",
      faxPlaceholder: "03012345678",
      memo: "メモ",
      memoHint: "請求書などの文書には印字されません。",
      cancel: "キャンセル",
      register: "登録する",
    },
    sampleClients,
  },
  ko: {
    tabs: ["거래처", "일괄 등록·업데이트"],
    title: "거래처",
    createClient: "거래처 신규 등록",
    searchPlaceholder: "거래처명, 관리 코드, 배송지",
    search: "검색",
    csvDownload: "CSV 다운로드",
    tableHeaders: ["거래처", "관리 코드", "배송지", "작업"],
    edit: "편집",
    createDocument: "문서 작성",
    showDocument: "문서 표시",
    listToggle: "목록 / 숨기기",
    honorific: "귀중",
    modal: {
      title: "거래처/배송지 신규 등록",
      clientName: "거래처명",
      required: "필수",
      nameSuffix: " 귀중",
      charCount: "0/40",
      corpLookup: "국세청 법인번호 공표 사이트에서 검색하여 자동 입력",
      furigana: "후리가나",
      corpNumber: "법인번호",
      corpNumberHint: "법인번호 공표 사이트에서 입력하면 자동으로 입력됩니다.",
      destinationTab: "배송지",
      addTab: "+ 추가",
      managementCode: "관리 코드",
      managementCodeHint: "CSV 일괄 청구서 작성 시 사용할 임의 문자열을 설정할 수 있습니다.",
      department: "부서·담당자",
      departmentHint: "최대 3행까지 입력할 수 있습니다.",
      email: "이메일 주소",
      emailPlaceholder: "a@salesflow.com",
      emailCc: "이메일 주소 (CC)",
      emailCcPlaceholder: "b@salesflow.com, c@salesflow.com, ...",
      emailCcHint: "메일 발송 시 CC로 보낼 이메일 주소를 추가합니다. 여러 개는 쉼표로 구분해 주세요.",
      postalCode: "우편번호",
      postalCodeHint: "000-0000 형식(반각)으로 입력해 주세요",
      postalCodeLookup: "우편번호로 검색",
      address: "주소",
      addressLine1Placeholder: "도도부현·시구정촌",
      addressLine2Placeholder: "번지·빌딩명",
      mailingName: "우편 발송처 수신인",
      mailingNameHint: "우편 발송 시 1행은 필수입니다.",
      mailingLine1Placeholder: "회사명 또는 개인명",
      mailingLine2Placeholder: "부서명",
      mailingLine3Placeholder: "과명",
      mailingLine4NamePlaceholder: "이름",
      honorificLabel: "경칭",
      phone: "전화번호",
      phonePlaceholder: "03012345678",
      fax: "FAX 번호",
      faxPlaceholder: "03012345678",
      memo: "메모",
      memoHint: "청구서 등 문서에는 인쇄되지 않습니다.",
      cancel: "취소",
      register: "등록하기",
    },
    sampleClients,
  },
  en: {
    tabs: ["Clients", "Bulk Registration / Update"],
    title: "Clients",
    createClient: "Register New Client",
    searchPlaceholder: "Client name, management code, destination",
    search: "Search",
    csvDownload: "CSV Download",
    tableHeaders: ["Client", "Management Code", "Destination", "Actions"],
    edit: "Edit",
    createDocument: "Create Document",
    showDocument: "Show Document",
    listToggle: "List / Hidden",
    honorific: "",
    modal: {
      title: "Register New Client / Destination",
      clientName: "Client Name",
      required: "Required",
      nameSuffix: "",
      charCount: "0/40",
      corpLookup: "Search National Tax Agency Corporate Number site and auto-fill",
      furigana: "Furigana",
      corpNumber: "Corporate Number",
      corpNumberHint: "Automatically filled when entered from the Corporate Number database.",
      destinationTab: "Destination",
      addTab: "+ Add",
      managementCode: "Management Code",
      managementCodeHint: "Set any string used when creating invoices in bulk via CSV.",
      department: "Department / Contact",
      departmentHint: "Up to 3 lines can be entered.",
      email: "Email Address",
      emailPlaceholder: "a@salesflow.com",
      emailCc: "Email Address (CC)",
      emailCcPlaceholder: "b@salesflow.com, c@salesflow.com, ...",
      emailCcHint: "Add email addresses to be CC'd. Use commas for multiple entries.",
      postalCode: "Postal Code",
      postalCodeHint: "Enter in 000-0000 format (half-width)",
      postalCodeLookup: "Search by postal code",
      address: "Address",
      addressLine1Placeholder: "Prefecture, City/Town/Village",
      addressLine2Placeholder: "Street, Building name",
      mailingName: "Mailing Address Name",
      mailingNameHint: "For mailing, the first line is mandatory.",
      mailingLine1Placeholder: "Company or individual name",
      mailingLine2Placeholder: "Department name",
      mailingLine3Placeholder: "Section name",
      mailingLine4NamePlaceholder: "Name",
      honorificLabel: "Honorific",
      phone: "Phone Number",
      phonePlaceholder: "03012345678",
      fax: "FAX Number",
      faxPlaceholder: "03012345678",
      memo: "Memo",
      memoHint: "Will not be printed on documents such as invoices.",
      cancel: "Cancel",
      register: "Register",
    },
    sampleClients,
  },
} as const;

export function getClientsContent(lang: AppLocale) {
  return labels[lang];
}
