import type { AppLocale } from "@/contexts/language-context";

const labels = {
  ja: {
    tabs: ["取引先", "一括登録・更新"],
    title: "取引先",
    createClient: "取引先の新規登録",
    searchPlaceholder: "取引先名、管理コード、送り先",
    search: "検索",
    csvDownload: "CSVダウンロード",
    csvHeaders: ["取引先名", "ふりがな", "管理コード", "部署", "メール", "電話", "FAX"],
    tableHeaders: ["取引先", "管理コード", "送り先", "操作"],
    edit: "編集",
    delete: "削除",
    deleteConfirm: "この取引先を削除しますか？",
    favoritesOnly: "お気に入りのみ表示",
    favorite: "お気に入り",
    empty: "取引先はありません",
    createDocument: "文書の作成",
    showDocument: "文書の表示",
    listToggle: "一覧 / 非表示",
    honorific: "様",
    bulk: {
      title: "取引先の一括登録・更新(CSVアップロード)",
      intro:
        "CSVファイルをアップロードして、取引先をまとめて登録・更新できます。管理コードが既存の取引先と一致する場合は、その取引先を更新します。",
      uploadSection: "CSVファイルのアップロード",
      chooseFile: "ファイルを選択",
      noFile: "選択されていません",
      upload: "アップロード",
      uploadResult: "{created}件を登録、{updated}件を更新しました",
      emptyFile: "CSVにデータ行がありません。",
      uploadNotes: [
        "ExcelでCSV形式として保存したファイルをアップロードしてください。",
        "1行目はヘッダー行として扱われます。",
        "管理コードが既存の取引先と一致する場合は更新、空欄または未登録の場合は新規登録になります。",
        "空欄のセルは既存の値をそのまま残します(消去されません)。",
        "1行でもエラーがある場合は1件も登録されません。",
        "一度に処理できる件数は最大1000件です。",
      ],
      templateSection: "入力用テンプレートのダウンロード",
      templateUtf8: "UTF-8版",
      templateUtf8Button: "UTF-8版 入力用テンプレート",
      templateShiftJis: "Shift-JIS版\n(Excelをお使いの方はこちら)",
      templateShiftJisButton: "Shift-JIS版 入力用テンプレート",
      formatSection: "入力用テンプレートの形式",
      formatRows: [
        ["形式", "CSV形式"],
        ["文字コード", "UTF-8 または Shift-JIS"],
      ] as const,
      formatNote: "保存の際は上記の形式で保存してください。",
      fieldsSection: "入力用テンプレートの項目説明",
      fieldsIntro: "入力用テンプレートの各項目は次のとおりです。",
      fieldHeaders: ["項目", "必須", "制限", "説明"],
      fields: [
        { name: "取引先名", required: "○", limit: "40文字", desc: "取引先の名称です。" },
        { name: "フリガナ", required: "", limit: "100文字", desc: "並び替えに使われます。" },
        {
          name: "管理コード",
          required: "",
          limit: "40文字",
          desc: "更新のキーになります。既存の取引先と一致すると、その取引先を上書き更新します。",
        },
        { name: "法人番号", required: "", limit: "13文字", desc: "国税庁の法人番号です。" },
        { name: "部署・担当者", required: "", limit: "100文字", desc: "部署名・担当者名です。" },
        { name: "メールアドレス", required: "", limit: "—", desc: "形式が正しくない場合はエラーになります。" },
        {
          name: "メールアドレス(CC)",
          required: "",
          limit: "10件",
          desc: "複数ある場合はセミコロン(;)で区切ってください。",
        },
        { name: "電話番号", required: "", limit: "30文字", desc: "ハイフンはあってもかまいません。" },
        { name: "FAX番号", required: "", limit: "30文字", desc: "ハイフンはあってもかまいません。" },
        { name: "敬称", required: "", limit: "10文字", desc: "「様」「御中」などを入力します。" },
        { name: "郵便番号", required: "", limit: "8文字", desc: "000-0000形式(半角)で入力してください。" },
        { name: "住所1", required: "", limit: "200文字", desc: "都道府県・市区町村です。" },
        { name: "住所2", required: "", limit: "200文字", desc: "番地・ビル名です。" },
        { name: "郵送先1", required: "", limit: "100文字", desc: "会社名または個人名です。郵送する場合は必須です。" },
        { name: "郵送先2", required: "", limit: "100文字", desc: "部署名です。" },
        { name: "郵送先3", required: "", limit: "100文字", desc: "課名です。" },
        { name: "郵送先4", required: "", limit: "100文字", desc: "名前です。" },
        { name: "郵送先敬称", required: "", limit: "10文字", desc: "郵送先の宛名に付ける敬称です。" },
        { name: "メモ", required: "", limit: "2000文字", desc: "請求書などの文書には印字されません。" },
      ],
    },
    modal: {
      title: "取引先/送り先を新規登録",
      clientName: "取引先名",
      required: "必須",
      nameSuffix: "様",
      charCount: "0/40",
      corpLookup: "国税庁 法人番号公表サイトから検索して自動入力する",
      furigana: "ふりがな",
      corpNumber: "法人番号",
      corpNumberHint: "法人番号公表サイトから入力すると自動で入力されます。",
      destinationTab: "送り先",
      addTab: "+ 追加",
      managementCode: "管理コード",
      managementCodeHint: "CSV一括で請求書を作成する際に利用する任意の文字列を設定できます。",
      department: "部署・担当者",
      departmentHint: "3行まで入力できます。",
      email: "メールアドレス",
      emailPlaceholder: "a@salesflow.com",
      emailCc: "メールアドレス (CC)",
      emailCcPlaceholder: "b@salesflow.com, c@salesflow.com, ...",
      emailCcHint: "メール送信時にCCで送るメールアドレスを追加します。複数ある場合はカンマで区切ってください。",
      postalCode: "郵便番号",
      postalCodeHint: "000-0000形式(半角)で入力してください",
      postalCodeLookup: "郵便番号から検索",
      address: "住所",
      addressLine1Placeholder: "都道府県・市区町村",
      addressLine2Placeholder: "番地・ビル名",
      mailingName: "郵送先の宛名",
      mailingNameHint: "郵送の場合、1行目は必須です。",
      mailingLine1Placeholder: "会社名または個人名",
      mailingLine2Placeholder: "部署名",
      mailingLine3Placeholder: "課名",
      mailingLine4NamePlaceholder: "名前",
      honorificLabel: "敬称",
      phone: "電話番号",
      phonePlaceholder: "03012345678",
      fax: "FAX番号",
      faxPlaceholder: "03012345678",
      memo: "メモ",
      memoHint: "請求書などの文書には印字されません。",
      cancel: "キャンセル",
      register: "登録する",
    },
  },
  ko: {
    tabs: ["거래처", "일괄 등록·업데이트"],
    title: "거래처",
    createClient: "거래처 신규 등록",
    searchPlaceholder: "거래처명, 관리 코드, 배송지",
    search: "검색",
    csvDownload: "CSV 다운로드",
    csvHeaders: ["거래처명", "후리가나", "관리 코드", "부서", "이메일", "전화", "FAX"],
    tableHeaders: ["거래처", "관리 코드", "배송지", "작업"],
    edit: "편집",
    delete: "삭제",
    deleteConfirm: "이 거래처를 삭제하시겠습니까?",
    favoritesOnly: "즐겨찾기만 표시",
    favorite: "즐겨찾기",
    empty: "거래처가 없습니다",
    createDocument: "문서 작성",
    showDocument: "문서 표시",
    listToggle: "목록 / 숨기기",
    honorific: "귀중",
    bulk: {
      title: "거래처 일괄 등록·업데이트(CSV 업로드)",
      intro:
        "CSV 파일을 업로드하여 거래처를 한 번에 등록·수정할 수 있습니다. 관리 코드가 기존 거래처와 일치하면 해당 거래처를 갱신합니다.",
      uploadSection: "CSV 파일 업로드",
      chooseFile: "파일 선택",
      noFile: "선택된 파일 없음",
      upload: "업로드",
      uploadResult: "{created}건 등록, {updated}건 갱신했습니다",
      emptyFile: "CSV에 데이터 행이 없습니다.",
      uploadNotes: [
        "Excel에서 CSV 형식으로 저장한 파일을 업로드해 주세요.",
        "첫 번째 행은 헤더 행으로 처리됩니다.",
        "관리 코드가 기존 거래처와 일치하면 갱신되고, 비어 있거나 없는 코드는 신규 등록됩니다.",
        "빈 셀은 기존 값을 그대로 유지합니다(지워지지 않습니다).",
        "한 행이라도 오류가 있으면 아무것도 등록되지 않습니다.",
        "한 번에 처리할 수 있는 건수는 최대 1000건입니다.",
      ],
      templateSection: "입력용 템플릿 다운로드",
      templateUtf8: "UTF-8版",
      templateUtf8Button: "UTF-8版 입력용 템플릿",
      templateShiftJis: "Shift-JIS版\n(Excel 사용자는 여기)",
      templateShiftJisButton: "Shift-JIS版 입력용 템플릿",
      formatSection: "입력용 템플릿 형식",
      formatRows: [
        ["형식", "CSV 형식"],
        ["문자 인코딩", "UTF-8 또는 Shift-JIS"],
      ] as const,
      formatNote: "저장 시 위 형식으로 저장해 주세요.",
      fieldsSection: "입력용 템플릿 항목 설명",
      fieldsIntro: "입력용 템플릿의 각 항목은 다음과 같습니다.",
      fieldHeaders: ["항목", "필수", "제한", "설명"],
      fields: [
        { name: "거래처명", required: "○", limit: "40자", desc: "거래처의 명칭입니다." },
        { name: "후리가나", required: "", limit: "100자", desc: "정렬에 사용됩니다." },
        {
          name: "관리 코드",
          required: "",
          limit: "40자",
          desc: "갱신 기준 키입니다. 기존 거래처와 일치하면 해당 거래처를 덮어씁니다.",
        },
        { name: "법인번호", required: "", limit: "13자", desc: "일본 국세청 법인번호입니다." },
        { name: "부서·담당자", required: "", limit: "100자", desc: "부서명·담당자명입니다." },
        { name: "이메일 주소", required: "", limit: "—", desc: "형식이 올바르지 않으면 오류가 발생합니다." },
        {
          name: "이메일 주소(CC)",
          required: "",
          limit: "10건",
          desc: "여러 개인 경우 세미콜론(;)으로 구분해 주세요.",
        },
        { name: "전화번호", required: "", limit: "30자", desc: "하이픈은 있어도 됩니다." },
        { name: "FAX 번호", required: "", limit: "30자", desc: "하이픈은 있어도 됩니다." },
        { name: "경칭", required: "", limit: "10자", desc: "「様」「御中」 등을 입력합니다." },
        { name: "우편번호", required: "", limit: "8자", desc: "000-0000 형식(반각)으로 입력해 주세요." },
        { name: "주소1", required: "", limit: "200자", desc: "도도부현·시구정촌입니다." },
        { name: "주소2", required: "", limit: "200자", desc: "번지·빌딩명입니다." },
        { name: "우편 발송처1", required: "", limit: "100자", desc: "회사명 또는 개인명입니다. 우편 발송 시 필수입니다." },
        { name: "우편 발송처2", required: "", limit: "100자", desc: "부서명입니다." },
        { name: "우편 발송처3", required: "", limit: "100자", desc: "과명입니다." },
        { name: "우편 발송처4", required: "", limit: "100자", desc: "이름입니다." },
        { name: "우편 발송처 경칭", required: "", limit: "10자", desc: "우편 수신인에 붙이는 경칭입니다." },
        { name: "메모", required: "", limit: "2000자", desc: "청구서 등 문서에는 인쇄되지 않습니다." },
      ],
    },
    modal: {
      title: "거래처/배송지 신규 등록",
      clientName: "거래처명",
      required: "필수",
      nameSuffix: "",
      charCount: "0/40",
      corpLookup: "국세청 법인번호 공표 사이트에서 검색하여 자동 입력",
      furigana: "후리가나",
      corpNumber: "법인번호",
      corpNumberHint: "법인번호 공표 사이트에서 입력하면 자동으로 입력됩니다.",
      destinationTab: "배송지",
      addTab: "+ 추가",
      managementCode: "관리 코드",
      managementCodeHint: "CSV 일괄 청구서 작성 시 사용할 임의 문자열을 설정할 수 있습니다.",
      department: "부서·담당자",
      departmentHint: "최대 3행까지 입력할 수 있습니다.",
      email: "이메일 주소",
      emailPlaceholder: "a@salesflow.com",
      emailCc: "이메일 주소 (CC)",
      emailCcPlaceholder: "b@salesflow.com, c@salesflow.com, ...",
      emailCcHint: "메일 발송 시 CC로 보낼 이메일 주소를 추가합니다. 여러 개는 쉼표로 구분해 주세요.",
      postalCode: "우편번호",
      postalCodeHint: "000-0000 형식(반각)으로 입력해 주세요",
      postalCodeLookup: "우편번호로 검색",
      address: "주소",
      addressLine1Placeholder: "도도부현·시구정촌",
      addressLine2Placeholder: "번지·빌딩명",
      mailingName: "우편 발송처 수신인",
      mailingNameHint: "우편 발송 시 1행은 필수입니다.",
      mailingLine1Placeholder: "회사명 또는 개인명",
      mailingLine2Placeholder: "부서명",
      mailingLine3Placeholder: "과명",
      mailingLine4NamePlaceholder: "이름",
      honorificLabel: "경칭",
      phone: "전화번호",
      phonePlaceholder: "03012345678",
      fax: "FAX 번호",
      faxPlaceholder: "03012345678",
      memo: "메모",
      memoHint: "청구서 등 문서에는 인쇄되지 않습니다.",
      cancel: "취소",
      register: "등록하기",
    },
  },
  en: {
    tabs: ["Clients", "Bulk Registration / Update"],
    title: "Clients",
    createClient: "Register New Client",
    searchPlaceholder: "Client name, management code, destination",
    search: "Search",
    csvDownload: "CSV Download",
    csvHeaders: ["Client Name", "Furigana", "Management Code", "Department", "Email", "Phone", "FAX"],
    tableHeaders: ["Client", "Management Code", "Destination", "Actions"],
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Delete this client?",
    favoritesOnly: "Favorites only",
    favorite: "Favorite",
    empty: "No clients",
    createDocument: "Create Document",
    showDocument: "Show Document",
    listToggle: "List / Hidden",
    honorific: "",
    bulk: {
      title: "Bulk Client Registration / Update (CSV Upload)",
      intro:
        "Upload a CSV file to register or update clients at once. Rows whose management code matches an existing client update that client.",
      uploadSection: "CSV File Upload",
      chooseFile: "Choose file",
      noFile: "No file selected",
      upload: "Upload",
      uploadResult: "Registered {created}, updated {updated}",
      emptyFile: "The CSV has no data rows.",
      uploadNotes: [
        "Upload a file saved in CSV format from Excel.",
        "The first row is treated as a header row.",
        "A matching management code updates that client; a blank or unknown code creates a new client.",
        "Blank cells keep the existing value (they are not cleared).",
        "If any row has an error, nothing is registered.",
        "Up to 1000 rows can be processed at once.",
      ],
      templateSection: "Download Input Template",
      templateUtf8: "UTF-8",
      templateUtf8Button: "UTF-8 input template",
      templateShiftJis: "Shift-JIS\n(for Excel users)",
      templateShiftJisButton: "Shift-JIS input template",
      formatSection: "Input Template Format",
      formatRows: [
        ["Format", "CSV"],
        ["Encoding", "UTF-8 or Shift-JIS"],
      ] as const,
      formatNote: "Please save the file in the format above.",
      fieldsSection: "Input Template Fields",
      fieldsIntro: "The columns of the input template are as follows.",
      fieldHeaders: ["Field", "Required", "Limit", "Description"],
      fields: [
        { name: "Client name", required: "○", limit: "40 chars", desc: "Name of the client." },
        { name: "Furigana", required: "", limit: "100 chars", desc: "Used for sorting." },
        {
          name: "Management code",
          required: "",
          limit: "40 chars",
          desc: "Key used for updates. A match overwrites that existing client.",
        },
        { name: "Corporate number", required: "", limit: "13 chars", desc: "Japanese corporate number." },
        { name: "Department / contact", required: "", limit: "100 chars", desc: "Department or contact name." },
        { name: "Email", required: "", limit: "—", desc: "An invalid format results in an error." },
        {
          name: "Email (CC)",
          required: "",
          limit: "10 entries",
          desc: "Separate multiple addresses with semicolons (;).",
        },
        { name: "Phone", required: "", limit: "30 chars", desc: "Hyphens are allowed." },
        { name: "FAX", required: "", limit: "30 chars", desc: "Hyphens are allowed." },
        { name: "Honorific", required: "", limit: "10 chars", desc: "For example 様 or 御中." },
        { name: "Postal code", required: "", limit: "8 chars", desc: "Enter in 000-0000 format (half-width)." },
        { name: "Address 1", required: "", limit: "200 chars", desc: "Prefecture, city / town / village." },
        { name: "Address 2", required: "", limit: "200 chars", desc: "Street and building name." },
        { name: "Mailing line 1", required: "", limit: "100 chars", desc: "Company or individual name. Required for mailing." },
        { name: "Mailing line 2", required: "", limit: "100 chars", desc: "Department name." },
        { name: "Mailing line 3", required: "", limit: "100 chars", desc: "Section name." },
        { name: "Mailing line 4", required: "", limit: "100 chars", desc: "Person name." },
        { name: "Mailing honorific", required: "", limit: "10 chars", desc: "Honorific added to the mailing name." },
        { name: "Memo", required: "", limit: "2000 chars", desc: "Not printed on documents such as invoices." },
      ],
    },
    modal: {
      title: "Register New Client / Destination",
      clientName: "Client Name",
      required: "Required",
      nameSuffix: "",
      charCount: "0/40",
      corpLookup: "Search National Tax Agency Corporate Number site and auto-fill",
      furigana: "Furigana",
      corpNumber: "Corporate Number",
      corpNumberHint: "Automatically filled when entered from the Corporate Number database.",
      destinationTab: "Destination",
      addTab: "+ Add",
      managementCode: "Management Code",
      managementCodeHint: "Set any string used when creating invoices in bulk via CSV.",
      department: "Department / Contact",
      departmentHint: "Up to 3 lines can be entered.",
      email: "Email Address",
      emailPlaceholder: "a@salesflow.com",
      emailCc: "Email Address (CC)",
      emailCcPlaceholder: "b@salesflow.com, c@salesflow.com, ...",
      emailCcHint: "Add email addresses to be CC'd. Use commas for multiple entries.",
      postalCode: "Postal Code",
      postalCodeHint: "Enter in 000-0000 format (half-width)",
      postalCodeLookup: "Search by postal code",
      address: "Address",
      addressLine1Placeholder: "Prefecture, City/Town/Village",
      addressLine2Placeholder: "Street, Building name",
      mailingName: "Mailing Address Name",
      mailingNameHint: "For mailing, the first line is mandatory.",
      mailingLine1Placeholder: "Company or individual name",
      mailingLine2Placeholder: "Department name",
      mailingLine3Placeholder: "Section name",
      mailingLine4NamePlaceholder: "Name",
      honorificLabel: "Honorific",
      phone: "Phone Number",
      phonePlaceholder: "03012345678",
      fax: "FAX Number",
      faxPlaceholder: "03012345678",
      memo: "Memo",
      memoHint: "Will not be printed on documents such as invoices.",
      cancel: "Cancel",
      register: "Register",
    },
  },
} as const;

export function getClientsContent(lang: AppLocale) {
  return labels[lang];
}

export function getClientsHref(_lang: AppLocale, page: "list" | "bulk" = "list") {
  const base = "/clients";
  return page === "bulk" ? `${base}/bulk` : base;
}
