import type { AppLocale } from "@/contexts/language-context";

const labels = {
  ja: {
    title: "受信箱",
    helpLink: "受信箱機能について",
    emailAlert: {
      title: "Gmailと連携して受信文書を取り込みます。",
      body: "下のボタンからGoogleアカウントを連携すると、受信トレイのメールがこの受信箱に表示されます。",
      button: "Gmailを連携する",
    },
    gmail: {
      connected: "連携中",
      connect: "Gmailを連携",
      disconnect: "連携を解除",
      syncNow: "今すぐ同期",
      syncing: "同期中…",
      lastSync: "最終同期",
      syncError: "同期エラー",
      connectedToast: "Gmailを連携しました。",
      disconnectedToast: "Gmail連携を解除しました。",
      syncedToast: "同期が完了しました。",
      sendScopeMissingTitle: "メール送信の権限がありません",
      sendScopeMissingBody:
        "自動作成予約の自動メール送信には Gmail の送信権限が必要です。再連携して送信を許可してください。",
      reconnect: "再連携する",
      lastSendError: "送信エラー",
    },
    markAllRead: "すべて既読にする",
    backToList: "受信箱へ戻る",
    detailTitle: "受信メッセージ",
    from: "差出人",
    receivedAt: "受信日時",
    body: "本文",
    attachments: "添付ファイル",
    download: "ダウンロード",
    empty: "受信した文書はありません",
    listHeaders: ["種別", "件名", "受信日時", "状態"],
    kindLabels: {
      received_document: "受信文書",
      system: "システム",
      announcement: "お知らせ",
    },
    unread: "未読",
    read: "既読",
    unreadOnly: "未読のみ",
    all: "すべて",
    noSubject: "（件名なし）",
  },
  ko: {
    title: "받은 문서함",
    helpLink: "받은 문서함 기능 안내",
    emailAlert: {
      title: "Gmail을 연동해 수신 문서를 가져옵니다.",
      body: "아래 버튼으로 Google 계정을 연동하면 받은편지함 메일이 이 문서함에 표시됩니다.",
      button: "Gmail 연동",
    },
    gmail: {
      connected: "연동됨",
      connect: "Gmail 연동",
      disconnect: "연동 해제",
      syncNow: "지금 동기화",
      syncing: "동기화 중…",
      lastSync: "마지막 동기화",
      syncError: "동기화 오류",
      connectedToast: "Gmail을 연동했습니다.",
      disconnectedToast: "Gmail 연동을 해제했습니다.",
      syncedToast: "동기화가 완료되었습니다.",
      sendScopeMissingTitle: "메일 발송 권한이 없습니다",
      sendScopeMissingBody:
        "자동 작성 예약의 자동 메일 발송에는 Gmail 발송 권한이 필요합니다. 재연동해서 발송을 허용해 주세요.",
      reconnect: "재연동",
      lastSendError: "발송 오류",
    },
    markAllRead: "모두 읽음 처리",
    backToList: "받은 문서함으로",
    detailTitle: "수신 메시지",
    from: "보낸 사람",
    receivedAt: "수신 일시",
    body: "본문",
    attachments: "첨부 파일",
    download: "다운로드",
    empty: "수신한 문서가 없습니다",
    listHeaders: ["종류", "제목", "수신 일시", "상태"],
    kindLabels: {
      received_document: "수신 문서",
      system: "시스템",
      announcement: "공지",
    },
    unread: "읽지 않음",
    read: "읽음",
    unreadOnly: "읽지 않은 것만",
    all: "전체",
    noSubject: "(제목 없음)",
  },
  en: {
    title: "Inbox",
    helpLink: "About the inbox feature",
    emailAlert: {
      title: "Connect Gmail to import received documents.",
      body: "Link your Google account below to show inbox emails in this document inbox.",
      button: "Connect Gmail",
    },
    gmail: {
      connected: "Connected",
      connect: "Connect Gmail",
      disconnect: "Disconnect",
      syncNow: "Sync now",
      syncing: "Syncing…",
      lastSync: "Last sync",
      syncError: "Sync error",
      connectedToast: "Gmail connected.",
      disconnectedToast: "Gmail disconnected.",
      syncedToast: "Sync completed.",
      sendScopeMissingTitle: "No permission to send email",
      sendScopeMissingBody:
        "Automatic emails for auto-create schedules need Gmail send permission. Reconnect to grant it.",
      reconnect: "Reconnect",
      lastSendError: "Send error",
    },
    markAllRead: "Mark all as read",
    backToList: "Back to inbox",
    detailTitle: "Received message",
    from: "From",
    receivedAt: "Received",
    body: "Body",
    attachments: "Attachments",
    download: "Download",
    empty: "No received documents",
    listHeaders: ["Type", "Subject", "Received", "Status"],
    kindLabels: {
      received_document: "Received document",
      system: "System",
      announcement: "Announcement",
    },
    unread: "Unread",
    read: "Read",
    unreadOnly: "Unread only",
    all: "All",
    noSubject: "(No subject)",
  },
} as const;

export function getInboxContent(lang: AppLocale) {
  return labels[lang];
}
